import { q, type ReadingPassageSeed } from "../readingBankTypes";

export const ARTS_PASSAGES: readonly ReadingPassageSeed[] = [
    {
        id: "60000000-0000-4000-8000-000000000025",

        slug: "searching-for-blue",
        title: "The Search for a Stable Blue",
        topicEs: "Historia de pigmentos azules",
        genre: "arts",
        cefr: "B1",
        difficulty: 1,
        length: "short",
        estimatedMinutes: 5,
        paragraphs: [
            "For painters, a beautiful color is useful only if it can be prepared, applied, and preserved. Stable blue pigments were historically difficult to obtain. Ground lapis lazuli produced a brilliant blue, but the stone traveled through long trade routes and was expensive. Artists and patrons sometimes reserved it for the most important parts of an image.",
            "Other blue materials had drawbacks. Some changed color when mixed with particular substances, while plant-based dyes could fade in light. Workshops developed careful recipes and applied protective layers, but results still varied. A pigment’s reputation depended not only on its initial appearance but on how it aged.",
            "The development of synthetic blues expanded access and gave artists new choices. It did not simply replace older materials; painters selected pigments for hue, texture, cost, symbolism, and compatibility. The history of blue therefore reflects chemistry and trade as much as artistic preference.",
        ],
        questions: [
            q("70000000-0000-4000-8000-000000000151", 
                "READ_MAIN_IDEA",
                "Which factor shaped artists’ historical use of blue according to the passage?",
                "The color’s material cost, stability, and chemical behavior",
                ["A universal ban on blue images", "The absence of trade between regions", "A belief that every blue pigment was identical"],
                "El texto relaciona disponibilidad, envejecimiento, compatibilidad y simbolismo con decisiones artísticas.",
                3,
                "reflects chemistry and trade as much as artistic preference",
                ["No se menciona una prohibición general.", "El lapislázuli viajaba por rutas comerciales.", "Los pigmentos tenían propiedades distintas."],
            ),
            q("70000000-0000-4000-8000-000000000152", 
                "READ_DETAIL",
                "Why was lapis lazuli sometimes reserved for important areas?",
                "It produced a brilliant color but was costly.",
                ["It was the only material that faded instantly.", "It could be found beside every workshop.", "It always damaged protective layers."],
                "El primer párrafo vincula el azul brillante con largas rutas y precio elevado.",
                1,
                "produced a brilliant blue, but the stone traveled through long trade routes and was expensive",
                ["El desvanecimiento se asocia a ciertos tintes vegetales.", "La distancia comercial contradice disponibilidad local universal.", "No se afirma daño inevitable a capas protectoras."],
            ),
            q("70000000-0000-4000-8000-000000000153", 
                "READ_VOCAB_CONTEXT",
                "The word “drawbacks” in paragraph 2 is closest in meaning to",
                "disadvantages",
                ["recipes", "symbols", "trade routes"],
                "Las oraciones siguientes enumeran problemas de cambio de color y pérdida por luz.",
                2,
                "Other blue materials had drawbacks.",
                ["Las recetas intentaban reducir problemas.", "El simbolismo es un criterio de elección posterior.", "Las rutas explican costo, no el significado de la palabra."],
            ),
            q("70000000-0000-4000-8000-000000000154", 
                "READ_INFERENCE",
                "Why would a workshop keep detailed pigment recipes?",
                "Small differences in preparation could affect color and durability.",
                ["Painters were forbidden to observe finished colors.", "All materials behaved the same in every mixture.", "Synthetic pigments existed before mineral pigments."],
                "La variabilidad de resultados y compatibilidad vuelve valioso controlar preparación y capas.",
                2,
                "Workshops developed careful recipes",
                ["La observación del resultado era esencial.", "El texto destaca reacciones distintas.", "Los sintéticos se desarrollaron después."],
                2,
            ),
            q("70000000-0000-4000-8000-000000000155", 
                "READ_PARAPHRASE",
                "How did synthetic blues change artistic choice according to the final paragraph?",
                "New synthetic pigments broadened choices without eliminating the reasons artists might prefer older ones.",
                ["Synthetic blue ended all artistic use of minerals.", "Painters selected colors only by price.", "Chemistry became irrelevant after synthetic blue appeared."],
                "El cierre presenta una ampliación, no una sustitución total, y conserva múltiples criterios de elección.",
                3,
                "did not simply replace older materials",
                ["El texto niega el reemplazo simple.", "Matiz, textura y simbolismo también importaban.", "La compatibilidad química siguió siendo un criterio."],
                2,
            ),
        ],
    },
    {
        id: "60000000-0000-4000-8000-000000000026",

        slug: "writing-down-dance",
        title: "Writing Down Movement",
        topicEs: "Sistemas de notación coreográfica",
        genre: "arts",
        cefr: "B1",
        difficulty: 2,
        length: "short",
        estimatedMinutes: 5,
        paragraphs: [
            "Dance disappears as it is performed, so choreographers have long searched for ways to record movement. Written notation can preserve sequences, directions, timing, and relationships among dancers. Some systems use symbols placed on a staff, while others combine floor diagrams with verbal descriptions.",
            "No notation captures a performance completely. The angle of a hand can be marked, but qualities such as tension, hesitation, or weight may depend on interpretation. Detailed scores also require specialized training to read. For this reason, dancers often combine notation with oral coaching, photographs, or video.",
            "Recording does more than support reconstruction. A score can reveal patterns that are difficult to notice while watching at full speed, and it allows researchers to compare versions created in different periods. Notation is therefore less a replacement for performance than a tool for preserving and analyzing selected features of it.",
        ],
        questions: [
            q("70000000-0000-4000-8000-000000000156", 
                "READ_PRIMARY_PURPOSE",
                "What does the author explain about dance notation?",
                "It records and supports analysis of movement but cannot preserve every performance quality.",
                ["It makes live performance unnecessary.", "It can be understood without any training.", "It records only the names of dancers."],
                "El pasaje combina usos de preservación y análisis con límites de expresividad y lectura.",
                3,
                "a tool for preserving and analyzing selected features",
                ["La notación complementa, no reemplaza, la actuación.", "Los sistemas detallados requieren aprendizaje.", "Se registran secuencias, tiempo, espacio y relaciones."],
            ),
            q("70000000-0000-4000-8000-000000000157", 
                "READ_DETAIL",
                "Which information can dance notation preserve?",
                "Timing and relationships among dancers",
                ["The exact feelings of every audience member", "The future cost of a theater", "The chemical composition of costumes"],
                "El primer párrafo enumera secuencias, direcciones, tiempo y relaciones entre intérpretes.",
                1,
                "timing, and relationships among dancers",
                ["La reacción del público no forma parte de la partitura.", "Los costos teatrales no se mencionan.", "La composición de vestuario no es movimiento."],
            ),
            q("70000000-0000-4000-8000-000000000158", 
                "READ_NEGATIVE_DETAIL",
                "All of the following may supplement written notation EXCEPT",
                "water-quality measurements",
                ["oral coaching", "photographs", "video"],
                "El segundo párrafo enumera las tres formas de apoyo; medir agua no pertenece al proceso coreográfico descrito.",
                2,
                "combine notation with oral coaching, photographs, or video",
                ["La enseñanza oral ayuda con interpretación.", "Las fotografías conservan posiciones.", "El video registra movimiento temporal."],
            ),
            q("70000000-0000-4000-8000-000000000159", 
                "READ_INFERENCE",
                "Why might a researcher study a score in addition to a video?",
                "The score may make structural patterns easier to compare.",
                ["The score contains every quality with no ambiguity.", "Video cannot show movement.", "A score eliminates differences between performances."],
                "El último párrafo señala que la representación escrita vuelve visibles patrones y facilita comparación entre versiones.",
                3,
                "allows researchers to compare versions",
                ["El pasaje reconoce cualidades no capturadas.", "El video sí registra movimiento.", "Las diferencias son objeto de comparación, no se eliminan."],
                2,
            ),
            q("70000000-0000-4000-8000-000000000160", 
                "READ_REFERENCE",
                "The word “it” at the end of paragraph 3 refers to",
                "performance",
                ["the researcher", "the staff", "oral coaching"],
                "La notación preserva y analiza características seleccionadas de la actuación.",
                3,
                "selected features of it",
                ["El investigador utiliza la herramienta, pero no es su referente.", "El pentagrama es un formato de símbolos.", "La enseñanza oral es un complemento."],
            ),
        ],
    },
    {
        id: "60000000-0000-4000-8000-000000000027",

        slug: "oral-epics-in-performance",
        title: "An Epic Recreated",
        topicEs: "Tradiciones épicas orales",
        genre: "arts",
        cefr: "B2",
        difficulty: 2,
        length: "standard",
        estimatedMinutes: 7,
        paragraphs: [
            "An oral epic may be described as a long story passed from one performer to another, but this description can suggest that each performance is a copy of a fixed original. In many traditions, singers compose while performing. They draw on known episodes, repeated phrases, rhythmic patterns, and character types, combining them in response to the occasion.",
            "Formulaic language helps make this possible. A phrase that fits a familiar rhythm can be inserted while the performer plans what comes next. Repetition also helps listeners follow a story over many hours. The formulas are not necessarily signs of poor memory; they are resources that support fluency and variation.",
            "Audiences influence the event. A performer may expand a battle scene for listeners who value heroic detail or shorten a genealogical section when time is limited. Local names and current concerns can enter an old narrative. Listeners may also request a familiar episode or respond aloud at expected moments. Two performances can therefore be recognizably the same epic while differing greatly in length and emphasis.",
            "Recording a performance preserves one valuable version but changes how it may be understood. A written transcription removes voice, gesture, timing, and audience response, while an audio or video recording still captures only one particular occasion. Scholars compare multiple performances and learn about the wider social, cultural, and historical setting so that variation is treated as part of the art rather than as corruption of a perfect text.",
        ],
        questions: [
            q("70000000-0000-4000-8000-000000000161", 
                "READ_MAIN_IDEA",
                "Which idea about oral epics does the passage emphasize?",
                "Performers recreate a shared tradition through formulas, context, and audience interaction.",
                ["Every performance reproduces a fixed text word for word.", "Repeated language proves that performers have poor memories.", "A single recording contains the complete tradition."],
                "El texto cuestiona el modelo de copia fija y explica composición situada y variación artística.",
                4,
                "variation is treated as part of the art",
                ["Las versiones pueden variar mucho.", "Las fórmulas apoyan fluidez y planificación.", "Una grabación conserva solo una ocasión."],
            ),
            q("70000000-0000-4000-8000-000000000162", 
                "READ_RHETORICAL_PURPOSE",
                "Why does the author discuss formulaic language?",
                "To explain a technique that supports composition during performance",
                ["To show that listeners dislike repetition", "To prove that epics have no rhythm", "To identify errors introduced only by writing"],
                "Las frases rítmicas conocidas dan tiempo para planear y ayudan al seguimiento del público.",
                2,
                "support fluency and variation",
                ["La repetición ayuda a los oyentes.", "Las fórmulas encajan precisamente en patrones rítmicos.", "Funcionan dentro de la actuación oral."],
            ),
            q("70000000-0000-4000-8000-000000000163", 
                "READ_DETAIL",
                "What might cause a performer to shorten a genealogical section?",
                "Limited time",
                ["A ban on local names", "The absence of any audience", "The invention of video"],
                "El tercer párrafo contrasta expansión por interés del público con reducción cuando el tiempo escasea.",
                3,
                "shorten a genealogical section when time is limited",
                ["Los nombres locales pueden incorporarse.", "El público influye en decisiones.", "La grabación se discute después."],
            ),
            q("70000000-0000-4000-8000-000000000164", 
                "READ_INFERENCE",
                "How can two performances be considered the same epic despite major differences?",
                "They draw on shared characters, episodes, and patterns.",
                ["They must have exactly the same number of words.", "They are both written by one audience member.", "They exclude all current concerns."],
                "La identidad reside en recursos narrativos compartidos, mientras longitud y énfasis pueden adaptarse.",
                1,
                "known episodes, repeated phrases, rhythmic patterns, and character types",
                ["La variación verbal es una característica central.", "La composición corresponde al intérprete.", "Los asuntos actuales pueden entrar en la narración."],
                2,
            ),
            q("70000000-0000-4000-8000-000000000165", 
                "READ_TONE",
                "How does the author view variation in oral performance?",
                "As a meaningful feature that should be studied rather than corrected away",
                ["As evidence that every singer is careless", "As a problem solved completely by transcription", "As irrelevant to the social setting"],
                "El cierre pide comparar versiones y tratar la variación como parte del arte.",
                4,
                "rather than as corruption of a perfect text",
                ["Las fórmulas y adaptaciones son recursos, no descuido.", "La transcripción elimina dimensiones de la actuación.", "El contexto social es necesario para interpretar cambios."],
                3,
            ),
        ],
    },
    {
        id: "60000000-0000-4000-8000-000000000028",

        slug: "lighting-a-museum",
        title: "Light That Reveals and Damages",
        topicEs: "Conservación e iluminación museística",
        genre: "arts",
        cefr: "B1",
        difficulty: 2,
        length: "short",
        estimatedMinutes: 5,
        paragraphs: [
            "Museums need light, so visitors can see, but light can permanently damage sensitive objects. Energy absorbed by dyes, paper, and textiles can trigger chemical changes that fade colors or weaken fibers. The damage accumulates: low light for a long period may have an effect similar to brighter light for a shorter one.",
            "Conservators manage exposure rather than attempting to eliminate it. They choose lamps that emit little ultraviolet radiation, limit brightness, and rotate fragile works off display. Motion sensors may keep a gallery dim until someone enters. Exhibition designers also use contrast and directed light so that an object remains legible at a lower overall level.",
            "There is no single safe brightness for every collection. Stone and metal usually tolerate more exposure than watercolor or historic fabric. Decisions balance access with preservation, recognizing that displaying an object now consumes part of the limited light exposure it can safely receive over its lifetime.",
        ],
        questions: [
            q("70000000-0000-4000-8000-000000000166", 
                "READ_MAIN_IDEA",
                "What balance must museums manage according to the passage?",
                "Making objects visible while limiting cumulative light damage",
                ["Keeping every gallery completely dark", "Exposing paper to more light than stone", "Replacing all original objects with lamps"],
                "El texto describe daño acumulativo y estrategias para permitir acceso sin agotar la tolerancia del objeto.",
                3,
                "balance access with preservation",
                ["La iluminación es necesaria para ver.", "El papel suele ser más sensible.", "Las lámparas iluminan objetos, no los sustituyen."],
            ),
            q("70000000-0000-4000-8000-000000000167", 
                "READ_DETAIL",
                "Why might a museum rotate a fragile work off display?",
                "To reduce its total exposure to damaging light",
                ["To increase the ultraviolet radiation it receives", "To make stone objects fade faster", "To eliminate the need for conservation decisions"],
                "La rotación limita el tiempo iluminado y, por tanto, el daño acumulado.",
                2,
                "rotate fragile works off display",
                ["Se eligen lámparas con poca radiación ultravioleta.", "La rotación protege la obra frágil, no perjudica piedra.", "Es una decisión de conservación, no su eliminación."],
            ),
            q("70000000-0000-4000-8000-000000000168", 
                "READ_PARAPHRASE",
                "What does the passage mean by saying that displaying an object “consumes” light exposure?",
                "Each period on display uses part of the object’s lifetime tolerance.",
                ["The object produces electricity for the gallery.", "Light damage can always be reversed later.", "Visitors remove light from the room."],
                "El verbo presenta la exposición segura como un presupuesto limitado que disminuye con el tiempo.",
                3,
                "consumes part of the limited light exposure",
                ["No se describe generación eléctrica.", "El daño se caracteriza como permanente.", "La entrada de visitantes activa luz en algunos casos."],
                2,
            ),
            q("70000000-0000-4000-8000-000000000169", 
                "READ_NEGATIVE_DETAIL",
                "Which action is NOT mentioned as a way to reduce harmful exposure?",
                "Heating the gallery to a high temperature",
                ["using low-ultraviolet lamps", "limiting brightness", "installing motion sensors"],
                "La temperatura elevada no aparece como estrategia; las otras tres sí se enumeran.",
                2,
                "choose lamps that emit little ultraviolet radiation, limit brightness",
                ["Reducir ultravioleta limita daño.", "La intensidad se controla.", "Los sensores mantienen penumbra sin visitantes."],
            ),
            q("70000000-0000-4000-8000-000000000170", 
                "READ_INFERENCE",
                "Why can directed light improve preservation?",
                "It can make the object readable without brightly lighting the entire room.",
                ["It guarantees that no light reaches the object.", "It makes every material equally durable.", "It increases cumulative exposure everywhere."],
                "El contraste concentra la luz necesaria y permite bajar el nivel general.",
                2,
                "remains legible at a lower overall level",
                ["El objeto debe recibir algo de luz para verse.", "La sensibilidad material sigue variando.", "El objetivo es reducir exposición total."],
                2,
            ),
        ],
    },
    {
        id: "60000000-0000-4000-8000-000000000029",

        slug: "patterns-that-carry-memory",
        title: "Patterns That Carry Memory",
        topicEs: "Textiles como sistemas culturales",
        genre: "arts",
        cefr: "B2",
        difficulty: 2,
        length: "standard",
        estimatedMinutes: 7,
        paragraphs: [
            "A woven pattern can function as decoration, technical solution, social marker, and record of exchange at the same time. The structure of a loom determines which movements are convenient, but weavers also adapt tools to achieve desired forms. Repeated geometric units may help maintain tension and count threads while producing a recognizable visual rhythm. Small irregularities can record decisions made during the work.",
            "Meanings attached to patterns are rarely fixed everywhere. A motif associated with one community may be borrowed, altered, or sold in another. Colors can indicate age, occasion, rank, or simply access to particular dyes. The same cloth may also acquire a new meaning when given as a gift. Interpreting a textile therefore requires information about who made it, who used it, where it circulated, and when.",
            "Museum labels have sometimes assigned one definitive meaning to a design based on a single collector’s note. Such explanations are attractive because they are concise, but they can freeze a flexible tradition. The collector may have misunderstood a translation or recorded one person’s view as universal. Contemporary weavers may disagree with the label, use the motif differently, or intentionally create a new interpretation.",
            "Technical study adds another layer. Examining fibers, dye molecules, and thread direction can reveal repairs, imported materials, or changes made during weaving. It may also distinguish a later replacement from the original border. These findings do not replace knowledge held by makers. The strongest interpretation brings material analysis into conversation with oral history, visual comparison, and present-day practice.",
        ],
        questions: [
            q("70000000-0000-4000-8000-000000000171", 
                "READ_MAIN_IDEA",
                "What approach to interpreting textile patterns does the passage support?",
                "Combining material evidence with cultural context and makers’ knowledge",
                ["Assigning one permanent meaning to every motif", "Ignoring how a textile was made", "Treating all geometric patterns as accidental"],
                "El texto insiste en variación de significados y en integrar análisis técnico, historia oral y práctica viva.",
                4,
                "brings material analysis into conversation with oral history",
                ["Los significados pueden cambiar entre lugares y tiempos.", "La estructura técnica aporta información.", "Los patrones pueden cumplir funciones técnicas y sociales."],
            ),
            q("70000000-0000-4000-8000-000000000172", 
                "READ_DETAIL",
                "How can repeated geometric units assist a weaver?",
                "They can help count threads and maintain tension.",
                ["They remove the need for a loom.", "They guarantee access to imported dyes.", "They prevent anyone from borrowing a motif."],
                "El primer párrafo vincula repetición con control del proceso además de ritmo visual.",
                1,
                "help maintain tension and count threads",
                ["El telar condiciona y posibilita la estructura.", "Los tintes son un factor social distinto.", "Los motivos pueden circular entre comunidades."],
            ),
            q("70000000-0000-4000-8000-000000000173", 
                "READ_VOCAB_CONTEXT",
                "The word “freeze” in paragraph 3 is closest in meaning to",
                "treat as unchanging",
                ["make physically cold", "repair with new thread", "photograph under bright light"],
                "Una etiqueta definitiva puede presentar una tradición flexible como si tuviera un significado inmóvil.",
                3,
                "freeze a flexible tradition",
                ["El contexto es interpretación, no temperatura.", "Las reparaciones se detectan mediante estudio técnico.", "La fotografía no aparece en esta frase."],
            ),
            q("70000000-0000-4000-8000-000000000174", 
                "READ_INFERENCE",
                "Why might contemporary weavers disagree with an older museum label?",
                "The label may generalize from limited evidence and ignore changing practice.",
                ["Weavers cannot recognize any visual pattern.", "Museum labels always describe fiber chemistry only.", "Older textiles contain no cultural information."],
                "Basarse en una nota única puede imponer una lectura que los propios creadores usan de otras maneras.",
                3,
                "based on a single collector’s note",
                ["Los tejedores producen y transforman motivos.", "Las etiquetas discutidas asignan significados culturales.", "El texto valora los textiles como registros complejos."],
                2,
            ),
            q("70000000-0000-4000-8000-000000000175", 
                "READ_ORGANIZATION",
                "How does the final paragraph relate to the preceding discussion?",
                "It adds scientific material analysis while insisting that it be integrated with cultural knowledge.",
                ["It rejects every form of fiber examination.", "It proves that collector notes are always complete.", "It changes the topic to railway engineering."],
                "El cierre amplía las fuentes de evidencia sin permitir que una reemplace a las demás.",
                4,
                "These findings do not replace knowledge held by makers.",
                ["Se enumeran fibras, tintes y dirección de hilo como útiles.", "El tercer párrafo critica la evidencia única.", "El tema continúa siendo interpretación textil."],
                3,
            ),
        ],
    },
    {
        id: "60000000-0000-4000-8000-000000000030",

        slug: "rooms-designed-to-listen",
        title: "Rooms Designed to Listen",
        topicEs: "Acústica arquitectónica",
        genre: "arts",
        cefr: "B2",
        difficulty: 2,
        length: "standard",
        estimatedMinutes: 7,
        paragraphs: [
            "A concert hall does not merely contain sound; its shape and surfaces participate in what listeners hear. Sound travels directly from a performer and also reaches the audience after reflecting from walls, ceilings, seats, and people. Reflections arriving very soon can strengthen clarity and fullness, while much later ones may be perceived as echoes. Their direction also affects whether sound feels spatially enveloping.",
            "The ideal balance depends on the performance. Speech benefits from clarity because listeners must distinguish rapid consonants. Some orchestral music benefits from longer reverberation that blends tones, while extremely long reverberation can blur detail. Musicians also need to hear one another clearly enough to coordinate. A room praised for one use may frustrate another.",
            "Architects adjust geometry and materials to manage reflection and absorption. Irregular surfaces scatter sound in several directions; heavy curtains and upholstered seats absorb more energy. Empty and occupied rooms can sound different because audiences themselves absorb sound. Temperature and humidity can produce smaller changes in how sound travels. Designers sometimes choose seats whose absorption resembles that of a person so rehearsals and performances remain more consistent.",
            "Modern halls may include movable panels, curtains, or overhead reflectors. These elements allow one room to support lectures, chamber groups, and larger ensembles. Technicians can change configurations between events and document settings that worked well. Adjustable design does not create a perfect setting for every event, but it recognizes acoustics as a set of trade-offs rather than a single measure of quality.",
        ],
        questions: [
            q("70000000-0000-4000-8000-000000000176", 
                "READ_PRIMARY_PURPOSE",
                "What does the passage explain about concert-hall acoustics?",
                "Good acoustic design balances reflections differently for different performances.",
                ["Every event requires the longest possible echo.", "Only the performers affect what an audience hears.", "One fixed material creates perfect sound in all rooms."],
                "El texto compara usos, materiales, ocupación y elementos móviles para mostrar compromisos acústicos.",
                4,
                "a set of trade-offs rather than a single measure of quality",
                ["La reverberación excesiva puede borrar detalle.", "Superficies, forma, asientos y público participan.", "Se combinan geometría y materiales ajustables."],
            ),
            q("70000000-0000-4000-8000-000000000177", 
                "READ_DETAIL",
                "Why does speech generally require acoustic clarity?",
                "Listeners need to distinguish quickly changing consonants.",
                ["Speakers produce no reflected sound.", "Speech is always performed in an empty room.", "Curtains make words travel faster than light."],
                "El segundo párrafo da una razón lingüística directa para controlar reverberación en habla.",
                2,
                "listeners must distinguish rapid consonants",
                ["Toda fuente genera sonido directo y reflejado.", "La ocupación puede variar.", "Las cortinas absorben sonido; no alteran la velocidad de luz."],
            ),
            q("70000000-0000-4000-8000-000000000178", 
                "READ_REFERENCE",
                "The phrase “These elements” in paragraph 4 refers to",
                "movable panels, curtains, and overhead reflectors",
                ["rapid consonants", "audience members", "late echoes only"],
                "El demostrativo resume los componentes ajustables enumerados en la oración anterior.",
                4,
                "movable panels, curtains, or overhead reflectors. These elements",
                ["Las consonantes motivan claridad pero no son elementos arquitectónicos.", "El público absorbe sonido, aunque no es el antecedente inmediato.", "Los dispositivos gestionan múltiples reflexiones."],
            ),
            q("70000000-0000-4000-8000-000000000179", 
                "READ_INFERENCE",
                "Why might designers test a hall with and without an audience?",
                "People absorb sound and can change the room’s reverberation.",
                ["Audiences rebuild the ceiling during performances.", "An empty room has no surfaces.", "Sound cannot travel when seats are occupied."],
                "El tercer párrafo advierte que la absorción del público altera la respuesta respecto de un ensayo vacío.",
                3,
                "audiences themselves absorb sound",
                ["No se atribuye construcción al público.", "Paredes, asientos y techo siguen presentes.", "El sonido llega por rutas directas y reflejadas."],
                2,
            ),
            q("70000000-0000-4000-8000-000000000180", 
                "READ_PARAPHRASE",
                "How should acoustic quality be evaluated according to the final sentence?",
                "Acoustic quality depends on choices among competing benefits, not one universally best value.",
                ["A hall should never be adjusted after construction.", "Every room can be perfect for every event.", "Only loudness determines acoustic quality."],
                "La conclusión define el diseño como negociación entre claridad, mezcla, uso y consistencia.",
                4,
                "trade-offs rather than a single measure of quality",
                ["Los paneles y cortinas permiten ajuste.", "Se niega perfección universal.", "Se analizan tiempo y dirección de reflexiones, no solo volumen."],
                3,
            ),
        ],
    },
    {
        id: "60000000-0000-4000-8000-000000000031",

        slug: "restoring-what-remains",
        title: "Restoring What Remains",
        topicEs: "Ética de restauración artística",
        genre: "arts",
        cefr: "B2",
        difficulty: 3,
        length: "long",
        estimatedMinutes: 13,
        paragraphs: [
            "When an artwork is damaged, restoration does not simply return it to an obvious original state. Materials age, earlier repairs alter surfaces, and evidence about the artist’s intention may be incomplete. Different owners may also value different periods in the object’s life. Conservators must decide what kind of change is justified, visible, reversible, and documented.",
            "Cleaning illustrates the difficulty. Removing darkened varnish can recover contrast and color, but the boundary between varnish and original glaze may be uncertain. A solvent strong enough to remove one layer can affect another. Earlier cleanings may already have thinned delicate paint. Conservators test small areas and examine samples, yet every cleaning still involves judgment about which traces of age belong to the object’s history.",
            "Missing areas create a different problem. Leaving a loss untouched makes damage visible but can interrupt the image. Filling it completely may produce a visually continuous work while giving modern additions too much authority. Large losses can require structural support even when no image is reconstructed. Some approaches use retouching that blends at normal viewing distance but becomes distinguishable under close inspection or special light.",
            "Reversibility is often treated as an ethical goal. A repair material should ideally be removable without harming the original, allowing future conservators to respond to new evidence or better technology. Perfect reversibility is rare, however. Even a removable coating may change how an old surface ages, and the act of removing it can create stress. Conservators therefore also consider compatibility and predictable aging.",
            "The history of an object may include previous restorations. An old addition can be technically inaccurate yet culturally important because viewers have known the work in that form for generations. Removing it may reveal earlier material while erasing part of the object’s later biography. Ownership, law, and ritual use can shape who participates in the decision. Conservators consult curators, historians, scientists, owners, and sometimes communities connected to the work.",
            "Digital reconstruction offers another option. A projection or screen can show a proposed original appearance without placing paint on the object. Digital models can also compare several hypotheses. Displayed simulations may be updated when evidence changes. They are not neutral: choices about color, missing detail, and certainty still shape what viewers see. Clear labels should distinguish evidence from speculation.",
            "Good restoration is therefore not measured by making intervention invisible at any cost. It aims to stabilize material, support understanding, and remain honest about uncertainty. Detailed records preserve photographs, tests, materials, and reasoning so future researchers can evaluate not only the artwork but the decisions made around it. Records also identify areas that should be monitored after treatment and note changing environmental conditions that could affect the repair over time in storage or transit.",
        ],
        questions: [
            q("70000000-0000-4000-8000-000000000181", 
                "READ_MAIN_IDEA",
                "Which principle of restoration is developed throughout the passage?",
                "Intervention requires transparent judgments that balance material stability, appearance, history, and uncertainty.",
                ["Every damaged artwork has one obvious original state.", "The best repair is always completely invisible.", "Digital reconstruction eliminates interpretation."],
                "Los ejemplos de limpieza, faltantes, reversibilidad, reparaciones antiguas y modelos digitales exigen decisiones documentadas.",
                7,
                "remain honest about uncertainty",
                ["La intención puede ser incompleta y el envejecimiento complejo.", "El cierre rechaza invisibilidad a cualquier costo.", "Los modelos también incorporan decisiones."],
                3,
            ),
            q("70000000-0000-4000-8000-000000000182", 
                "READ_DETAIL",
                "Why can removing varnish threaten an original glaze?",
                "A solvent may affect both layers when their boundary is uncertain.",
                ["Varnish is always part of the artist’s original paint.", "Glaze cannot be examined with samples.", "Darkened surfaces contain no historical evidence."],
                "El segundo párrafo vincula límite incierto y acción química del solvente sobre capas distintas.",
                2,
                "A solvent strong enough to remove one layer can affect another.",
                ["El barniz puede ser posterior y se distingue del esmalte original.", "Se examinan muestras y zonas pequeñas.", "Las huellas de edad pueden pertenecer a la historia del objeto."],
            ),
            q("70000000-0000-4000-8000-000000000183", 
                "READ_VOCAB_CONTEXT",
                "The word “loss” in paragraph 3 is closest in meaning to",
                "an area where original material is missing",
                ["a financial expense", "a forgotten museum address", "a removable varnish"],
                "El párrafo contrapone dejar el faltante, rellenarlo y retocarlo dentro de la imagen.",
                3,
                "Leaving a loss untouched makes damage visible",
                ["El contexto es físico, no económico.", "No se discute ubicación del museo.", "El barniz es una capa, no el vacío de material."],
            ),
            q("70000000-0000-4000-8000-000000000184", 
                "READ_RHETORICAL_PURPOSE",
                "Why does the author discuss retouching visible only at close range?",
                "To illustrate a compromise between visual continuity and disclosure of modern additions",
                ["To show that visitors should never approach art", "To prove that all missing areas must remain empty", "To explain why special light damages every pigment"],
                "La técnica permite lectura coherente a distancia y reconocimiento del añadido durante examen.",
                3,
                "blends at normal viewing distance but becomes distinguishable under close inspection",
                ["La distancia sirve para distinguir intervención, no para prohibir acercamiento.", "Es una alternativa a dejar vacío.", "La luz especial se usa para identificar, no se describe como daño universal."],
                3,
            ),
            q("70000000-0000-4000-8000-000000000185", 
                "READ_INFERENCE",
                "Why are detailed treatment records valuable even when a repair appears successful?",
                "Future researchers need to know what was changed and why.",
                ["They guarantee that materials will never age.", "They make scientific testing unnecessary.", "They prevent any future reconsideration."],
                "Los registros vuelven evaluables las decisiones y permiten reinterpretar con evidencia o tecnología futura.",
                7,
                "future researchers can evaluate not only the artwork but the decisions made around it",
                ["Todos los materiales siguen envejeciendo.", "Las pruebas forman parte del registro.", "La documentación facilita reconsideración."],
                2,
            ),
            q("70000000-0000-4000-8000-000000000186", 
                "READ_NEGATIVE_DETAIL",
                "All of the following are mentioned as restoration considerations EXCEPT",
                "increasing the artwork’s auction price",
                ["whether an intervention can be removed", "the cultural meaning of older repairs", "the distinction between evidence and speculation"],
                "El valor de subasta no aparece como criterio; los otros tres se desarrollan en distintos párrafos.",
                6,
                "distinguish evidence from speculation",
                ["La reversibilidad es un objetivo ético.", "Las reparaciones antiguas pueden tener importancia cultural.", "Los modelos digitales deben declarar incertidumbre."],
                2,
            ),
            q("70000000-0000-4000-8000-000000000187", 
                "READ_REFERENCE",
                "The word “it” in paragraph 4, in “the act of removing it,” refers to",
                "a supposedly removable coating",
                ["the original artist", "a digital screen", "the viewing distance"],
                "El pronombre retoma el material de recubrimiento cuya eliminación futura puede estresar la superficie.",
                4,
                "Even a removable coating may change how an old surface ages, and the act of removing it",
                ["No se elimina al artista.", "La reconstrucción digital aparece después.", "La distancia pertenece al retoque del párrafo anterior."],
            ),
            q("70000000-0000-4000-8000-000000000188", 
                "READ_PARAPHRASE",
                "Which statement best expresses the point about old restorations in paragraph 5?",
                "A historically inaccurate addition may itself become part of an artwork’s meaningful history.",
                ["Every older repair must be preserved unchanged.", "Technical accuracy has no importance in conservation.", "Viewers never become familiar with altered works."],
                "El texto presenta un conflicto entre revelar material temprano y conservar la biografía posterior del objeto.",
                5,
                "technically inaccurate yet culturally important",
                ["La importancia se evalúa, no produce una regla absoluta.", "La exactitud es una consideración entre varias.", "La familiaridad generacional es la razón de importancia."],
                3,
            ),
            q("70000000-0000-4000-8000-000000000189", 
                "READ_TONE",
                "How does the author present reversibility?",
                "As a valuable ideal whose practical limits must be acknowledged",
                ["As an easy guarantee for every material", "As an outdated idea with no ethical value", "As a property found only in digital images"],
                "El cuarto párrafo valora remover reparaciones futuras pero explica que ninguna acción es perfectamente neutra.",
                4,
                "Perfect reversibility is rare",
                ["Los recubrimientos pueden alterar envejecimiento.", "Se denomina objetivo ético.", "La discusión se aplica a materiales físicos."],
                3,
            ),
            q("70000000-0000-4000-8000-000000000190", 
                "READ_ORGANIZATION",
                "How does the passage build its argument?",
                "It examines several restoration decisions and then draws a principle of transparent, documented intervention.",
                ["It gives a chronological biography of one painter.", "It lists solvents without discussing ethics.", "It begins by proving that all repairs are reversible."],
                "Cada problema concreto contribuye a la síntesis ética del último párrafo.",
                7,
                "Good restoration is therefore not measured by making intervention invisible at any cost.",
                ["No se sigue a un artista individual.", "Los solventes son un ejemplo dentro de decisiones éticas.", "La reversibilidad perfecta se considera rara."],
                3,
            ),
        ],
    },
    {
        id: "60000000-0000-4000-8000-000000000032",

        slug: "photographs-and-public-memory",
        title: "Photographs and Public Memory",
        topicEs: "Fotografía como evidencia y memoria",
        genre: "arts",
        cefr: "C1",
        difficulty: 3,
        length: "long",
        estimatedMinutes: 14,
        paragraphs: [
            "Photographs often appear to preserve a moment automatically: light from a scene reached a camera and left a trace. This physical connection gives photographs evidentiary force, but it does not make them complete or self-explanatory. A scene can also be carefully staged before exposure. A frame includes some people and excludes others, fixes one instant, and reflects where a photographer was able or permitted to stand.",
            "Captions guide interpretation. A date, location, and name can connect an image to other records, while an inaccurate caption can redirect meaning for decades. Names may be absent because an institution never asked or because a record was separated from the print. Captions also classify. Describing a group as residents, protesters, workers, or a crowd foregrounds different relationships. Archives increasingly preserve the history of caption changes rather than treating the latest wording as timeless.",
            "Survival is selective. Institutions preserved some photographs because they documented officials, major construction, or celebrated events. Family albums and commercial studios preserved other views, but humidity, displacement, and private decisions destroyed many collections. Digitization can widen access to surviving material without restoring what was never kept. The visual record may therefore be abundant and still represent some communities or activities poorly.",
            "Reproduction changes significance. A small photograph in an album can become a large museum print, a newspaper illustration, or a rapidly shared digital image. Cropping may remove surrounding details; contrast adjustments may reveal or conceal features. Search systems can also favor images with detailed captions over poorly described ones. Repeated publication can turn one image into a symbol for an event even when it was not typical of what most participants experienced.",
            "People photographed are not merely subjects for later interpretation. Images may expose grief, medical conditions, sacred practices, or identities that create risk. Legal permission to publish does not settle every ethical question, especially when the photographer’s consent was obtained under unequal conditions or when descendants understand the image differently. Access decisions may need periodic review as circumstances change.",
            "Communities and archives have developed responses. Some projects invite people to identify relatives, correct descriptions, record oral histories, or set culturally appropriate access restrictions. These collaborations can add knowledge unavailable in institutional files. Respectful participation also requires time, compensation, and clarity about who controls the result. It can reveal disagreement within a community, so participation should not be represented as producing a single collective voice.",
            "Reading a historical photograph therefore involves movement between image and context. Researchers inspect visible details but also ask who made the image, how it circulated, why it survived, what information accompanied it, and who can speak about it now. Comparing related frames or records can test an interpretation. The photograph remains evidence, but its evidentiary value grows when uncertainty and the history of its use are made visible.",
        ],
        questions: [
            q("70000000-0000-4000-8000-000000000191", 
                "READ_MAIN_IDEA",
                "What argument does the passage make about historical photographs?",
                "They are valuable evidence whose meaning depends on framing, description, survival, circulation, and ethics.",
                ["Their physical link to light makes captions unnecessary.", "Every community is represented equally in archives.", "A photograph’s meaning remains fixed after exposure."],
                "El texto recorre condiciones que median la evidencia visual y concluye con una lectura contextual.",
                7,
                "its evidentiary value grows when uncertainty and the history of its use are made visible",
                ["Los pies de foto orientan y pueden distorsionar.", "La supervivencia es selectiva.", "Reproducción y nuevas descripciones cambian interpretación."],
                3,
            ),
            q("70000000-0000-4000-8000-000000000192", 
                "READ_DETAIL",
                "Why do some archives preserve earlier versions of captions?",
                "Caption changes are part of the photograph’s interpretive history.",
                ["Earlier captions are always more accurate.", "Images cannot be stored without several captions.", "The date of a photograph never matters."],
                "El segundo párrafo propone conservar la evolución descriptiva en vez de hacer pasar el texto actual como eterno.",
                2,
                "preserve the history of caption changes",
                ["Una versión anterior también puede ser inexacta.", "La razón es histórica, no una necesidad técnica.", "La fecha puede conectar con otros registros."],
            ),
            q("70000000-0000-4000-8000-000000000193", 
                "READ_VOCAB_CONTEXT",
                "The word “foregrounds” in paragraph 2 is closest in meaning to",
                "emphasizes",
                ["erases permanently", "photographs secretly", "dates precisely"],
                "Elegir una categoría dirige la atención hacia determinadas relaciones del grupo.",
                2,
                "foregrounds different relationships",
                ["La clasificación cambia enfoque, no borra necesariamente.", "El verbo describe lenguaje de la leyenda.", "La fecha es otra información posible."],
            ),
            q("70000000-0000-4000-8000-000000000194", 
                "READ_RHETORICAL_PURPOSE",
                "Why does the author compare an album photograph with a museum print and digital image?",
                "To show that scale, setting, and circulation can alter how an image functions",
                ["To prove that albums contain no historical evidence", "To show that digital copies always include more context", "To identify three cameras used at the same event"],
                "El ejemplo introduce transformaciones por reproducción, recorte y publicación reiterada.",
                4,
                "Reproduction changes significance.",
                ["El álbum conserva una forma de contexto.", "El recorte digital puede eliminar detalles.", "Se comparan usos y formatos, no cámaras."],
                3,
            ),
            q("70000000-0000-4000-8000-000000000195", 
                "READ_INFERENCE",
                "Why can a visually rich archive still give a distorted impression?",
                "The processes that preserved photographs favored certain people, events, and institutions.",
                ["Every surviving photograph is false.", "Humidity improves all private collections.", "Official events were never photographed."],
                "La abundancia total no corrige selecciones sistemáticas sobre qué se produjo y sobrevivió.",
                3,
                "abundant and still represent some communities or activities poorly",
                ["La crítica es a representatividad, no autenticidad universal.", "La humedad destruyó colecciones.", "Los eventos oficiales fueron una prioridad de preservación."],
                3,
            ),
            q("70000000-0000-4000-8000-000000000196", 
                "READ_NEGATIVE_DETAIL",
                "All of the following are mentioned as possible effects of reproducing a photograph EXCEPT",
                "restoring every lost collection",
                ["changing its scale", "cropping surrounding details", "turning it into a symbol"],
                "La reproducción no recupera archivos desaparecidos; los otros efectos aparecen en el cuarto párrafo.",
                4,
                "Repeated publication can turn one image into a symbol",
                ["Una foto pequeña puede ampliarse.", "El recorte elimina contexto.", "La repetición puede volverla representativa simbólicamente."],
            ),
            q("70000000-0000-4000-8000-000000000197", 
                "READ_REFERENCE",
                "The phrase “These collaborations” in paragraph 6 refers to",
                "projects in which archives work with communities to add knowledge or guide access",
                ["contrast adjustments made automatically", "private decisions that destroyed albums", "legal rules that forbid all publication"],
                "El demostrativo resume identificación, corrección, historia oral y restricciones construidas con participación comunitaria.",
                6,
                "These collaborations can add knowledge",
                ["El ajuste visual pertenece al párrafo anterior.", "La pérdida de colecciones no es colaboración.", "Se habla de decisiones éticas, no de prohibición universal."],
            ),
            q("70000000-0000-4000-8000-000000000198", 
                "READ_PARAPHRASE",
                "Which statement best expresses the ethical point in paragraph 5?",
                "Having legal permission does not remove responsibilities toward photographed people and their communities.",
                ["Any legally published image is ethically harmless.", "Only photographers can be affected by an image.", "Descendants never have relevant knowledge."],
                "El párrafo distingue autorización legal de consentimiento, riesgo, desigualdad y comprensión posterior.",
                5,
                "Legal permission to publish does not settle every ethical question",
                ["La legalidad no agota la ética.", "Las personas retratadas pueden sufrir exposición.", "Los descendientes pueden interpretar de otra manera."],
                3,
            ),
            q("70000000-0000-4000-8000-000000000199", 
                "READ_TONE",
                "How does the author view community participation in archival description?",
                "As valuable but not guaranteed to produce one uncontested interpretation",
                ["As unnecessary because institutions know everything", "As a method that always creates complete agreement", "As useful only for changing image contrast"],
                "Se reconoce conocimiento añadido y, al mismo tiempo, desacuerdo interno.",
                6,
                "should not be represented as producing a single collective voice",
                ["Los archivos pueden carecer de nombres e historias.", "El desacuerdo puede permanecer.", "La participación se centra en contexto y acceso."],
                3,
            ),
            q("70000000-0000-4000-8000-000000000200", 
                "READ_ORGANIZATION",
                "What is the function of the final paragraph?",
                "It synthesizes the earlier cautions into a method for reading photographs contextually.",
                ["It rejects photographs as evidence.", "It introduces an unrelated history of painting.", "It states that visible details should be ignored."],
                "El cierre reúne autoría, circulación, supervivencia, descripción y voces presentes en una práctica de investigación.",
                7,
                "movement between image and context",
                ["La fotografía conserva valor probatorio.", "El tema sigue siendo archivo fotográfico.", "Los detalles visibles son una parte de la lectura."],
                3,
            ),
        ],
    },
];
