import { q, type ReadingPassageSeed } from "../readingBankTypes";

export const HISTORY_PASSAGES: readonly ReadingPassageSeed[] = [
    {
        slug: "roman-concrete",
        title: "Concrete That Heals",
        topicEs: "Materiales de construcción romanos",
        genre: "history",
        cefr: "B1",
        difficulty: 1,
        length: "short",
        estimatedMinutes: 5,
        paragraphs: [
            "Roman builders made concrete by mixing lime, water, volcanic ash, and pieces of rock. In harbors, they sometimes placed the mixture directly into wooden forms under seawater. The resulting structures could remain strong for centuries, even while modern concrete exposed to salt water often cracks and weakens.",
            "Microscopic studies have revealed small lime-rich fragments throughout some Roman concrete. These fragments were once dismissed as evidence of careless mixing. Researchers now propose that they can contribute to self-repair. When a crack reaches a fragment and water enters, calcium-rich material dissolves and later forms new minerals inside the opening.",
            "This process cannot repair unlimited damage, and Roman recipes varied widely. Nevertheless, the finding changes how historians interpret apparently imperfect material. What looked like a defect may have resulted from a hot-mixing method that gave the concrete useful long-term behavior.",
        ],
        questions: [
            q(
                "READ_MAIN_IDEA",
                "What discovery about Roman concrete is emphasized in the passage?",
                "Lime-rich fragments once considered defects may help seal cracks.",
                ["All Roman concrete was poured in dry desert conditions.", "Modern salt water cannot damage concrete.", "Roman builders removed every mineral from their mixtures."],
                "El núcleo del texto es la reinterpretación de fragmentos de cal como posibles agentes de autorreparación.",
                2,
                "they can contribute to self-repair",
                ["El texto menciona colocación bajo agua marina.", "Se afirma que el concreto moderno puede agrietarse con sal.", "Los minerales se forman dentro de las grietas."],
            ),
            q(
                "READ_DETAIL",
                "What happens after water reaches a lime-rich fragment?",
                "Calcium-rich material dissolves and forms minerals in the crack.",
                ["The entire structure becomes liquid.", "Volcanic ash is removed from the harbor.", "Wooden forms grow around the crack."],
                "El segundo párrafo describe una secuencia de disolución y posterior precipitación mineral.",
                2,
                "calcium-rich material dissolves and later forms new minerals",
                ["El cambio es local y no licua la estructura.", "La ceniza forma parte de la mezcla y no se extrae.", "Los moldes se usaron durante construcción, no crecen."],
            ),
            q(
                "READ_VOCAB_CONTEXT",
                "The word “dismissed” in paragraph 2 is closest in meaning to",
                "rejected as unimportant",
                ["carefully measured", "placed underwater", "copied exactly"],
                "Antes se consideraban señal de mezcla descuidada y no una característica funcional digna de atención.",
                2,
                "were once dismissed as evidence of careless mixing",
                ["La medición microscópica pertenece a estudios recientes.", "La colocación bajo agua describe construcción portuaria.", "No se habla de copiar los fragmentos."],
            ),
            q(
                "READ_INFERENCE",
                "Why has the interpretation of the lime fragments changed?",
                "New microscopic evidence suggests a useful mechanism that was previously overlooked.",
                ["Historians discovered that Romans never used lime.", "Every modern concrete recipe now copies a Roman one.", "The fragments have disappeared from old structures."],
                "La observación de interacción entre agua, calcio y grietas ofrece una función que antes no se reconocía.",
                2,
                "Researchers now propose that they can contribute to self-repair.",
                ["La cal era un ingrediente explícito.", "No se afirma adopción universal moderna.", "Los fragmentos siguen siendo objeto de estudio."],
                2,
            ),
            q(
                "READ_TONE",
                "How does the author qualify the self-repair explanation?",
                "It is promising but limited and not identical across all Roman concrete.",
                ["It proves that Roman structures can never be damaged.", "It applies only to modern concrete.", "It is described as a deliberate historical fraud."],
                "El cierre reconoce límites del daño reparable y variación de recetas antes de señalar la importancia del hallazgo.",
                3,
                "cannot repair unlimited damage, and Roman recipes varied widely",
                ["Se niega explícitamente reparación ilimitada.", "El fenómeno se estudia en concreto romano.", "No se atribuye engaño a los constructores."],
                2,
            ),
        ],
    },
    {
        slug: "relay-posts",
        title: "Messages in Relays",
        topicEs: "Redes postales premodernas",
        genre: "history",
        cefr: "B1",
        difficulty: 1,
        length: "short",
        estimatedMinutes: 5,
        paragraphs: [
            "Long before railways or electronic communication, large states developed relay systems for official messages. Stations were placed along major routes, each within reach of the next. A courier arriving with a sealed document could exchange a tired horse for a rested one or hand the message to another rider.",
            "The relay increased speed because no single animal or person had to complete the entire journey without rest. It also required substantial organization. Stations needed food, animals, workers, and accurate information about authorized travelers. Rulers issued tokens or documents that allowed officials to use these resources.",
            "Although relay posts are often described as early postal systems, they were not always open to ordinary correspondence. Their main purpose was administrative: reporting conditions, transmitting orders, and moving officials. The network connected distant regions to a political center, but access to that speed was itself a form of power.",
        ],
        questions: [
            q(
                "READ_PRIMARY_PURPOSE",
                "What does the passage explain about relay networks?",
                "How they accelerated official communication through organized exchanges",
                ["How ordinary citizens received free mail every day", "Why horses could travel forever without rest", "How electronic messages replaced sealed documents"],
                "El texto describe estaciones, cambios de caballo o mensajero, recursos y uso político principalmente oficial.",
                2,
                "no single animal or person had to complete the entire journey without rest",
                ["El acceso ordinario no estaba siempre permitido.", "La ventaja consistía en reemplazar animales cansados.", "El período descrito precede la comunicación electrónica."],
            ),
            q(
                "READ_DETAIL",
                "What could an authorized courier do at a relay station?",
                "Exchange a tired horse for a rested one",
                ["Print a newspaper for local residents", "Build a new political capital", "Send an electronic copy of the message"],
                "El primer párrafo enumera el cambio de caballo y la entrega a otro jinete como operaciones del relevo.",
                1,
                "exchange a tired horse for a rested one",
                ["No se mencionan periódicos.", "Las estaciones conectaban con el centro; no creaban capitales.", "La transmisión era física."],
            ),
            q(
                "READ_REFERENCE",
                "The word “these” in paragraph 2 refers to",
                "station animals, food, workers, and related resources",
                ["distant political centers", "ordinary private letters", "future railway schedules"],
                "El demostrativo retoma los recursos que un viajero debía estar autorizado a utilizar.",
                2,
                "allowed officials to use these resources",
                ["Los centros son destinos de la red, no recursos de estación.", "La correspondencia común podía estar excluida.", "Los ferrocarriles son posteriores."],
            ),
            q(
                "READ_NEGATIVE_DETAIL",
                "Which activity was NOT identified as a main purpose of the relay network?",
                "Delivering personal letters for all residents",
                ["transmitting government orders", "reporting conditions in distant regions", "moving officials"],
                "El último párrafo limita el sistema a funciones administrativas y aclara que no siempre aceptaba correspondencia ordinaria.",
                3,
                "not always open to ordinary correspondence",
                ["Las órdenes forman parte de la lista administrativa.", "Los informes de condiciones se mencionan expresamente.", "El movimiento de funcionarios también era una función."],
            ),
            q(
                "READ_INFERENCE",
                "Why does the author call access to speed “a form of power”?",
                "Those authorized to use the network could act on distant information sooner than others.",
                ["Fast horses automatically became rulers.", "Every station controlled its own independent state.", "Ordinary correspondence traveled faster than official orders."],
                "El privilegio de la red permitía al gobierno transmitir información y decisiones con una rapidez no disponible para todos.",
                3,
                "access to that speed was itself a form of power",
                ["Los animales eran recursos, no autoridades.", "Las estaciones integraban una red política.", "El acceso oficial era el prioritario."],
                2,
            ),
        ],
    },
    {
        slug: "paper-travels-west",
        title: "A Material That Changed Writing",
        topicEs: "Difusión histórica del papel",
        genre: "history",
        cefr: "B2",
        difficulty: 2,
        length: "standard",
        estimatedMinutes: 7,
        paragraphs: [
            "Paper was developed in China from plant fibers and discarded textiles. Compared with bamboo strips, it was light; compared with silk, it was relatively inexpensive. Its manufacture required knowledge of how to separate fibers, suspend them in water, lift them on a screen, press the wet sheet, and dry it evenly.",
            "The technique spread gradually through movement and contact rather than in a single journey. Workshops appeared in Central Asia and later in cities governed by Islamic dynasties. Artisans adapted raw materials to local conditions, using linen and hemp rags where the plants common in Chinese production were unavailable. Knowledge traveled with craftspeople, merchants, prisoners, and written descriptions, although historians debate the importance of each route. Water-powered equipment eventually helped pulp fibers in some regions.",
            "Paper did not immediately replace every writing surface. Papyrus remained important in parts of the Mediterranean, while parchment was valued for durability and could be erased and reused. Institutions selected materials according to price, prestige, availability, and purpose. Administrative offices, merchants, scholars, and religious communities could make different choices.",
            "As paper production expanded, it supported more extensive record keeping and bookmaking. Yet the material alone did not create a literate society. Schools, scribes, trade networks, state demand, and later printing technologies shaped who could produce and read texts. The ability to recycle used fibers also affected local material supply. Paper lowered some production costs, but its historical effect depended on the institutions that used it.",
        ],
        questions: [
            q(
                "READ_MAIN_IDEA",
                "Which idea about the spread of paper is central to the passage?",
                "Paper spread through gradual adaptation and gained importance within supporting institutions.",
                ["Paper replaced all other writing materials as soon as it appeared.", "The same plant fibers were used in every region.", "Paper alone caused universal literacy."],
                "El texto combina transmisión técnica, adaptación de materias primas, convivencia de soportes y condiciones institucionales.",
                4,
                "its historical effect depended on the institutions that used it",
                ["Papiro y pergamino continuaron utilizándose.", "Los artesanos usaron materiales locales distintos.", "El cierre niega que el material por sí solo creara una sociedad alfabetizada."],
            ),
            q(
                "READ_DETAIL",
                "Why did some workshops use linen and hemp rags?",
                "Locally available materials differed from those used in China.",
                ["Rags eliminated the need to separate fibers.", "Parchment could not be erased.", "Water power was forbidden in China."],
                "El segundo párrafo explica que los artesanos adaptaron la materia prima a las condiciones locales.",
                2,
                "adapted raw materials to local conditions",
                ["La fabricación aún requería preparar fibras.", "El pergamino podía borrarse y reutilizarse.", "No se plantea una prohibición de energía hidráulica."],
            ),
            q(
                "READ_VOCAB_CONTEXT",
                "The word “suspend” in paragraph 1 is closest in meaning to",
                "disperse throughout a liquid",
                ["hang a finished book from a wall", "stop production permanently", "write symbols on dry paper"],
                "Durante la fabricación, las fibras se distribuyen en agua antes de levantarlas con una malla.",
                1,
                "suspend them in water",
                ["No se describe almacenamiento de libros.", "La secuencia continúa después de esta acción.", "La escritura sucede tras fabricar y secar la hoja."],
            ),
            q(
                "READ_RHETORICAL_PURPOSE",
                "Why does the author discuss papyrus and parchment?",
                "To show that adoption of paper was gradual and depended on particular uses",
                ["To prove that paper was less portable than bamboo", "To explain how printing was invented in China", "To claim that every institution chose the same material"],
                "La permanencia de otros soportes demuestra selección según costo, prestigio, disponibilidad y finalidad.",
                3,
                "did not immediately replace every writing surface",
                ["El primer párrafo caracteriza el papel como ligero.", "La impresión se menciona después como otra tecnología.", "Las instituciones podían tomar decisiones diferentes."],
                2,
            ),
            q(
                "READ_PARAPHRASE",
                "Which statement best expresses the conclusion?",
                "Cheaper writing material mattered most where social and economic systems enabled people to use it.",
                ["Low paper prices automatically taught everyone to read.", "Institutions had no influence on written communication.", "Printing made schools and trade networks unnecessary."],
                "La reducción de costos fue una condición útil, pero su efecto dependió de escuelas, demanda, productores y redes.",
                4,
                "Paper lowered some production costs, but its historical effect depended on the institutions that used it.",
                ["El pasaje rechaza una relación automática con alfabetización universal.", "Las instituciones son el condicionante central.", "Escuelas y comercio aparecen junto con impresión, no como sustituidos por ella."],
                3,
            ),
        ],
    },
    {
        slug: "stars-waves-and-islands",
        title: "Finding Islands without Instruments",
        topicEs: "Navegación tradicional del Pacífico",
        genre: "history",
        cefr: "B2",
        difficulty: 2,
        length: "standard",
        estimatedMinutes: 7,
        paragraphs: [
            "Navigators in the Pacific traveled between islands across vast stretches of open water without magnetic compasses or modern charts. Their knowledge did not depend on a single sign. Instead, they combined observations of stars, ocean swells, winds, birds, clouds, and the color of the sea.",
            "Stars provided directional reference. A navigator learned where particular stars rose and set and could imagine the canoe at the center of a changing star compass. When clouds hid the sky, long ocean swells could preserve information about distant winds. Several swells might cross at once, so recognizing a useful pattern required experience rather than simply following the largest wave.",
            "Signs of land became important near the end of a voyage. Some seabirds feed far offshore but return to islands at night, and particular cloud formations may gather above land. Reflected light can give the underside of a cloud a pale green tint over a lagoon. None of these signs alone guarantees land, but several consistent observations increase confidence.",
            "Knowledge was carried through teaching, memory, and repeated voyages. Training included names and sequences, but it also developed careful attention to subtle movement at sea. A learner might lie quietly in the canoe and feel how its motion changed as waves struck from different directions. Experienced navigators evaluated learners gradually over many journeys, allowing responsibility to grow as observations became more reliable. Navigation was therefore both an intellectual system and a bodily skill refined through practice.",
        ],
        questions: [
            q(
                "READ_PRIMARY_PURPOSE",
                "What does the author mainly explain about Pacific navigation?",
                "It combined multiple environmental cues with trained memory and bodily experience.",
                ["It relied entirely on the largest visible wave.", "It became possible only after magnetic compasses arrived.", "It used one bird species as a guaranteed sign of land."],
                "El pasaje recorre señales celestes, oceánicas y terrestres, además del aprendizaje práctico que las integra.",
                4,
                "both an intellectual system and a bodily skill",
                ["Varias olas podían cruzarse y la mayor no bastaba.", "Se destaca navegación sin compás magnético.", "Ninguna señal aislada garantizaba tierra."],
            ),
            q(
                "READ_DETAIL",
                "How could ocean swells assist when stars were hidden?",
                "They could retain information about winds beyond the cloudy area.",
                ["They made all clouds disappear.", "They always pointed directly toward the nearest island.", "They produced a magnetic field around the canoe."],
                "El segundo párrafo señala que oleajes largos conservan información sobre vientos distantes aun con cielo cubierto.",
                2,
                "long ocean swells could preserve information about distant winds",
                ["El oleaje no controla las nubes.", "Interpretar patrones no equivale a señalar siempre la isla más cercana.", "No se atribuye magnetismo al oleaje."],
            ),
            q(
                "READ_NEGATIVE_DETAIL",
                "Which of the following is NOT mentioned as a possible sign of nearby land?",
                "A sudden change in the writing on a chart",
                ["seabirds returning in the evening", "clouds gathering above land", "a green tint beneath a cloud"],
                "Las cartas modernas no forman parte del sistema descrito; las otras señales se enumeran en el tercer párrafo.",
                3,
                "Signs of land became important near the end of a voyage.",
                ["El regreso nocturno de ciertas aves puede indicar islas.", "Algunas nubes se forman sobre tierra.", "La luz reflejada de una laguna puede teñir una nube."],
            ),
            q(
                "READ_INFERENCE",
                "Why was experience necessary for interpreting swells?",
                "Several wave patterns could overlap and had to be distinguished.",
                ["Swells occurred only once in a navigator’s lifetime.", "A canoe could not move when waves were present.", "Wind had no relationship to wave direction."],
                "Con múltiples oleajes simultáneos, reconocer el patrón informativo exige comparación aprendida.",
                2,
                "Several swells might cross at once",
                ["Los viajes y la práctica eran repetidos.", "El movimiento de la canoa era una fuente de sensación.", "Los oleajes preservaban información sobre vientos."],
                2,
            ),
            q(
                "READ_PARAPHRASE",
                "What broader point does the final paragraph make about navigational knowledge?",
                "Navigational knowledge included memorized systems and sensitivity developed through physical practice.",
                ["Navigation was taught only through written examinations.", "Bodily sensation made star knowledge unnecessary.", "Learners avoided feeling the movement of the canoe."],
                "La conclusión une nombres y secuencias con percepción corporal afinada en viajes.",
                4,
                "both an intellectual system and a bodily skill refined through practice",
                ["La enseñanza se apoyaba en memoria y práctica, no solo escritura.", "Las fuentes de información se combinaban.", "Sentir el movimiento era un ejercicio formativo."],
                2,
            ),
        ],
    },
    {
        slug: "coffeehouses-and-news",
        title: "Rooms Full of News",
        topicEs: "Cafés y circulación de información",
        genre: "history",
        cefr: "B1",
        difficulty: 2,
        length: "short",
        estimatedMinutes: 5,
        paragraphs: [
            "Coffeehouses expanded in several European cities during the seventeenth and eighteenth centuries. Customers came for the drink, but many also came for information. Newspapers, pamphlets, shipping notices, and letters circulated through rooms where strangers could discuss trade, politics, science, and literature.",
            "Different establishments developed particular reputations. Merchants gathered near exchanges and docks, while writers or political groups favored other locations. Regular customers created networks that could spread news rapidly. The same speed also carried rumor, and governments sometimes watched coffeehouses or attempted to restrict discussion.",
            "These spaces were not open to everyone equally. Cost, location, social rules, and gender shaped who could participate. It is therefore misleading to describe every coffeehouse as a fully democratic public sphere. Their historical importance lies instead in how they connected print, conversation, business, and sociability in new combinations.",
        ],
        questions: [
            q(
                "READ_MAIN_IDEA",
                "Why were urban coffeehouses historically important according to the passage?",
                "They brought printed information and social networks together.",
                ["They guaranteed equal political power to every resident.", "They prevented rumors from spreading.", "They served only as quiet places to drink coffee."],
                "El texto destaca la combinación de impresos, conversación, negocios y redes, con límites de acceso.",
                3,
                "connected print, conversation, business, and sociability",
                ["La participación estaba condicionada y no era plenamente igual.", "La rapidez también difundía rumores.", "Las conversaciones y noticias eran funciones centrales."],
            ),
            q(
                "READ_DETAIL",
                "Where were merchants especially likely to gather?",
                "Near exchanges and docks",
                ["Inside remote farming villages", "Only in government offices", "At stations for relay horses"],
                "El segundo párrafo asocia reputaciones y clientelas con ubicaciones, incluidos intercambios y muelles.",
                2,
                "Merchants gathered near exchanges and docks",
                ["El contexto es urbano.", "Los cafés eran espacios distintos de oficinas oficiales.", "Las estaciones postales pertenecen a otra red."],
            ),
            q(
                "READ_VOCAB_CONTEXT",
                "The word “favored” in paragraph 2 is closest in meaning to",
                "preferred",
                ["closed", "financed", "measured"],
                "Escritores y grupos políticos tendían a elegir ciertos locales frente a otros.",
                2,
                "favored other locations",
                ["Los locales podían ser vigilados, pero «favored» no significa cerrar.", "No se afirma que financiaran el establecimiento.", "No expresa una operación de medición."],
            ),
            q(
                "READ_INFERENCE",
                "Why might governments have monitored coffeehouses?",
                "Rapid discussion networks could circulate politically sensitive ideas or rumors.",
                ["Coffee made printed pages impossible to read.", "Every customer worked for the government.", "Coffeehouses prevented merchants from trading."],
                "La velocidad de noticias y rumores, junto con debate político, explica el interés de vigilancia.",
                2,
                "governments sometimes watched coffeehouses or attempted to restrict discussion",
                ["Los materiales impresos circulaban ampliamente.", "Los clientes incluían múltiples grupos.", "Los comerciantes usaban estos espacios vinculados con negocios."],
                2,
            ),
            q(
                "READ_TONE",
                "How does the author treat the idea that coffeehouses were democratic spaces?",
                "With caution, because participation was socially limited",
                ["With complete acceptance", "As impossible because no conversation occurred", "As irrelevant to their history"],
                "El autor corrige una generalización: reconoce intercambio público pero enumera barreras de acceso.",
                3,
                "misleading to describe every coffeehouse as a fully democratic public sphere",
                ["La afirmación se matiza explícitamente.", "La conversación era una actividad principal.", "La inclusión limitada es parte del análisis histórico."],
                3,
            ),
        ],
    },
    {
        slug: "calendars-and-seasons",
        title: "Keeping a Calendar in Step",
        topicEs: "Historia de calendarios",
        genre: "history",
        cefr: "B2",
        difficulty: 2,
        length: "standard",
        estimatedMinutes: 7,
        paragraphs: [
            "A calendar divides time into named units, but the astronomical cycles used to define those units do not fit neatly together. A lunar month is about twenty-nine and a half days, while a solar year is roughly 365 and a quarter days. Twelve lunar months therefore end before the seasons complete a full cycle.",
            "Societies have addressed this mismatch in different ways. A purely lunar calendar allows months to move through the seasons. A solar calendar keeps dates aligned with the seasons but does not attempt to match each month to the moon. Lunisolar systems use lunar months and periodically insert an additional month so that seasonal festivals and agricultural markers remain in approximately the same part of the year.",
            "Even solar calendars need correction because a year is not an exact whole number of days. Leap-day rules add time according to a repeating pattern. If the rule adds slightly too much or too little, calendar dates drift slowly relative to equinoxes and solstices. Over centuries, a small annual error becomes noticeable.",
            "Calendar reform is never only an astronomical calculation. Changing a rule can alter religious observances, tax periods, contracts, and anniversaries. Printed schedules and official legal records may also need carefully coordinated conversion across an entire political region. People may strongly resist losing locally familiar dates even when the new system tracks the sun more accurately. A successful reform must therefore coordinate institutions as carefully as it coordinates days.",
        ],
        questions: [
            q(
                "READ_MAIN_IDEA",
                "What problem and response does the passage primarily discuss?",
                "Calendars use different correction systems because astronomical cycles do not divide evenly.",
                ["The moon has stopped changing its phases.", "All societies use the same definition of a month.", "Calendar reform affects astronomy but no social institution."],
                "El pasaje parte del desajuste, compara sistemas, explica días intercalares y termina con consecuencias sociales.",
                1,
                "astronomical cycles used to define those units do not fit neatly together",
                ["El ciclo lunar sigue siendo la base de varios calendarios.", "Se describen sistemas lunar, solar y lunisolar.", "La reforma afecta contratos, impuestos y celebraciones."],
            ),
            q(
                "READ_DETAIL",
                "How does a lunisolar calendar keep seasonal events in a similar part of the year?",
                "It occasionally inserts an extra month.",
                ["It shortens every day.", "It ignores lunar months completely.", "It removes all agricultural markers."],
                "El segundo párrafo señala la intercalación periódica de un mes para realinear meses lunares y estaciones.",
                2,
                "periodically insert an additional month",
                ["La duración del día no cambia.", "El sistema conserva meses lunares.", "Los marcadores agrícolas son una razón para mantener alineación."],
            ),
            q(
                "READ_VOCAB_CONTEXT",
                "The word “drift” in paragraph 3 is closest in meaning to",
                "move gradually out of alignment",
                ["become immediately identical", "stop being counted", "change names every day"],
                "Un error pequeño acumulado durante siglos desplaza lentamente las fechas respecto de eventos solares.",
                3,
                "dates drift slowly relative to equinoxes and solstices",
                ["El resultado es desalineación, no identidad.", "Las fechas continúan contándose.", "No se describe un cambio diario de nombres."],
            ),
            q(
                "READ_INFERENCE",
                "Why can a very small error in year length matter?",
                "Repeated annually, it accumulates into a visible seasonal shift.",
                ["It changes the length of the moon’s orbit immediately.", "It prevents anyone from using contracts.", "It adds a full month every morning."],
                "El tercer párrafo explica acumulación: una diferencia mínima anual se vuelve perceptible con el paso de siglos.",
                3,
                "Over centuries, a small annual error becomes noticeable.",
                ["El calendario no modifica la órbita lunar.", "Los contratos son afectados por reformas, no imposibilitados por todo error.", "La escala descrita es anual y secular."],
                2,
            ),
            q(
                "READ_RHETORICAL_PURPOSE",
                "Why does the author mention taxes, contracts, and anniversaries?",
                "To show that calendar changes have practical and social consequences",
                ["To list astronomical objects", "To prove that leap days are unnecessary", "To explain how lunar months are measured"],
                "Los ejemplos amplían la reforma más allá del cálculo astronómico hacia instituciones y hábitos.",
                4,
                "Changing a rule can alter religious observances, tax periods, contracts, and anniversaries.",
                ["Son actividades humanas, no cuerpos celestes.", "La necesidad de corrección solar ya fue explicada.", "La medición lunar se presenta al inicio, no mediante contratos."],
                2,
            ),
        ],
    },
    {
        slug: "archaeology-of-discarded-things",
        title: "What People Threw Away",
        topicEs: "Arqueología de residuos domésticos",
        genre: "history",
        cefr: "B2",
        difficulty: 3,
        length: "long",
        estimatedMinutes: 13,
        paragraphs: [
            "Archaeologists often learn about past households from objects their owners no longer wanted. Broken pottery, animal bones, ash, worn tools, and construction debris accumulate in pits or layers. Unlike valuable objects deliberately preserved, ordinary refuse can record repeated activities with little concern for how later observers will interpret it.",
            "A deposit is not a direct photograph of daily life. People sort, reuse, burn, move, and trade discarded material. A cracked vessel may be repaired before it is finally thrown away, and bones may be carried away by animals after disposal. Floods or later construction can mix deposits from different periods. Archaeologists must reconstruct the processes that formed a layer before treating its contents as evidence.",
            "Location provides one clue. Refuse beside a cooking area may differ from material dumped at the edge of a settlement. Tiny fish bones or plant seeds are easily missed during excavation, so soil is often passed through screens or floated in water. Light botanical remains rise to the surface, while heavier fragments sink. Recording the mesh size and sampled volume allows later researchers to evaluate what could have been recovered. These recovery methods can transform an apparently empty sample into evidence about diet and environment.",
            "Quantities also require interpretation. Many cattle bones in one deposit do not automatically mean that every resident ate beef frequently. The bones could come from specialized butchery, a feast, or a workshop processing hides. Researchers compare body parts, cut marks, burning, age of animals, and distribution across sites. Multiple patterns are stronger than a single count.",
            "Refuse can reveal inequality. Fine imported ceramics may cluster around certain houses, while repairs on ordinary vessels can indicate efforts to extend their use. Yet expensive objects do not map perfectly onto wealthy people. An heirloom can remain in a modest household, and a rich household may dispose of goods somewhere not excavated. Interpretation works with probabilities rather than simple labels.",
            "Modern assumptions create another risk. Categories such as useful and waste change across cultures. Material considered rubbish by one group may be fuel, fertilizer, building fill, or a resource for craft production in another. Even the place chosen for disposal may carry meanings that are not obvious to an excavator. Ethnographic and historical sources can suggest possibilities, but analogy must not replace evidence from the site itself.",
            "The archaeology of refuse is powerful precisely because it is necessarily incomplete. Gaps force researchers to combine context, recovery technique, measurement, comparison, and uncertainty. New laboratory methods can identify residues or microscopic wear, but they do not remove the need for contextual judgment. A trash pit cannot tell a household’s whole story, but it can preserve choices and routines rarely celebrated in monuments or written records.",
        ],
        questions: [
            q(
                "READ_MAIN_IDEA",
                "What central point does the passage make about archaeological refuse?",
                "Discarded material reveals ordinary life when its formation and context are carefully analyzed.",
                ["Trash deposits provide exact records of every household activity.", "Only rare and valuable objects can reveal patterns of inequality.", "Archaeologists generally avoid recovering or interpreting small biological remains."],
                "El texto combina el valor de los residuos con alteraciones, recuperación, comparación y límites interpretativos.",
                7,
                "combine context, recovery technique, measurement, comparison, and uncertainty",
                ["El segundo párrafo niega que sea una fotografía directa.", "Cerámica común e importada pueden aportar información social.", "Se usan cribado y flotación para recuperar restos pequeños."],
                3,
            ),
            q(
                "READ_DETAIL",
                "Why might a broken vessel not enter a trash deposit immediately?",
                "It may be repaired and used again first.",
                ["It always becomes an imported heirloom.", "Floodwater turns it into animal bone.", "Screens prevent pottery from being discarded."],
                "El segundo párrafo ofrece la reparación como etapa previa a la eliminación final.",
                2,
                "A cracked vessel may be repaired before it is finally thrown away",
                ["Un objeto reparado no se vuelve necesariamente importado.", "La inundación puede mezclar capas, no transformar materiales.", "Las cribas son herramientas de excavación posterior."],
            ),
            q(
                "READ_VOCAB_CONTEXT",
                "The word “cluster” in paragraph 5 is closest in meaning to",
                "be concentrated together",
                ["disappear completely", "be dated incorrectly", "float to the surface"],
                "Las cerámicas finas aparecen agrupadas alrededor de determinadas casas, señalando una distribución espacial.",
                5,
                "may cluster around certain houses",
                ["La presencia agrupada no implica desaparición.", "La frase habla de ubicación, no error cronológico.", "Flotar describe restos botánicos en otro procedimiento."],
            ),
            q(
                "READ_RHETORICAL_PURPOSE",
                "Why does the author mention animals carrying bones away?",
                "To illustrate how material can move after it is discarded",
                ["To prove that animals created all archaeological sites", "To show that bones cannot reveal diet", "To explain how pottery was manufactured"],
                "El ejemplo forma parte de los procesos que alteran un depósito y deben reconstruirse.",
                2,
                "bones may be carried away by animals after disposal",
                ["Los animales son un agente entre varios.", "Los huesos sí aportan evidencia cuando se analizan con contexto.", "La fabricación cerámica no se explica."],
                2,
            ),
            q(
                "READ_INFERENCE",
                "Why are recovery techniques important when comparing deposits?",
                "Different methods can change which small remains are visible and counted.",
                ["Every deposit contains exactly the same objects.", "Floating removes all evidence of plants.", "Large pottery fragments can be found only in water."],
                "Sin cribado o flotación, semillas y huesos diminutos pueden faltar del registro observado y sesgar comparaciones.",
                3,
                "can transform an apparently empty sample into evidence",
                ["Los depósitos varían por actividad y ubicación.", "La flotación recupera restos botánicos.", "La cerámica grande no depende exclusivamente de flotación."],
                3,
            ),
            q(
                "READ_NEGATIVE_DETAIL",
                "All of the following are suggested for interpreting animal bones EXCEPT",
                "the color of nearby modern buildings",
                ["cut marks", "which body parts are present", "the animals’ ages"],
                "El color de edificios modernos no figura entre las variables; las otras se enumeran en el cuarto párrafo.",
                4,
                "compare body parts, cut marks, burning, age of animals",
                ["Las partes ayudan a distinguir procesamiento y consumo.", "Las marcas de corte revelan actividad.", "La edad de los animales forma parte de la comparación."],
            ),
            q(
                "READ_REFERENCE",
                "The word “its” in paragraph 5, in the phrase “extend its use,” refers to",
                "an ordinary vessel",
                ["an imported house", "an excavated workshop", "a cattle bone"],
                "El posesivo retoma el objeto reparado —la vasija común— cuya vida útil se prolonga.",
                5,
                "repairs on ordinary vessels can indicate efforts to extend their use",
                ["«Imported» describe cerámica, no casas.", "El taller se menciona en relación con huesos.", "La reparación descrita corresponde a recipientes."],
            ),
            q(
                "READ_PARAPHRASE",
                "Which statement best expresses the caution in paragraph 5?",
                "Objects associated with wealth offer clues but cannot establish social status with certainty.",
                ["Imported ceramics are found only in households with few resources.", "Wealthy households rarely discard objects where archaeologists can find them.", "Every repaired vessel at a site belonged to the same family."],
                "El texto ofrece excepciones —herencias y áreas no excavadas— para evitar equivalencias automáticas.",
                5,
                "expensive objects do not map perfectly onto wealthy people",
                ["La concentración puede asociarse con ciertas casas, sin exclusividad inversa.", "Los ricos pueden desechar en lugares no excavados.", "Las reparaciones indican uso prolongado, no una familia única."],
                3,
            ),
            q(
                "READ_TONE",
                "How would the author’s approach to archaeological interpretation best be described?",
                "Evidence-based and cautious about simple conclusions",
                ["Certain that one object explains an entire site", "Dismissive of ordinary household activities", "Focused only on written records"],
                "A lo largo del texto se exigen patrones múltiples, contexto y reconocimiento explícito de incertidumbre.",
                7,
                "A trash pit cannot tell a household’s whole story",
                ["Se rechaza depender de un solo conteo.", "Las rutinas cotidianas son precisamente el interés.", "Los residuos complementan lo que monumentos y registros no celebran."],
                3,
            ),
            q(
                "READ_ORGANIZATION",
                "Which description best matches the organization of the passage?",
                "It introduces refuse evidence, then examines sources of bias and methods of interpretation.",
                ["It gives detailed instructions for repairing and reusing modern pottery.", "It follows one animal bone from a household to a museum.", "It argues that all discarded material has the same meaning across cultures."],
                "Tras introducir el valor documental, cada párrafo agrega formación, recuperación, cantidad, desigualdad y categorías culturales.",
                7,
                "The archaeology of refuse is powerful precisely because it is necessarily incomplete.",
                ["La reparación es un ejemplo histórico, no un manual.", "No se narra la trayectoria de un hueso individual.", "El sexto párrafo destaca variación cultural del concepto de residuo."],
                3,
            ),
        ],
    },
    {
        slug: "making-city-water-safe",
        title: "Making City Water Safer",
        topicEs: "Historia del saneamiento urbano",
        genre: "history",
        cefr: "C1",
        difficulty: 3,
        length: "long",
        estimatedMinutes: 14,
        paragraphs: [
            "Rapid urban growth in the nineteenth century placed pressure on water systems designed for smaller populations. Wells stood near leaking pits, waste entered rivers, and crowded districts often lacked reliable drainage. Epidemics were commonly explained through miasma, the belief that foul-smelling air caused disease. That theory was wrong about transmission, but concern about smell still motivated some street cleaning and sewer construction.",
            "Evidence linking contaminated water to disease accumulated unevenly. During an outbreak, investigators could compare where ill residents obtained water, but urban networks were complicated. Competing companies sometimes served neighboring houses through different pipes. This accidental variation allowed patterns to emerge that would have been difficult to create deliberately, although surviving household and company records were often incomplete or inconsistent across districts. Investigators therefore compared several kinds of evidence.",
            "Accepting waterborne transmission did not immediately produce safe supplies. Cities needed intake points away from sewage, pipes that prevented contamination, filtration, and treatment. Slow sand filters removed suspended material and supported biological layers that reduced microbes. Later, chemical disinfection provided another barrier. No single measure was sufficient when distribution pipes still leaked or waste remained unmanaged.",
            "Infrastructure required political and financial decisions. Large sewers and treatment works demanded taxes, long construction periods, and coordination across municipal boundaries. Debates concerned who would pay, which neighborhoods would be connected first, and whether services should be publicly or privately managed. Wealthier districts often received improvements first, while renters and informal settlements had less influence. Public health benefits were broad, but costs and disruptions were not distributed equally.",
            "Measurement made systems more accountable. Laboratories tested water, engineers tracked pressure, and health departments mapped disease. Standards converted observations into thresholds that suppliers were expected to meet. Publishing results could expose repeated failures and support demands for investment. Yet testing only occasional samples could miss short contamination events. Officials had to decide where, how often, and for which organisms to test.",
            "Sanitation also changed rivers downstream. Moving waste away from city streets could simply transfer pollution to another community. Fish deaths, odors, and contaminated irrigation water made those transfers increasingly visible. Treatment therefore expanded from protecting drinking-water intakes to reducing the environmental burden of discharged sewage. This shift required seeing the river not merely as a pipe carrying waste away but as an ecosystem and a shared resource.",
            "Modern systems inherit these layered solutions and inequalities. Filtration, disinfection, sewer separation, monitoring, and watershed protection work together. Operators must also retain training, spare parts, emergency plans, and public trust. Aging pipes, extreme rainfall, and unequal service can reopen risks that appear solved. The history of sanitation shows that technical knowledge matters, but durable safety depends on maintenance, public institutions, and attention to who remains outside the network.",
        ],
        questions: [
            q(
                "READ_MAIN_IDEA",
                "What is the passage’s central claim about urban sanitation?",
                "Safe water emerged from layered technical and institutional changes that require continued maintenance and equitable reach.",
                ["One scientific discovery immediately made every city’s water safe.", "Sewer construction mattered only because it improved smells.", "Modern systems no longer face contamination risks."],
                "El texto integra teoría, evidencia, barreras técnicas, inversión, medición, ambiente y desigualdad persistente.",
                7,
                "durable safety depends on maintenance, public institutions, and attention to who remains outside the network",
                ["La aceptación del agua contaminada no produjo seguridad inmediata.", "El olor motivó obras, pero la función sanitaria fue más amplia.", "Tuberías viejas y lluvias extremas pueden reabrir riesgos."],
                3,
            ),
            q(
                "READ_DETAIL",
                "What made neighboring houses useful for comparing disease patterns?",
                "They could receive water from different companies through separate pipes.",
                ["They all used the same private well.", "Their residents never moved.", "They were located outside every city boundary."],
                "La variación accidental de proveedores entre viviendas cercanas permitía comparar exposición con otras condiciones similares.",
                2,
                "Competing companies sometimes served neighboring houses through different pipes.",
                ["El punto era la diferencia de suministro.", "No se afirma inmovilidad de residentes.", "Eran viviendas dentro de redes urbanas."],
            ),
            q(
                "READ_VOCAB_CONTEXT",
                "The word “barrier” in paragraph 3 is closest in meaning to",
                "a layer of protection",
                ["a political border", "a source of smell", "a method of taxation"],
                "La desinfección se suma a filtración y tuberías como defensa contra contaminación microbiana.",
                3,
                "provided another barrier",
                ["El contexto es tratamiento de agua, no territorio.", "El olor pertenece a teorías anteriores.", "Los impuestos financian infraestructura pero no son barrera sanitaria."],
            ),
            q(
                "READ_RHETORICAL_PURPOSE",
                "Why does the author discuss miasma theory?",
                "To show that an incorrect explanation could still encourage some useful environmental action",
                ["To claim that smell is the true cause of every infection", "To prove that sewers were never constructed", "To replace evidence about contaminated water"],
                "Aunque equivocada en transmisión, la preocupación por aire fétido impulsó limpieza y alcantarillado.",
                1,
                "That theory was wrong about transmission, but concern about smell still motivated some street cleaning and sewer construction.",
                ["El texto declara incorrecta la teoría causal.", "La construcción aparece como consecuencia parcial.", "La evidencia sobre agua se desarrolla en el siguiente párrafo."],
                3,
            ),
            q(
                "READ_INFERENCE",
                "Why could improving only a water intake fail to prevent disease?",
                "Water could be contaminated later through leaking pipes or unmanaged waste.",
                ["Sand filters always added sewage.", "Chemical treatment prevented water from entering pipes.", "Every intake was already far from pollution."],
                "El enfoque de barreras múltiples reconoce que el agua limpia en origen puede contaminarse durante distribución.",
                3,
                "No single measure was sufficient when distribution pipes still leaked",
                ["Los filtros reducían material y microbios.", "La desinfección protegía y no bloqueaba distribución.", "Mover tomas lejos del drenaje era una mejora pendiente."],
                3,
            ),
            q(
                "READ_NEGATIVE_DETAIL",
                "All of the following are mentioned as parts of safer water systems EXCEPT",
                "eliminating every municipal boundary",
                ["filtration", "chemical disinfection", "pressure monitoring"],
                "Coordinar entre límites era necesario, pero no se propone eliminarlos; las otras medidas se enumeran.",
                7,
                "Filtration, disinfection, sewer separation, monitoring, and watershed protection work together.",
                ["La filtración aparece como barrera física y biológica.", "La desinfección química agrega protección.", "Los ingenieros seguían presión para rendición de cuentas."],
            ),
            q(
                "READ_REFERENCE",
                "The phrase “This shift” in paragraph 6 refers to",
                "expanding sanitation goals to reduce downstream environmental harm",
                ["moving wealthy residents into informal settlements", "replacing all laboratories with maps", "returning to miasma theory"],
                "El demostrativo retoma la ampliación desde proteger tomas urbanas hasta tratar las descargas y el río compartido.",
                6,
                "This shift required seeing the river",
                ["La desigualdad urbana se discute, pero no se describe ese traslado.", "Mapas y laboratorios son herramientas complementarias.", "El pasaje avanza hacia transmisión hídrica, no regresa a miasma."],
            ),
            q(
                "READ_PARAPHRASE",
                "Which statement best expresses the warning in paragraph 5?",
                "Limited sampling can cause a testing program to overlook brief or localized risks.",
                ["One clean sample is enough to establish permanent water safety.", "Accurate laboratories make formal water-quality standards and targets unnecessary.", "Only visibly dirty or foul-smelling water needs regular laboratory testing."],
                "La frecuencia, ubicación y objetivos del muestreo determinan si se detectan episodios cortos.",
                5,
                "testing only occasional samples could miss short contamination events",
                ["Una muestra aislada no cubre variación temporal.", "Los estándares orientan lo que los laboratorios deben comprobar.", "Microbios peligrosos no dependen necesariamente de olor."],
                3,
            ),
            q(
                "READ_TONE",
                "How does the author evaluate sanitation progress?",
                "As substantial but vulnerable to neglect and unequal service",
                ["As a complete failure with no health benefits", "As permanently finished in every modern city", "As unrelated to political choices"],
                "Se reconocen soluciones acumuladas y beneficios, junto con infraestructura envejecida y exclusión.",
                7,
                "can reopen risks that appear solved",
                ["Los beneficios de salud pública se describen como amplios.", "Los riesgos pueden regresar.", "Impuestos, límites y poder político afectan implementación."],
                3,
            ),
            q(
                "READ_ORGANIZATION",
                "How does paragraph 6 broaden the discussion?",
                "It extends sanitation from protecting city residents to considering downstream ecosystems and communities.",
                ["It narrows the passage to the smell of one street.", "It abandons water to discuss railway schedules.", "It argues that rivers should serve only as waste pipes."],
                "El párrafo incorpora externalidades ambientales y usuarios aguas abajo al objetivo sanitario.",
                6,
                "an ecosystem and a shared resource",
                ["La escala se amplía más allá de una calle.", "El tema sigue siendo agua y residuos.", "La metáfora de tubería se rechaza explícitamente."],
                3,
            ),
        ],
    },
];
