import { q, type ReadingPassageSeed } from "../readingBankTypes";

export const NATURAL_SCIENCE_PASSAGES: readonly ReadingPassageSeed[] = [
    {
        id: "60000000-0000-4000-8000-000000000001",

        slug: "fog-water-redwoods",
        title: "Water from Fog",
        topicEs: "Ecología de bosques costeros",
        genre: "natural_science",
        cefr: "B1",
        difficulty: 1,
        length: "short",
        estimatedMinutes: 5,
        paragraphs: [
            "Along some cool coastlines, summer rain is rare even though thick fog arrives almost every night. Coastal redwoods and several neighboring plants have adapted to this unusual combination. Their leaves intercept tiny droplets suspended in the fog. Some of that water enters the leaves directly, while the rest gathers into larger drops that fall to the forest floor.",
            "This process, known as fog drip, benefits more than the trees that collect the water. Moisture reaching the soil can be absorbed by shallow roots, mosses, and small animals. Researchers have measured noticeably wetter soil beneath redwoods than in nearby open areas. The trees therefore act as structures that redistribute atmospheric water through the ecosystem.",
            "Fog does not replace rainfall entirely. A long period without either rain or fog can still stress the forest. Nevertheless, fog drip helps coastal plants survive the driest part of the year and may become increasingly important where seasonal rainfall becomes less predictable.",
        ],
        questions: [
            q("70000000-0000-4000-8000-000000000001", 
                "READ_MAIN_IDEA",
                "Which statement best summarizes the discussion of coastal fog?",
                "How coastal trees capture fog and redistribute its water",
                ["Why coastal rainfall has increased in recent years", "How redwood roots prevent all water loss", "Why fog is dangerous to small forest animals"],
                "El texto explica el mecanismo de captura de niebla y sus beneficios para distintas partes del ecosistema.",
                2,
                "The trees therefore act as structures that redistribute atmospheric water through the ecosystem.",
                ["El texto señala que la lluvia estival es escasa, no que haya aumentado.", "Las raíces aprovechan humedad, pero no evitan toda pérdida de agua.", "Los animales aparecen como beneficiarios de la humedad, no como víctimas de la niebla."],
            ),
            q("70000000-0000-4000-8000-000000000002", 
                "READ_DETAIL",
                "According to the passage, what happens to water that is not absorbed directly by the leaves?",
                "It forms larger drops that fall to the ground.",
                ["It immediately returns to the ocean.", "It remains permanently suspended in the air.", "It is stored inside the tree trunk."],
                "El primer párrafo distingue entre la absorción directa y el agua que se agrupa en gotas y cae.",
                1,
                "the rest gathers into larger drops that fall to the forest floor",
                ["No se describe un retorno inmediato al océano.", "Las gotas dejan de permanecer suspendidas cuando se agrupan.", "El tronco no se menciona como depósito de esa agua."],
            ),
            q("70000000-0000-4000-8000-000000000003", 
                "READ_REFERENCE",
                "The phrase “This process” in paragraph 2 refers to",
                "the collection and dripping of water from fog",
                ["the measurement of rainfall in open areas", "the growth of shallow roots beneath moss", "the arrival of summer storms on the coast"],
                "La expresión retoma la secuencia descrita justo antes: las hojas interceptan gotas y parte del agua cae al suelo.",
                2,
                "This process, known as fog drip",
                ["Las mediciones aparecen después y no anteceden al demostrativo.", "Las raíces absorben el resultado del proceso, pero no lo constituyen.", "El texto destaca precisamente la escasez de lluvia estival."],
            ),
            q("70000000-0000-4000-8000-000000000004", 
                "READ_INFERENCE",
                "What can be inferred about open areas near redwood forests?",
                "Their soil may receive less moisture from fog.",
                ["Their soil is always deeper than forest soil.", "They receive more summer rainfall than the forest.", "They contain no plants capable of using fog water."],
                "Si el suelo bajo los redwoods es notablemente más húmedo que el de áreas abiertas cercanas, estas reciben menos aporte por goteo de niebla.",
                2,
                "wetter soil beneath redwoods than in nearby open areas",
                ["La profundidad del suelo nunca se compara.", "Las áreas son cercanas y no se afirma que reciban lluvias distintas.", "La comparación no permite concluir que carezcan por completo de plantas adaptadas."],
                2,
            ),
            q("70000000-0000-4000-8000-000000000005", 
                "READ_VOCAB_CONTEXT",
                "The word “stress” in paragraph 3 is closest in meaning to",
                "weaken",
                ["measure", "surround", "cool"],
                "En este contexto, la falta prolongada de agua puede debilitar al bosque.",
                3,
                "can still stress the forest",
                ["Medir es una acción de los investigadores, no el efecto de la sequía.", "Rodear no expresa daño fisiológico.", "Enfriar no corresponde al efecto de carecer de lluvia y niebla."],
            ),
        ],
    },
    {
        id: "60000000-0000-4000-8000-000000000002",

        slug: "nurse-logs",
        title: "A Fallen Tree’s Second Life",
        topicEs: "Regeneración forestal",
        genre: "natural_science",
        cefr: "B1",
        difficulty: 1,
        length: "short",
        estimatedMinutes: 5,
        paragraphs: [
            "When a large tree falls in a wet forest, decay begins almost immediately. Fungi and insects enter the wood, breaking its tissues into smaller components. The fallen trunk gradually becomes soft and porous, so it can hold considerable amounts of rainwater.",
            "Seeds that land on this damp surface sometimes grow more successfully than seeds on the crowded forest floor. The elevated trunk gives young plants access to light and keeps them above layers of wet leaves. As the wood decomposes, it also releases nutrients that the seedlings can use. For these reasons, ecologists often call a fallen trunk that supports new growth a nurse log.",
            "The relationship changes over time. Roots eventually extend through the decaying log and enter the soil below. Decades later, the original trunk may disappear completely, leaving a row of mature trees whose raised roots reveal where their temporary support once lay.",
        ],
        questions: [
            q("70000000-0000-4000-8000-000000000006", 
                "READ_PRIMARY_PURPOSE",
                "Why does the author discuss fungi and insects in paragraph 1?",
                "To explain how a fallen trunk becomes suitable for new growth",
                ["To argue that insects are the main cause of tree falls", "To compare two methods of measuring rainfall", "To show why young trees must avoid all fungi"],
                "Los organismos descomponedores vuelven la madera blanda, porosa y capaz de retener agua, preparando el soporte para plántulas.",
                1,
                "breaking its tissues into smaller components",
                ["El árbol ya está caído cuando llegan los insectos.", "No se comparan métodos de medición.", "El texto presenta la descomposición como beneficiosa para el establecimiento de plantas."],
            ),
            q("70000000-0000-4000-8000-000000000007", 
                "READ_DETAIL",
                "Which advantage of growing on a nurse log is mentioned in paragraph 2?",
                "Seedlings are lifted above layers of wet leaves.",
                ["Seedlings no longer need sunlight.", "Their roots immediately reach deep soil.", "They are protected from every forest insect."],
                "El segundo párrafo enumera acceso a luz, elevación sobre hojas húmedas y nutrientes liberados por la madera.",
                2,
                "keeps them above layers of wet leaves",
                ["El acceso a la luz es una ventaja, por lo que sí la necesitan.", "Las raíces alcanzan el suelo posteriormente, no de inmediato.", "No se promete protección total frente a insectos."],
            ),
            q("70000000-0000-4000-8000-000000000008", 
                "READ_VOCAB_CONTEXT",
                "The word “porous” in paragraph 1 is closest in meaning to",
                "full of small spaces that can hold liquid",
                ["covered by a hard waterproof layer", "perfectly smooth and dry", "separated from the forest floor"],
                "La consecuencia inmediata —retener mucha lluvia— aclara que la madera porosa contiene espacios donde entra el agua.",
                1,
                "soft and porous, so it can hold considerable amounts of rainwater",
                ["Una capa impermeable impediría retener agua dentro de la madera.", "La madera se describe como húmeda y en descomposición.", "La elevación pertenece a la posición del tronco, no al significado de «porous»."],
            ),
            q("70000000-0000-4000-8000-000000000009", 
                "READ_INFERENCE",
                "How might a person identify the former location of a nurse log many years later?",
                "By looking for a line of trees with elevated roots",
                ["By finding an undecayed trunk beneath every tree", "By measuring unusually low rainfall nearby", "By searching for leaves that receive no light"],
                "Aunque el tronco desaparezca, el texto indica que una fila de árboles y sus raíces levantadas conservan la huella de su ubicación.",
                3,
                "leaving a row of mature trees whose raised roots reveal where their temporary support once lay",
                ["El tronco puede haber desaparecido por completo.", "La lluvia no funciona como marcador histórico en el pasaje.", "La disponibilidad de luz explica el crecimiento, pero no localiza el tronco décadas después."],
                2,
            ),
            q("70000000-0000-4000-8000-000000000010", 
                "READ_ORGANIZATION",
                "How is the passage organized?",
                "It follows the transformation of a fallen tree and its effects over time.",
                ["It presents competing theories about why trees fall.", "It classifies forests according to annual rainfall.", "It gives instructions for moving seedlings onto logs."],
                "Los párrafos avanzan desde la caída y descomposición hasta el establecimiento de plántulas y la desaparición final del tronco.",
                3,
                "The relationship changes over time.",
                ["No aparecen teorías rivales sobre la caída.", "La lluvia es parte del proceso, pero no se clasifican bosques.", "El texto describe un fenómeno natural, no un procedimiento humano."],
            ),
        ],
    },
    {
        id: "60000000-0000-4000-8000-000000000003",

        slug: "living-light",
        title: "Living Light in the Ocean",
        topicEs: "Bioluminiscencia marina",
        genre: "natural_science",
        cefr: "B2",
        difficulty: 2,
        length: "standard",
        estimatedMinutes: 7,
        paragraphs: [
            "Sunlight fades rapidly below the ocean’s surface, yet darkness does not mean that the deep sea is without light. Many organisms produce their own through bioluminescence, a chemical reaction in which energy is released as visible light. Unlike a hot electric bulb, this reaction produces very little heat. It can therefore occur inside delicate tissues without damaging them.",
            "Bioluminescence serves different purposes. Some small animals flash when a predator approaches. The sudden light may startle the attacker or attract a larger animal that then attacks the original predator. Other species use rows of light-producing organs along the underside of their bodies. Seen from below, this glow resembles the faint light descending from the surface and makes the animal’s silhouette harder to detect.",
            "Light can also help organisms find food. Certain fish suspend a glowing structure near the mouth, where it resembles a small prey animal. Curious organisms approach the light and become prey themselves. In other cases, a narrow beam allows a fish to inspect its surroundings without illuminating its entire body.",
            "Because the deep ocean is difficult to observe directly, scientists once learned about these displays mainly from animals brought to the surface. Such specimens were often injured and behaved unnaturally. Modern low-light cameras and quiet remotely operated vehicles now record bioluminescence under the pressure and temperature conditions in which it evolved. These tools have revealed that living light is not an occasional curiosity but a widespread form of communication, concealment, and predation.",
        ],
        questions: [
            q("70000000-0000-4000-8000-000000000011", 
                "READ_MAIN_IDEA",
                "What is the main idea of the passage?",
                "Deep-sea organisms use self-produced light in several adaptive ways.",
                ["Most deep-sea light comes from damaged research equipment.", "Bioluminescence is mainly a source of heat for ocean animals.", "Only predatory fish are capable of producing light."],
                "El texto describe el mecanismo de luz biológica y una variedad de funciones: defensa, camuflaje, alimentación y comunicación.",
                4,
                "a widespread form of communication, concealment, and predation",
                ["Las herramientas registran la luz; no son su fuente principal.", "La reacción produce muy poco calor.", "Se mencionan animales pequeños y diversas especies, no solo peces depredadores."],
            ),
            q("70000000-0000-4000-8000-000000000012", 
                "READ_DETAIL",
                "Why can bioluminescence occur in delicate tissues?",
                "The reaction releases very little heat.",
                ["The tissues are exposed to strong sunlight.", "Ocean pressure prevents all chemical change.", "The organisms produce light only after surfacing."],
                "El primer párrafo vincula explícitamente la baja producción de calor con la ausencia de daño en tejidos delicados.",
                1,
                "this reaction produces very little heat",
                ["En el océano profundo la luz solar se desvanece.", "La presión no impide la reacción química.", "La bioluminiscencia sucede en el hábitat profundo, no solo en superficie."],
            ),
            q("70000000-0000-4000-8000-000000000013", 
                "READ_RHETORICAL_PURPOSE",
                "Why does the author describe light-producing organs on the underside of an animal?",
                "To illustrate how bioluminescence can provide camouflage",
                ["To show that all deep-sea animals swim upside down", "To explain how sunlight damages internal organs", "To identify the hottest part of an animal’s body"],
                "La luz inferior imita la iluminación que llega desde arriba y borra la silueta vista desde abajo.",
                2,
                "makes the animal’s silhouette harder to detect",
                ["La ubicación inferior no implica que el animal nade invertido.", "La función descrita es ocultar, no evitar daño solar.", "La reacción genera poco calor y no se localiza una región caliente."],
            ),
            q("70000000-0000-4000-8000-000000000014", 
                "READ_INFERENCE",
                "The passage suggests that an animal flashing near a predator may benefit even if the flash does not frighten the predator because",
                "the flash may draw a larger attacker to the scene",
                ["the flash permanently removes the predator’s vision", "the animal can use the light as food", "sunlight will immediately return to the deep water"],
                "El texto ofrece dos mecanismos defensivos: sobresaltar o atraer a un animal mayor que ataque al depredador inicial.",
                2,
                "attract a larger animal that then attacks the original predator",
                ["No se afirma que la pérdida de visión sea permanente.", "La luz atrae alimento en otros casos, pero no se consume como alimento.", "La presencia de luz solar no depende del destello."],
                2,
            ),
            q("70000000-0000-4000-8000-000000000015", 
                "READ_REFERENCE",
                "The phrase “Such specimens” in paragraph 4 refers to",
                "deep-sea animals brought to the surface",
                ["modern low-light cameras", "quiet remotely operated vehicles", "chemical reactions inside tissues"],
                "El grupo nominal retoma directamente a los animales que los científicos llevaban a la superficie para estudiarlos.",
                4,
                "animals brought to the surface. Such specimens",
                ["Las cámaras aparecen después como una mejora metodológica.", "Los vehículos son herramientas modernas, no especímenes.", "Las reacciones se estudian, pero no son organismos lesionados."],
            ),
        ],
    },
    {
        id: "60000000-0000-4000-8000-000000000004",

        slug: "volcanic-soil",
        title: "From Ash to Fertile Soil",
        topicEs: "Formación de suelos volcánicos",
        genre: "natural_science",
        cefr: "B2",
        difficulty: 2,
        length: "standard",
        estimatedMinutes: 7,
        paragraphs: [
            "A fresh layer of volcanic ash looks like an unlikely place for plants. It contains almost no organic matter, holds water poorly, and may shift in the wind. Yet landscapes covered by eruptions can eventually develop unusually productive soils. The change begins with physical and chemical weathering. Rain, temperature changes, and weak acids gradually break volcanic glass and minerals into finer particles.",
            "As those minerals weather, they release elements such as potassium, phosphorus, and iron. These nutrients alone do not create fertile soil, however. Pioneer organisms must first stabilize the surface. Lichens grow directly on exposed particles, while grasses and other hardy plants trap windblown dust. When these organisms die, decomposers convert their remains into organic matter.",
            "The mixture of weathered ash and organic material has a distinctive structure. Tiny mineral particles can bind with decomposed material and create spaces that retain both water and nutrients. In humid regions, this process may produce deep, dark soil. Farmers value such land, although cultivating it carelessly can destroy its advantages. Once protective vegetation is removed, the light particles are vulnerable to erosion.",
            "Not every volcanic deposit follows the same path. Climate, ash composition, slope, and the frequency of later eruptions all affect soil formation. A cool, wet deposit may develop differently from ash of the same age in a dry environment. Thus, the celebrated fertility of volcanic regions is not an immediate gift of an eruption but the result of a long interaction among rock, climate, and living organisms.",
        ],
        questions: [
            q("70000000-0000-4000-8000-000000000016", 
                "READ_PARAPHRASE",
                "Which sentence best expresses the meaning of the final sentence?",
                "Volcanic fertility develops gradually through geological, climatic, and biological processes.",
                ["Every eruption immediately creates soil suitable for farming.", "The age of volcanic ash is the only factor that determines fertility.", "Living organisms prevent minerals from entering volcanic soil."],
                "La conclusión rechaza la idea de fertilidad inmediata y la atribuye a una interacción prolongada de varios factores.",
                4,
                "the result of a long interaction among rock, climate, and living organisms",
                ["El texto dice explícitamente que no es un regalo inmediato.", "La edad no basta; también intervienen clima, composición y pendiente.", "Los organismos aportan y estabilizan materia, no bloquean los minerales."],
                2,
            ),
            q("70000000-0000-4000-8000-000000000017", 
                "READ_NEGATIVE_DETAIL",
                "According to paragraph 2, all of the following contribute to early soil development EXCEPT",
                "large amounts of organic matter already present in fresh ash",
                ["nutrients released by weathering", "lichens growing on exposed particles", "plants trapping dust carried by wind"],
                "La ceniza fresca casi no contiene materia orgánica; esta se acumula después mediante organismos pioneros y descomposición.",
                1,
                "contains almost no organic matter",
                ["La meteorización libera nutrientes según el segundo párrafo.", "Los líquenes estabilizan directamente la superficie expuesta.", "Las plantas resistentes atrapan polvo transportado por el viento."],
            ),
            q("70000000-0000-4000-8000-000000000018", 
                "READ_VOCAB_CONTEXT",
                "The word “hardy” in paragraph 2 is closest in meaning to",
                "able to survive difficult conditions",
                ["brightly colored", "recently discovered", "dependent on deep soil"],
                "Las plantas pioneras crecen sobre una superficie inestable y pobre, por lo que «hardy» significa resistentes.",
                2,
                "grasses and other hardy plants trap windblown dust",
                ["El color no participa en la función descrita.", "No se habla de cuándo fueron descubiertas.", "Estas plantas aparecen antes de que exista suelo profundo."],
            ),
            q("70000000-0000-4000-8000-000000000019", 
                "READ_DETAIL",
                "What makes weathered volcanic soil capable of retaining water?",
                "Spaces created when mineral particles bind with organic material",
                ["Repeated removal of protective vegetation", "The complete absence of decomposers", "Large pieces of volcanic glass remaining unchanged"],
                "El tercer párrafo explica que la unión de partículas finas y material descompuesto genera espacios que retienen agua y nutrientes.",
                3,
                "create spaces that retain both water and nutrients",
                ["Retirar la vegetación aumenta la erosión.", "Los descomponedores son necesarios para producir materia orgánica.", "La meteorización rompe el vidrio en partículas más finas."],
            ),
            q("70000000-0000-4000-8000-000000000020", 
                "READ_ORGANIZATION",
                "What is the relationship between paragraphs 1–3 and paragraph 4?",
                "The first three describe a general process, and the fourth explains why its outcome varies.",
                ["The first three reject farming, and the fourth recommends a single crop.", "The first three discuss dry climates, and the fourth discusses only humid ones.", "The first three present a failed theory that the fourth replaces completely."],
                "Después de explicar la formación y fertilidad, el último párrafo introduce variables que hacen que cada depósito evolucione de forma distinta.",
                4,
                "Not every volcanic deposit follows the same path.",
                ["El texto advierte sobre el manejo, pero no rechaza la agricultura ni propone cultivos.", "Los primeros párrafos no se limitan a climas secos.", "El último párrafo matiza el proceso, no lo descarta."],
                3,
            ),
        ],
    },
    {
        id: "60000000-0000-4000-8000-000000000005",

        slug: "seed-banks",
        title: "Seeds Held in Reserve",
        topicEs: "Conservación de diversidad vegetal",
        genre: "natural_science",
        cefr: "B2",
        difficulty: 2,
        length: "short",
        estimatedMinutes: 5,
        paragraphs: [
            "A seed bank stores seeds under carefully controlled conditions so that plant varieties remain available even if they disappear from farms or wild habitats. Before storage, workers dry the seeds to slow their metabolism. They then seal them in moisture-resistant containers and place them in cold rooms. For many species, low temperature and low moisture can extend survival for decades.",
            "Storage is not completely passive. Technicians periodically remove small samples and test whether the seeds still germinate. When germination rates fall, the bank grows a new generation of plants and collects fresh seeds. This regeneration step must be managed carefully: if only a few plants reproduce, some of the original genetic diversity may be lost.",
            "Seed banks are valuable, but they cannot preserve every plant. Some tropical species produce seeds that are damaged by drying or freezing. Other plants reproduce without conventional seeds. These cases require living collections, tissue cultures, or frozen cells. Conservationists therefore treat seed banks as one part of a broader strategy rather than a complete replacement for protecting ecosystems.",
        ],
        questions: [
            q("70000000-0000-4000-8000-000000000021", 
                "READ_DETAIL",
                "Why are seeds dried before they are placed in cold storage?",
                "To slow their metabolism",
                ["To make them germinate immediately", "To remove their genetic diversity", "To allow tropical insects to enter them"],
                "El primer párrafo da la finalidad directa del secado: reducir la actividad metabólica durante el almacenamiento.",
                1,
                "workers dry the seeds to slow their metabolism",
                ["La germinación se prueba después; no debe comenzar al guardar.", "El banco intenta conservar la diversidad, no eliminarla.", "Los recipientes protegen las semillas y no buscan introducir insectos."],
            ),
            q("70000000-0000-4000-8000-000000000022", 
                "READ_INFERENCE",
                "Why might a bank grow plants from many stored seeds during regeneration?",
                "To preserve as much of the original genetic variation as possible",
                ["To ensure that all plants become genetically identical", "To avoid collecting any new seeds", "To make the storage rooms warmer"],
                "El riesgo de reproducir pocas plantas es perder diversidad; usar muchas reduce ese efecto de muestreo.",
                2,
                "if only a few plants reproduce, some of the original genetic diversity may be lost",
                ["La identidad genética reduciría precisamente la diversidad.", "La regeneración tiene como objetivo producir semillas frescas.", "La temperatura de la cámara no depende de cuántas plantas se cultiven."],
                2,
            ),
            q("70000000-0000-4000-8000-000000000023", 
                "READ_VOCAB_CONTEXT",
                "The word “passive” in paragraph 2 is closest in meaning to",
                "requiring no active attention",
                ["located outdoors", "unable to remain cold", "limited to one species"],
                "La oración siguiente enumera pruebas y regeneración periódicas, mostrando que guardar semillas exige intervención continua.",
                2,
                "Storage is not completely passive.",
                ["La ubicación del almacenamiento no define «passive».", "El frío es una condición controlada, no una incapacidad.", "El banco conserva múltiples variedades y especies."],
            ),
            q("70000000-0000-4000-8000-000000000024", 
                "READ_NEGATIVE_DETAIL",
                "Which type of plant is NOT well suited to ordinary seed-bank storage?",
                "A species whose seeds are harmed by drying",
                ["A species whose dry seeds survive for decades", "A crop variety that has disappeared from farms", "A plant whose seeds can germinate after cold storage"],
                "El tercer párrafo identifica como excepción las semillas tropicales dañadas por secado o congelación.",
                3,
                "seeds that are damaged by drying or freezing",
                ["La supervivencia prolongada es justamente una condición favorable.", "Conservar variedades desaparecidas de granjas es una función del banco.", "La germinación posterior demuestra viabilidad en almacenamiento."],
            ),
            q("70000000-0000-4000-8000-000000000025", 
                "READ_MAIN_IDEA",
                "Which statement best summarizes the passage?",
                "Seed banks preserve many plants through active management but must be combined with other methods.",
                ["Seed banks can replace the protection of every natural ecosystem.", "Freezing works equally well for the seeds of all plants.", "Once stored, seeds never need to be tested or renewed."],
                "El texto combina el funcionamiento y mantenimiento de los bancos con sus límites y la necesidad de estrategias complementarias.",
                3,
                "one part of a broader strategy rather than a complete replacement",
                ["La conclusión niega que sean un reemplazo completo.", "Algunas semillas resultan dañadas por congelación.", "Las muestras se prueban y regeneran periódicamente."],
            ),
        ],
    },
    {
        id: "60000000-0000-4000-8000-000000000006",

        slug: "magnetic-migration",
        title: "A Map without Landmarks",
        topicEs: "Orientación magnética de aves",
        genre: "natural_science",
        cefr: "B2",
        difficulty: 3,
        length: "standard",
        estimatedMinutes: 8,
        paragraphs: [
            "Migrating birds use several sources of information to remain on course. The position of the sun and stars can provide compass directions, while coastlines, rivers, and mountains offer visible landmarks. These cues are not always available. Clouds may hide the sky, and a young bird crossing an unfamiliar region cannot rely on remembered scenery. Experiments suggest that many species also detect properties of Earth’s magnetic field.",
            "A magnetic compass and a magnetic map are not the same. A compass indicates direction, just as a handheld compass points north. A map provides information about location. Earth’s magnetic field varies gradually across the planet: its lines meet the surface at different angles, and its strength changes from place to place. If birds can sense both properties, they may estimate both where they are and which way to fly.",
            "Researchers test this possibility by temporarily placing birds in controlled magnetic fields. The birds remain physically in one location, but coils surrounding their enclosure reproduce the magnetic conditions of another region. Some birds then attempt to fly in the direction that would be appropriate from the simulated site rather than from their actual one. This response suggests that they interpreted the artificial field as location information.",
            "The sensory mechanism remains debated. Magnetic particles have been found in some animal tissues, but their exact role is uncertain. Another hypothesis proposes that light-sensitive molecules in the eye create chemical reactions influenced by magnetic direction. These explanations are not necessarily exclusive, and different species may combine them. What is clear is that migration is not guided by a single internal instrument; it depends on a flexible system that compares multiple cues.",
        ],
        questions: [
            q("70000000-0000-4000-8000-000000000026", 
                "READ_PRIMARY_PURPOSE",
                "What is the author’s primary purpose?",
                "To explain evidence that birds use Earth’s magnetic field for both direction and location",
                ["To prove that landmarks are useless during all migrations", "To describe how humans should build magnetic compasses", "To argue that one sensory mechanism has been conclusively identified"],
                "El pasaje distingue brújula y mapa magnéticos, describe experimentos y reconoce que el mecanismo sensorial sigue abierto.",
                3,
                "This response suggests that they interpreted the artificial field as location information.",
                ["Los puntos de referencia son una de varias señales útiles.", "La comparación con una brújula humana es explicativa, no una instrucción de construcción.", "El último párrafo afirma que el mecanismo continúa debatido."],
            ),
            q("70000000-0000-4000-8000-000000000027", 
                "READ_DETAIL",
                "Which property of Earth’s magnetic field varies from place to place?",
                "Its strength",
                ["The number of coastlines it crosses", "The visibility of the stars", "The age of nearby birds"],
                "El segundo párrafo menciona dos variaciones geográficas: el ángulo de las líneas y la intensidad del campo.",
                2,
                "its strength changes from place to place",
                ["Las costas son puntos de referencia visuales, no propiedades del campo.", "La visibilidad estelar depende de nubes y luz.", "La edad de las aves no forma parte del campo magnético."],
            ),
            q("70000000-0000-4000-8000-000000000028", 
                "READ_PARAPHRASE",
                "Which statement best expresses the distinction made in paragraph 2?",
                "Direction shows where to head; a map-like signal also shows current position.",
                ["A compass can identify every landmark, but a map cannot.", "Magnetic strength is identical everywhere, whereas direction changes.", "A map is useful only to birds that have never migrated."],
                "El párrafo diferencia información direccional de información posicional; detectar ambas permitiría decidir la ruta desde un lugar concreto.",
                2,
                "A compass indicates direction",
                ["Los puntos de referencia no son identificados por una brújula.", "El texto señala que la intensidad sí cambia geográficamente.", "No se limita el uso de un mapa a aves sin experiencia."],
                2,
            ),
            q("70000000-0000-4000-8000-000000000029", 
                "READ_RHETORICAL_PURPOSE",
                "Why does the author mention coils surrounding an enclosure?",
                "To explain how researchers alter magnetic information without moving the birds",
                ["To show how birds are trained to recognize mountains", "To provide evidence that birds cannot fly inside laboratories", "To describe a device that blocks every sensory cue"],
                "Las bobinas reproducen condiciones magnéticas de otro sitio mientras el ave permanece físicamente en el mismo lugar.",
                3,
                "reproduce the magnetic conditions of another region",
                ["El procedimiento no enseña montañas ni otros rasgos visuales.", "La dirección intentada por las aves es la variable observada, no su incapacidad de volar.", "Se modifica la señal magnética; no se afirma que se eliminen todas las demás."],
            ),
            q("70000000-0000-4000-8000-000000000030", 
                "READ_TONE",
                "How would the author’s attitude toward explanations of magnetic sensing best be described?",
                "Cautious and open to multiple mechanisms",
                ["Certain that magnetic particles explain every species", "Dismissive of experimental evidence", "Concerned that migration should be stopped"],
                "El autor presenta hipótesis, señala incertidumbre y permite que mecanismos diferentes funcionen juntos o varíen entre especies.",
                4,
                "These explanations are not necessarily exclusive",
                ["El papel exacto de las partículas se considera incierto.", "Los experimentos se usan como evidencia a favor de información posicional.", "No existe ninguna propuesta de detener la migración."],
                3,
            ),
        ],
    },
    {
        id: "60000000-0000-4000-8000-000000000007",

        slug: "coral-night-calendar",
        title: "A Reef’s Night Calendar",
        topicEs: "Reproducción sincronizada de corales",
        genre: "natural_science",
        cefr: "B2",
        difficulty: 3,
        length: "long",
        estimatedMinutes: 13,
        paragraphs: [
            "A coral reef may appear fixed and stone-like, but each coral colony is built by thousands of living animals called polyps. On a few nights each year, many colonies release bundles of eggs and sperm into the water at nearly the same time. The event can fill the sea with drifting pink or white particles. Because individual colonies cannot move to find mates, this synchronized spawning greatly increases the chance that reproductive cells from different colonies will meet.",
            "Synchronization occurs at several scales. Seasonal changes in water temperature help determine the month. The lunar cycle narrows the event to particular nights, often a set number of days after a full moon. Finally, the transition from daylight to darkness helps coordinate the hour. Different species may respond to slightly different combinations of these signals, so they can spawn on separate nights or at different times during the same evening.",
            "Releasing reproductive cells together offers advantages beyond finding mates. When billions of bundles enter the water at once, predators cannot consume all of them. This effect, called predator satiation, allows a proportion to survive even when fish and other animals gather to feed. Currents then carry fertilized eggs away from the parent reef. After a period drifting as larvae, survivors settle on suitable hard surfaces and begin new colonies.",
            "The timing is precise but not perfectly rigid. Local conditions can shift an event by a night or more. Heavy rain may lower salinity near shore, and unusually warm or cool water can alter development inside the colonies. Separate reefs in the same region therefore do not always spawn simultaneously. Scientists who want to observe an event combine long-term records with current measurements rather than relying on a calendar date alone.",
            "Climate change complicates these predictions. Corals use temperature as a developmental signal, but extreme heat can also cause bleaching, a breakdown of the relationship between polyps and the microscopic algae that supply much of their energy. A colony under severe stress may produce fewer reproductive cells or skip spawning. Recovery from bleaching can take months, so the reproductive effects may continue after water temperatures return to their usual range. If warming changes temperature patterns differently from lunar and daylight cycles, signals that once coincided may become less closely aligned.",
            "Researchers monitor spawning for practical as well as scientific reasons. During an event, they can collect egg-and-sperm bundles, fertilize them under controlled conditions, and raise young corals for restoration projects. Young colonies produced in this way can be placed on damaged reefs, although their survival is never guaranteed. Teams also compare which parent colonies produce larvae that tolerate warmer conditions. The work is demanding because the opportunity may last only a few hours. Understanding the reef’s multiple clocks helps teams prepare, but successful collection still depends on close observation of local colonies and conditions.",
        ],
        questions: [
            q("70000000-0000-4000-8000-000000000031", 
                "READ_MAIN_IDEA",
                "Which topic is developed throughout the passage?",
                "How multiple environmental signals coordinate coral spawning and why that timing matters",
                ["Why coral colonies migrate between reefs each year", "How predators determine the phases of the moon", "Why all coral species spawn at exactly the same moment"],
                "El texto explica las señales temporales, ventajas, variaciones, amenazas climáticas y utilidad científica del desove sincronizado.",
                6,
                "Understanding the reef’s multiple clocks helps teams prepare",
                ["Las colonias permanecen fijas; son las larvas las que se dispersan.", "La luna ayuda a sincronizar, pero los depredadores no determinan su ciclo.", "Las especies pueden desovar en noches u horas distintas."],
                2,
            ),
            q("70000000-0000-4000-8000-000000000032", 
                "READ_DETAIL",
                "Which signal helps narrow spawning to a particular hour?",
                "The change from daylight to darkness",
                ["The age of the reef’s hard surface", "The number of predators present", "The distance traveled by larvae"],
                "El segundo párrafo asigna escalas: temperatura para el mes, luna para noches y transición a oscuridad para la hora.",
                2,
                "the transition from daylight to darkness helps coordinate the hour",
                ["La superficie importa para el asentamiento posterior.", "La abundancia de depredadores no aparece como reloj.", "El viaje larvario ocurre después de la fecundación."],
            ),
            q("70000000-0000-4000-8000-000000000033", 
                "READ_VOCAB_CONTEXT",
                "The word “rigid” in paragraph 4 is closest in meaning to",
                "unable to vary",
                ["easy to observe", "limited to deep water", "controlled by predators"],
                "La oración contrasta precisión con cambios de una noche o más causados por condiciones locales.",
                4,
                "precise but not perfectly rigid",
                ["La facilidad de observación no es el contraste presentado.", "No se restringe el fenómeno a aguas profundas.", "Los depredadores afectan supervivencia, no la flexibilidad del calendario."],
            ),
            q("70000000-0000-4000-8000-000000000034", 
                "READ_INFERENCE",
                "Why can synchronized release improve fertilization for stationary colonies?",
                "It places reproductive cells from many colonies in the water together.",
                ["It allows adult colonies to swim toward one another.", "It prevents currents from moving any reproductive cells.", "It guarantees that every released egg survives."],
                "Las colonias no pueden buscar pareja; liberar células simultáneamente aumenta la probabilidad de encuentro entre colonias.",
                1,
                "increases the chance that reproductive cells from different colonies will meet",
                ["Los adultos no se desplazan.", "Las corrientes transportan huevos fecundados.", "La sincronía mejora probabilidades, pero no garantiza supervivencia total."],
                2,
            ),
            q("70000000-0000-4000-8000-000000000035", 
                "READ_REFERENCE",
                "The phrase “This effect” in paragraph 3 refers to",
                "predators being unable to consume all the reproductive bundles",
                ["larvae settling on hard surfaces", "corals responding to moonlight", "researchers collecting bundles"],
                "El demostrativo retoma la saturación producida cuando aparecen demasiados paquetes para que los depredadores los consuman todos.",
                3,
                "predators cannot consume all of them. This effect",
                ["El asentamiento se explica después.", "La respuesta lunar pertenece al párrafo anterior.", "La recolección científica aparece al final del pasaje."],
            ),
            q("70000000-0000-4000-8000-000000000036", 
                "READ_NEGATIVE_DETAIL",
                "All of the following are mentioned as factors that can shift or disrupt spawning EXCEPT",
                "the hardness of the surface beneath an adult colony",
                ["heavy rainfall near shore", "unusual water temperatures", "severe bleaching stress"],
                "La dureza de la superficie se relaciona con el asentamiento de larvas, no con el momento de desove de colonias adultas.",
                3,
                "suitable hard surfaces",
                ["La lluvia intensa puede reducir la salinidad y desplazar el evento.", "Temperaturas inusuales alteran el desarrollo.", "El estrés por blanqueamiento puede reducir o impedir el desove."],
                2,
            ),
            q("70000000-0000-4000-8000-000000000037", 
                "READ_RHETORICAL_PURPOSE",
                "Why does the author describe predator satiation?",
                "To identify a survival advantage of releasing many bundles simultaneously",
                ["To explain why corals produce no larvae", "To show that fish coordinate spawning dates", "To argue that predators should be removed from reefs"],
                "La saturación de depredadores explica por qué una liberación masiva permite que al menos una proporción escape y sobreviva.",
                3,
                "allows a proportion to survive",
                ["El proceso conduce a larvas tras la fecundación.", "Los peces responden al evento, pero no fijan su fecha.", "No se propone eliminar depredadores del ecosistema."],
                2,
            ),
            q("70000000-0000-4000-8000-000000000038", 
                "READ_PARAPHRASE",
                "Which statement best expresses the idea that climate change may cause signals to become “less closely aligned”?",
                "Temperature cues may shift while lunar and daylight cues retain a different schedule.",
                ["All environmental signals will permanently disappear.", "Corals will begin using predators as their only clock.", "Moon phases will change in response to warmer oceans."],
                "El calentamiento puede modificar los patrones térmicos sin modificar de la misma manera los ciclos lunar y diario.",
                5,
                "warming changes temperature patterns differently from lunar and daylight cycles",
                ["El texto habla de desajuste, no de desaparición total.", "Los depredadores no se presentan como señal temporal.", "El calentamiento no altera las fases lunares según el pasaje."],
                3,
            ),
            q("70000000-0000-4000-8000-000000000039", 
                "READ_TONE",
                "The author’s discussion of scientific prediction is best described as",
                "measured, emphasizing both useful patterns and local uncertainty",
                ["dismissive, claiming that records have no value", "certain, stating that calendars always predict the exact night", "alarmist, arguing that restoration work is impossible"],
                "Se reconoce que los registros y señales ayudan, pero se insiste en medir condiciones y observar colonias locales.",
                4,
                "combine long-term records with current measurements rather than relying on a calendar date alone",
                ["Los registros se combinan con datos actuales; no se descartan.", "El evento puede desplazarse una noche o más.", "La restauración es exigente, no imposible."],
                3,
            ),
            q("70000000-0000-4000-8000-000000000040", 
                "READ_ORGANIZATION",
                "How does the final paragraph contribute to the passage?",
                "It connects knowledge of spawning timing to coral restoration work.",
                ["It introduces the first evidence that corals are living animals.", "It replaces environmental signals with a fixed calendar.", "It explains why larvae can never be raised under controlled conditions."],
                "El cierre pasa de la explicación biológica a una aplicación práctica: recolectar y criar corales para restauración.",
                6,
                "raise young corals for restoration projects",
                ["La naturaleza viva de los pólipos se presenta al comienzo.", "El párrafo reafirma la necesidad de observación local, no de una fecha fija.", "Se describe explícitamente la cría controlada como posible."],
                2,
            ),
        ],
    },
    {
        id: "60000000-0000-4000-8000-000000000008",

        slug: "deep-ocean-carbon",
        title: "The Ocean’s Falling Snow",
        topicEs: "Ciclo de carbono oceánico",
        genre: "natural_science",
        cefr: "C1",
        difficulty: 3,
        length: "long",
        estimatedMinutes: 14,
        paragraphs: [
            "In the sunlit upper ocean, microscopic algae use carbon dioxide during photosynthesis. This process converts dissolved carbon into organic material and forms the base of much marine food. Most of that material is consumed and recycled near the surface, but a small fraction begins to sink. Viewed in underwater lights, the descending mixture of dead cells, waste, mucus, and mineral fragments resembles a slow snowfall, so researchers call it marine snow.",
            "Individual particles are tiny and would sink very slowly. They often collide and stick together, however, forming larger aggregates that descend more rapidly. These drifting animals also package fine material into dense waste pellets. Both mechanisms shorten the time during which currents and microbes can keep particles near the surface. The speed of descent matters because bacteria consume organic matter as it falls, returning much of its carbon to dissolved form.",
            "The amount that reaches deep water varies widely. Warm temperatures generally accelerate microbial activity, while the chemical composition of a particle affects how easily it can be broken down. Minerals such as calcium carbonate or windblown dust may add weight and may also shield some organic material from bacteria. Large, dense particles can therefore carry carbon farther than light, fragile ones.",
            "Animals complicate the vertical journey. Some species feed near the surface at night and swim hundreds of meters downward during the day to avoid predators. They carry carbon inside their bodies and release part of it through respiration and waste at depth. This active transport differs from passive sinking, yet it contributes to the same broad movement of carbon away from the atmosphere.",
            "Carbon that enters deep water is not necessarily stored forever. Ocean circulation can eventually bring it back toward the surface, where it may again exchange with the air. The interval can range from decades to centuries depending on depth and location. A much smaller quantity reaches seafloor sediments and becomes buried, where isolation may last far longer.",
            "Scientists want to know whether climate change will strengthen or weaken this biological carbon pump. Warming can increase stratification, reducing the supply of nutrients from deep water to algae at the surface. In some regions, lower nutrient availability may reduce production and sinking. At the same time, shifts in plankton species could change particle size, mineral content, and consumption by animals. These interacting effects make a single global prediction difficult.",
            "Researchers combine sediment traps, optical sensors, chemical measurements, and computer models to estimate the flow. Each method captures only part of the process: traps can disturb currents, cameras do not directly measure carbon, and models depend on assumptions. Agreement among independent methods therefore provides stronger evidence than any one instrument. Marine snow may look gentle, but understanding its descent is central to explaining how the ocean regulates atmospheric carbon over long periods.",
        ],
        questions: [
            q("70000000-0000-4000-8000-000000000041", 
                "READ_MAIN_IDEA",
                "Which statement best captures the central focus of the passage?",
                "The processes that move organic carbon from surface waters into the deep ocean",
                ["The use of artificial snow to cool the ocean surface", "Why photosynthesis occurs only on the seafloor", "A single instrument that measures all ocean carbon exactly"],
                "El pasaje sigue la formación, descenso, transformación, transporte animal, almacenamiento y medición del carbono oceánico.",
                7,
                "understanding its descent is central to explaining how the ocean regulates atmospheric carbon",
                ["La nieve marina es material orgánico natural, no nieve artificial.", "La fotosíntesis ocurre en la zona iluminada superior.", "El cierre destaca que cada método captura solo una parte."],
                2,
            ),
            q("70000000-0000-4000-8000-000000000042", 
                "READ_DETAIL",
                "What causes small particles to descend more rapidly?",
                "Their collision and combination into larger aggregates",
                ["Their complete conversion into dissolved carbon", "Their movement into warmer surface water", "Their exposure to brighter underwater lights"],
                "El segundo párrafo señala que las partículas que chocan y se adhieren forman agregados mayores con mayor velocidad de hundimiento.",
                2,
                "forming larger aggregates that descend more rapidly",
                ["El carbono disuelto ya no desciende como partícula.", "El agua cálida acelera microbios, no necesariamente el hundimiento.", "Las luces permiten observar, pero no impulsan las partículas."],
            ),
            q("70000000-0000-4000-8000-000000000043", 
                "READ_VOCAB_CONTEXT",
                "The word “shield” in paragraph 3 is closest in meaning to",
                "protect",
                ["measure", "dissolve", "heat"],
                "Los minerales pueden cubrir o asociarse con materia orgánica y reducir su exposición a las bacterias.",
                3,
                "shield some organic material from bacteria",
                ["Medir corresponde a las herramientas científicas del final.", "La protección reduce la descomposición, no la disolución.", "El calentamiento se discute como factor climático distinto."],
            ),
            q("70000000-0000-4000-8000-000000000044", 
                "READ_RHETORICAL_PURPOSE",
                "Why does the author mention zooplankton waste pellets?",
                "To give another mechanism that concentrates material into faster-sinking particles",
                ["To show that zooplankton perform photosynthesis", "To explain why all particles remain near the surface", "To identify the only source of carbon in seawater"],
                "Junto con la agregación por colisiones, los pellets densos empaquetan material fino y aceleran su descenso.",
                2,
                "These drifting animals also package fine material into dense waste pellets.",
                ["Los productores fotosintéticos mencionados son algas.", "El empaquetamiento acorta el tiempo cerca de la superficie.", "El carbono también procede de células muertas y otros materiales."],
                2,
            ),
            q("70000000-0000-4000-8000-000000000045", 
                "READ_PARAPHRASE",
                "Which sentence best expresses the idea in paragraph 4?",
                "Daily animal migrations transport carbon downward even when particles do not simply sink.",
                ["Animals prevent every form of carbon from reaching deep water.", "Predators carry carbon upward only during daylight.", "Passive sinking and animal movement are exactly the same process."],
                "Los animales ingieren carbono arriba y lo liberan abajo; es transporte activo distinto del hundimiento, pero con dirección general similar.",
                4,
                "This active transport differs from passive sinking",
                ["El transporte animal contribuye al movimiento hacia profundidad.", "Las especies bajan de día para evitar depredadores, no son estos quienes llevan carbono arriba.", "El texto diferencia explícitamente ambos mecanismos."],
                3,
            ),
            q("70000000-0000-4000-8000-000000000046", 
                "READ_INFERENCE",
                "Why is carbon reaching greater depths generally isolated from the atmosphere for longer?",
                "It takes ocean circulation more time to return it to surface waters.",
                ["Deep water contains no carbon-consuming organisms.", "The atmosphere stops exchanging gases at night.", "All deep carbon immediately becomes seafloor rock."],
                "El tiempo de almacenamiento aumenta con profundidad y ubicación porque el retorno mediante circulación puede tomar décadas o siglos.",
                5,
                "Ocean circulation can eventually bring it back toward the surface",
                ["El texto describe consumo bacteriano durante el descenso.", "El intercambio atmosférico no se limita por horario nocturno.", "Solo una fracción mucho menor queda enterrada en sedimentos."],
                3,
            ),
            q("70000000-0000-4000-8000-000000000047", 
                "READ_NEGATIVE_DETAIL",
                "All of the following are mentioned as affecting how far particles carry carbon EXCEPT",
                "the brightness of the moon",
                ["microbial activity", "particle composition", "the presence of minerals"],
                "La luz lunar no aparece como factor del hundimiento; sí se describen temperatura microbiana, composición y minerales.",
                3,
                "The amount that reaches deep water varies widely.",
                ["Los microbios consumen materia mientras cae.", "La facilidad de descomposición depende de la composición.", "Los minerales añaden peso y pueden proteger materia orgánica."],
                2,
            ),
            q("70000000-0000-4000-8000-000000000048", 
                "READ_REFERENCE",
                "The phrase “These interacting effects” in paragraph 6 refers to",
                "changes in nutrient supply and plankton-related particle properties",
                ["the use of lights and sediment traps", "the burial of all carbon on the seafloor", "the daily schedule of migrating predators"],
                "La frase resume la estratificación, disponibilidad de nutrientes y cambios en especies, tamaño, minerales y consumo.",
                6,
                "These interacting effects make a single global prediction difficult.",
                ["Las herramientas de medición se presentan en el párrafo siguiente.", "Solo una pequeña cantidad llega a enterrarse.", "La migración animal se explica antes, pero no es el conjunto inmediato retomado."],
                3,
            ),
            q("70000000-0000-4000-8000-000000000049", 
                "READ_TONE",
                "What is the author’s attitude toward predicting future changes in the biological carbon pump?",
                "Cautious because several mechanisms may change in different directions",
                ["Completely confident that warming will strengthen it everywhere", "Uninterested because the process has no atmospheric effect", "Certain that one camera can resolve every uncertainty"],
                "El autor presenta efectos contrapuestos y concluye que una predicción global única resulta difícil.",
                6,
                "make a single global prediction difficult",
                ["La producción puede reducirse en algunas regiones y no se ofrece una conclusión universal.", "El proceso se vincula directamente con carbono atmosférico.", "Las cámaras no miden carbono directamente."],
                3,
            ),
            q("70000000-0000-4000-8000-000000000050", 
                "READ_ORGANIZATION",
                "Why does the passage end by comparing several research methods?",
                "To show why estimates are strongest when independent approaches agree",
                ["To demonstrate that sediment traps never affect currents", "To argue that direct observation makes models unnecessary", "To change the subject from carbon to instrument sales"],
                "El último párrafo reconoce límites de cada técnica y justifica combinar evidencia independiente.",
                7,
                "Agreement among independent methods therefore provides stronger evidence",
                ["Las trampas pueden alterar corrientes.", "Los modelos siguen siendo una de las herramientas combinadas.", "La comparación metodológica apoya el estudio del mismo proceso de carbono."],
                3,
            ),
        ],
    },
];
