import { q, type ReadingPassageSeed } from "../readingBankTypes";

export const SOCIAL_SCIENCE_PASSAGES: readonly ReadingPassageSeed[] = [
    {
        id: "60000000-0000-4000-8000-000000000009",

        slug: "libraries-shared-infrastructure",
        title: "More Than Shelves",
        topicEs: "Funciones contemporáneas de bibliotecas públicas",
        genre: "social_science",
        cefr: "B1",
        difficulty: 1,
        length: "short",
        estimatedMinutes: 5,
        paragraphs: [
            "Public libraries were once defined mainly by the books they collected, but their role has expanded as information has moved online. Many now lend electronic materials and provide internet access, computers, and assistance with digital forms. For residents who lack reliable devices or connections at home, these services are basic infrastructure rather than optional conveniences.",
            "Libraries also offer a kind of public space that is increasingly uncommon. Visitors are generally allowed to remain without making a purchase. A student can work quietly, a job seeker can prepare an application, and a recently arrived resident can attend a language class. These activities differ, yet they share the same accessible setting.",
            "This broader mission creates challenges. Staff members need skills that range from preserving local records to teaching digital privacy. Buildings designed for silent reading must accommodate conversation, workshops, and group work without abandoning quiet areas. The modern library therefore balances continuity with adaptation: it protects access to recorded knowledge while changing how that access is delivered.",
        ],
        questions: [
            q("70000000-0000-4000-8000-000000000051", 
                "READ_MAIN_IDEA",
                "Which description best captures the modern public library?",
                "Public libraries preserve access to knowledge while expanding their services and spaces.",
                ["Public libraries have stopped lending books entirely.", "Digital services have made public buildings unnecessary.", "Libraries now require every visitor to buy something."],
                "El texto presenta una ampliación de funciones y concluye que la biblioteca combina continuidad con adaptación.",
                3,
                "balances continuity with adaptation",
                ["Los libros siguen formando parte de la misión.", "La falta de acceso doméstico vuelve importantes los espacios físicos.", "Permanecer sin comprar se presenta como una característica distintiva."],
            ),
            q("70000000-0000-4000-8000-000000000052", 
                "READ_DETAIL",
                "Why are library computers described as infrastructure for some residents?",
                "They may be the residents’ only reliable way to access online services.",
                ["They preserve every local record automatically.", "They eliminate the need for staff assistance.", "They are used only for entertainment."],
                "El primer párrafo vincula esos equipos con personas que no tienen dispositivos o conexión confiable en casa.",
                1,
                "lack reliable devices or connections at home",
                ["La preservación de registros requiere trabajo especializado.", "El texto menciona asistencia con formularios digitales.", "Se destacan solicitudes, estudio y servicios, no solo entretenimiento."],
            ),
            q("70000000-0000-4000-8000-000000000053", 
                "READ_RHETORICAL_PURPOSE",
                "Why does the author mention a student, a job seeker, and a recently arrived resident?",
                "To illustrate different uses of the same accessible public space",
                ["To rank visitors according to their reading ability", "To show that only three groups may enter libraries", "To argue that language classes should replace books"],
                "Los tres ejemplos concretan actividades distintas que comparten un espacio abierto y sin obligación de compra.",
                2,
                "These activities differ, yet they share the same accessible setting.",
                ["No se comparan niveles de lectura.", "Los ejemplos no constituyen una lista exclusiva.", "Las clases complementan, no sustituyen, el acceso al conocimiento."],
            ),
            q("70000000-0000-4000-8000-000000000054", 
                "READ_VOCAB_CONTEXT",
                "The word “accommodate” in paragraph 3 is closest in meaning to",
                "make room for",
                ["prevent", "measure", "record permanently"],
                "El edificio debe permitir conversaciones y talleres al mismo tiempo que conserva zonas silenciosas.",
                3,
                "must accommodate conversation, workshops, and group work",
                ["La biblioteca intenta permitir esas actividades, no impedirlas.", "No se trata de calcular su tamaño.", "Registrar información no expresa adaptar el espacio."],
            ),
            q("70000000-0000-4000-8000-000000000055", 
                "READ_INFERENCE",
                "What can be inferred about the skills required of modern library staff?",
                "They have become more varied as library services have expanded.",
                ["They are limited to arranging printed books.", "They no longer include preservation work.", "They are identical in every library building."],
                "El texto enumera desde preservación hasta privacidad digital, lo que implica un campo de competencias más amplio.",
                3,
                "skills that range from preserving local records to teaching digital privacy",
                ["La organización de libros no cubre la variedad descrita.", "La preservación se menciona explícitamente.", "Las necesidades pueden variar según servicios y comunidad."],
                2,
            ),
        ],
    },
    {
        id: "60000000-0000-4000-8000-000000000010",

        slug: "markets-and-city-streets",
        title: "Markets That Move",
        topicEs: "Mercados temporales y espacio urbano",
        genre: "social_science",
        cefr: "B1",
        difficulty: 1,
        length: "short",
        estimatedMinutes: 5,
        paragraphs: [
            "A street market may occupy a plaza for only a few hours, yet its temporary presence can shape the surrounding neighborhood. Vendors arrive early with tables, shade coverings, and portable displays. Customers alter their usual routes, and nearby shops may experience more foot traffic. When the market closes, the physical structures disappear, but social and economic connections formed there may continue.",
            "Temporary markets lower some barriers faced by small producers. Renting a permanent store requires long contracts and substantial capital, whereas a weekly stall can be tested with less risk. Vendors can observe which products attract buyers and adjust their offerings before making larger investments.",
            "The flexibility also creates tension. Residents may object to noise, blocked parking, or waste, while vendors need predictable rules and access to desirable locations. Successful market programs usually depend on negotiation among organizers, local government, businesses, and residents. The market is therefore not simply a collection of stalls; it is a recurring agreement about how public space will be shared.",
        ],
        questions: [
            q("70000000-0000-4000-8000-000000000056", 
                "READ_PRIMARY_PURPOSE",
                "What does the author seek to explain about temporary markets?",
                "To explain the opportunities and negotiations created by temporary street markets",
                ["To provide instructions for building a permanent shopping center", "To show that street markets leave no lasting effects", "To argue that residents should control all vendor prices"],
                "El pasaje combina efectos económicos, barreras de entrada, tensiones y acuerdos sobre el uso del espacio.",
                3,
                "a recurring agreement about how public space will be shared",
                ["El objeto de estudio es un mercado temporal.", "Las conexiones pueden continuar después de desmontar los puestos.", "La fijación de precios no se atribuye a residentes."],
            ),
            q("70000000-0000-4000-8000-000000000057", 
                "READ_DETAIL",
                "How can a weekly stall help a small producer?",
                "It allows the producer to test demand with less financial risk.",
                ["It guarantees a permanent location.", "It prevents customers from visiting nearby shops.", "It removes the need to follow local rules."],
                "El segundo párrafo contrasta el costo de una tienda permanente con la posibilidad de probar productos en un puesto.",
                2,
                "a weekly stall can be tested with less risk",
                ["La ubicación es temporal y puede ser objeto de negociación.", "Los comercios cercanos incluso pueden recibir más tránsito.", "Los vendedores necesitan reglas predecibles, no ausencia de reglas."],
            ),
            q("70000000-0000-4000-8000-000000000058", 
                "READ_REFERENCE",
                "The phrase “The flexibility” in paragraph 3 refers to",
                "the temporary and adjustable nature of the market",
                ["the length of permanent store contracts", "the fixed prices of nearby businesses", "the construction of new parking areas"],
                "La frase retoma la facilidad para instalar, probar y modificar un puesto sin una tienda permanente.",
                3,
                "The flexibility also creates tension.",
                ["Los contratos largos representan la alternativa menos flexible.", "No se discuten precios fijos.", "El estacionamiento aparece como posible conflicto, no como nueva construcción."],
            ),
            q("70000000-0000-4000-8000-000000000059", 
                "READ_NEGATIVE_DETAIL",
                "According to the passage, residents may object to all of the following EXCEPT",
                "vendors observing which products buyers prefer",
                ["noise", "blocked parking", "waste"],
                "La observación de demanda se presenta como ventaja empresarial, no como una queja vecinal.",
                2,
                "Vendors can observe which products attract buyers",
                ["El ruido figura entre las objeciones.", "El bloqueo de estacionamiento se menciona como tensión.", "Los residuos también aparecen en la lista de preocupaciones."],
            ),
            q("70000000-0000-4000-8000-000000000060", 
                "READ_PARAPHRASE",
                "Which sentence best expresses the final idea of the passage?",
                "A recurring market depends on continuing cooperation over the use of shared space.",
                ["A market succeeds only when its stalls become permanent.", "Public space cannot support both residents and vendors.", "Market organizers make decisions without consulting anyone else."],
                "La conclusión redefine el mercado como un acuerdo repetido entre varios actores, no solo como estructuras físicas.",
                3,
                "a recurring agreement about how public space will be shared",
                ["La temporalidad es una característica central.", "El texto plantea negociación, no incompatibilidad absoluta.", "Gobierno, negocios y residentes participan junto con organizadores."],
                2,
            ),
        ],
    },
    {
        id: "60000000-0000-4000-8000-000000000011",

        slug: "standard-time",
        title: "When Noon Became Standard",
        topicEs: "Estandarización social del tiempo",
        genre: "social_science",
        cefr: "B2",
        difficulty: 2,
        length: "standard",
        estimatedMinutes: 7,
        paragraphs: [
            "For much of history, towns kept local solar time. Noon occurred when the sun reached its highest point, so clocks in places separated by even modest distances could differ by several minutes. Such differences caused little trouble when travel and communication were slow. A person usually needed to coordinate activities only with others nearby.",
            "Railroads changed that situation in the nineteenth century. Trains crossed many local time systems during a single journey, and printed schedules became difficult to interpret. A departure listed as nine o’clock might refer to station time, railway headquarters time, or the time of another city. Telegraph networks made the inconsistency more visible because messages traveled almost instantly between clocks that disagreed.",
            "Railway companies responded by adopting shared regional times. In some countries, private companies standardized their schedules before national governments established legal time zones. The change was not immediately welcomed. Municipal leaders sometimes saw local time as a symbol of independence, and clock owners had to decide whether to adjust public clocks or display two times.",
            "Eventually, standard time became ordinary enough to seem natural. That familiarity can hide the fact that time zones are negotiated systems rather than direct copies of solar time. Their boundaries bend around political borders and economic relationships, and governments occasionally move them for practical reasons. Standard time solved genuine coordination problems, but it did so by replacing many locally observed noons with a smaller number of socially agreed ones worldwide.",
        ],
        questions: [
            q("70000000-0000-4000-8000-000000000061", 
                "READ_MAIN_IDEA",
                "Which statement best summarizes the development described in the passage?",
                "Faster transport and communication encouraged societies to replace local solar times with shared standards.",
                ["Town clocks became inaccurate because the sun changed speed.", "Governments created railways mainly to eliminate public clocks.", "Local time differences increased after standard zones were adopted."],
                "El argumento conecta la coordinación creada por tren y telégrafo con la adopción gradual de horarios regionales.",
                4,
                "replacing many locally observed noons with a smaller number of socially agreed ones",
                ["La variación provenía de la posición solar local, no de un cambio en la velocidad del sol.", "Los ferrocarriles motivaron la estandarización, no fueron creados para retirar relojes.", "Las zonas redujeron la cantidad de horarios usados."],
            ),
            q("70000000-0000-4000-8000-000000000062", 
                "READ_DETAIL",
                "Why did local solar time create few problems before railroads?",
                "Most coordination occurred among people in the same area.",
                ["All towns had clocks showing identical minutes.", "Telegraph messages traveled very slowly.", "People never traveled beyond their own towns."],
                "Con transporte y comunicación lentos, las actividades se coordinaban principalmente dentro de un entorno local.",
                1,
                "coordinate activities only with others nearby",
                ["Los relojes de lugares distintos podían diferir.", "El telégrafo todavía no era la condición descrita y luego transmitía casi al instante.", "El texto habla de menor necesidad de coordinación distante, no de ausencia total de viajes."],
            ),
            q("70000000-0000-4000-8000-000000000063", 
                "READ_RHETORICAL_PURPOSE",
                "Why does the author give the example of a nine o’clock departure?",
                "To illustrate the ambiguity created by multiple time systems",
                ["To show that all trains left in the morning", "To identify the first legally established time zone", "To argue that printed schedules were unnecessary"],
                "El ejemplo muestra que una misma hora impresa podía referirse a relojes diferentes.",
                2,
                "might refer to station time, railway headquarters time, or the time of another city",
                ["La hora es ilustrativa y no define todos los itinerarios.", "No se asocia con la primera zona legal.", "La dificultad era interpretar horarios, no prescindir de ellos."],
            ),
            q("70000000-0000-4000-8000-000000000064", 
                "READ_INFERENCE",
                "Why might some municipal leaders have resisted railway time?",
                "They believed accepting it could reduce a visible sign of local autonomy.",
                ["They wanted telegraph messages to travel more slowly.", "They believed the sun no longer reached its highest point.", "They preferred schedules that listed no departure times."],
                "El texto afirma que el tiempo local podía simbolizar independencia; sustituirlo implicaba ceder una convención propia.",
                3,
                "local time as a symbol of independence",
                ["La velocidad del telégrafo no dependía de la preferencia municipal.", "El mediodía solar seguía existiendo.", "La resistencia era al estándar, no a toda información horaria."],
                2,
            ),
            q("70000000-0000-4000-8000-000000000065", 
                "READ_TONE",
                "How does the author characterize modern time zones?",
                "As useful social agreements whose apparent naturalness hides historical choices",
                ["As exact representations of solar noon everywhere", "As failures that created more confusion than local time", "As systems determined only by geography"],
                "La conclusión reconoce la utilidad de coordinación y a la vez subraya su carácter negociado, político y económico.",
                4,
                "negotiated systems rather than direct copies of solar time",
                ["Las fronteras se apartan del mediodía solar local.", "El texto afirma que resolvieron problemas genuinos.", "Las fronteras también siguen relaciones políticas y económicas."],
                3,
            ),
        ],
    },
    {
        id: "60000000-0000-4000-8000-000000000012",

        slug: "community-mapping",
        title: "Maps Made by Residents",
        topicEs: "Cartografía participativa",
        genre: "social_science",
        cefr: "B1",
        difficulty: 2,
        length: "short",
        estimatedMinutes: 5,
        paragraphs: [
            "Official maps are designed for particular purposes, so they inevitably leave some information out. A transportation map may show roads but omit an informal footpath used daily by residents. A land-use map may identify buildings without recording where seasonal flooding blocks an entrance. Community mapping projects invite local people to document such knowledge.",
            "Participants may draw on printed maps, collect coordinates with phones, or annotate photographs. The process matters as much as the finished map. When residents compare observations, they often discover that groups experience the same place differently. A well-lit route preferred by one person may be inaccessible to someone using a wheelchair.",
            "Community knowledge is detailed but not automatically complete or neutral. Meetings can exclude people who lack time, confidence, or social status. Facilitators therefore use multiple ways to contribute and record who participated. The goal is not to replace technical surveys but to place lived experience alongside them, making decisions about public space better informed.",
        ],
        questions: [
            q("70000000-0000-4000-8000-000000000066", 
                "READ_PRIMARY_PURPOSE",
                "What is the passage mainly intended to explain?",
                "How community mapping adds residents’ experience to technical information",
                ["Why official maps should contain no roads", "How phones automatically resolve social inequality", "Why residents always agree about public space"],
                "El texto describe qué aporta la cartografía comunitaria, cómo se realiza y qué límites debe reconocer.",
                3,
                "place lived experience alongside them",
                ["Las carreteras son un ejemplo útil de información oficial.", "Los teléfonos son una herramienta, no una solución social automática.", "Las experiencias pueden diferir entre grupos."],
            ),
            q("70000000-0000-4000-8000-000000000067", 
                "READ_DETAIL",
                "Which information might residents add to a land-use map?",
                "An entrance that becomes blocked during seasonal flooding",
                ["The legal definition of every national border", "The time shown by railway headquarters", "The chemical composition of volcanic ash"],
                "El primer párrafo ofrece directamente la obstrucción estacional como información que un mapa de edificios podría omitir.",
                1,
                "where seasonal flooding blocks an entrance",
                ["Las fronteras nacionales no son el ejemplo local presentado.", "El tiempo ferroviario pertenece a otro problema.", "La composición mineral requeriría otro tipo de estudio."],
            ),
            q("70000000-0000-4000-8000-000000000068", 
                "READ_INFERENCE",
                "Why can comparing observations improve a map?",
                "It reveals needs that may be visible to one group but not another.",
                ["It guarantees that every participant uses a wheelchair.", "It removes the need to record participation.", "It makes technical surveys permanently inaccurate."],
                "El contraste entre ruta iluminada y accesibilidad demuestra que usuarios distintos detectan características distintas.",
                2,
                "groups experience the same place differently",
                ["La silla de ruedas es un ejemplo de perspectiva, no una condición universal.", "Registrar quién participó sigue siendo necesario.", "El objetivo es complementar las encuestas técnicas."],
                2,
            ),
            q("70000000-0000-4000-8000-000000000069", 
                "READ_VOCAB_CONTEXT",
                "The word “neutral” in paragraph 3 is closest in meaning to",
                "free from the influence of particular perspectives",
                ["drawn without color", "impossible to share", "limited to printed paper"],
                "El párrafo advierte que quién participa influye en el conocimiento representado; «neutral» alude a ausencia de sesgo de perspectiva.",
                3,
                "not automatically complete or neutral",
                ["El uso de color no se discute.", "Los proyectos se basan precisamente en compartir observaciones.", "Se admiten mapas impresos, teléfonos y fotografías."],
            ),
            q("70000000-0000-4000-8000-000000000070", 
                "READ_NEGATIVE_DETAIL",
                "All of the following are mentioned as ways to contribute to a community map EXCEPT",
                "changing a national law",
                ["drawing on a printed map", "collecting phone coordinates", "annotating photographs"],
                "Cambiar una ley no aparece como método de recopilación; las otras tres actividades sí se enumeran.",
                2,
                "draw on printed maps, collect coordinates with phones, or annotate photographs",
                ["Dibujar sobre mapas impresos se menciona expresamente.", "Las coordenadas pueden registrarse con teléfonos.", "Las fotografías pueden recibir anotaciones."],
            ),
        ],
    },
    {
        id: "60000000-0000-4000-8000-000000000013",

        slug: "learning-through-apprenticeship",
        title: "Learning Beside an Expert",
        topicEs: "Aprendizaje por participación",
        genre: "social_science",
        cefr: "B2",
        difficulty: 2,
        length: "standard",
        estimatedMinutes: 7,
        paragraphs: [
            "An apprenticeship is often described as learning by imitation, but observation alone is rarely enough. Newcomers usually begin with limited, low-risk tasks that contribute to real work. In a bakery, an apprentice might weigh ingredients before mixing dough; in a workshop, the learner may organize tools before operating machinery. These tasks introduce the sequence and standards of the activity without making the beginner responsible for its most dangerous parts.",
            "As competence grows, responsibility expands. Experts demonstrate procedures, but they also make tacit judgments that are difficult to express as rules. A potter adjusts pressure after feeling the clay change; a technician notices a vibration that indicates a machine is misaligned. Learners acquire this knowledge through repeated participation, questions, correction, and comparison of outcomes.",
            "The social structure of the workplace affects what can be learned. An expert who performs every difficult step without explanation may remain impressive but teaches little. Likewise, a learner who fears exposing uncertainty may avoid asking necessary questions. Effective apprenticeships create room for early mistakes whose consequences are manageable and provide timely, specific feedback before those mistakes become lasting habits.",
            "Apprenticeship should not be romanticized. Traditional arrangements have sometimes depended on unpaid labor or excluded people from professions through informal networks. Modern programs attempt to preserve situated practice while adding clear standards, fair compensation, and accessible routes for reporting problems. Their central challenge is to formalize protection without reducing learning to a checklist detached from real work.",
        ],
        questions: [
            q("70000000-0000-4000-8000-000000000071", 
                "READ_MAIN_IDEA",
                "What central idea does the passage develop?",
                "Apprenticeship builds practical judgment through guided participation, but its structure must also protect learners.",
                ["Apprentices learn best when they receive no feedback.", "Observation is the only useful part of workplace learning.", "Formal standards and real work can never coexist."],
                "El texto explica progresión, conocimiento tácito y retroalimentación, y termina incorporando protección y acceso justo.",
                4,
                "preserve situated practice while adding clear standards, fair compensation, and accessible routes for reporting problems",
                ["La retroalimentación evita que los errores se vuelvan hábitos.", "La participación y responsabilidad gradual complementan la observación.", "El reto es combinarlos, no declarar imposible su coexistencia."],
            ),
            q("70000000-0000-4000-8000-000000000072", 
                "READ_RHETORICAL_PURPOSE",
                "Why does the author mention weighing ingredients and organizing tools?",
                "To illustrate useful beginner tasks with limited risk",
                ["To compare the profits of bakeries and workshops", "To show that apprentices should never advance", "To identify tasks that experts are unable to perform"],
                "Los ejemplos concretan cómo un principiante participa en trabajo real sin asumir todavía las partes peligrosas.",
                1,
                "limited, low-risk tasks that contribute to real work",
                ["No se presentan datos económicos.", "La responsabilidad aumenta conforme crece la competencia.", "Los expertos pueden realizar esas tareas; se asignan por su valor formativo y menor riesgo."],
            ),
            q("70000000-0000-4000-8000-000000000073", 
                "READ_VOCAB_CONTEXT",
                "The word “tacit” in paragraph 2 is closest in meaning to",
                "understood through practice but not easily stated",
                ["written in a detailed manual", "unrelated to physical work", "known only to customers"],
                "Los ejemplos de tacto y vibración muestran juicios que el experto ejecuta pero que resultan difíciles de convertir en reglas.",
                2,
                "difficult to express as rules",
                ["Un manual detallado sería conocimiento explícito.", "Los juicios están integrados en la práctica física.", "Los poseen trabajadores expertos, no exclusivamente clientes."],
            ),
            q("70000000-0000-4000-8000-000000000074", 
                "READ_INFERENCE",
                "Why should early mistakes have manageable consequences?",
                "So learners can receive correction without causing serious harm.",
                ["So mistakes can be repeated until they become habits.", "So experts no longer need to supervise work.", "So workplaces can avoid explaining any standards."],
                "El pasaje valora un entorno donde sea posible equivocarse y corregir antes de consolidar el error o producir daños mayores.",
                3,
                "provide timely, specific feedback before those mistakes become lasting habits",
                ["El objetivo es impedir que se conviertan en hábitos.", "La supervisión y retroalimentación siguen siendo centrales.", "Los estándares claros forman parte de los programas modernos."],
                2,
            ),
            q("70000000-0000-4000-8000-000000000075", 
                "READ_TONE",
                "The author’s attitude toward apprenticeship is best described as",
                "supportive but attentive to its risks and exclusions",
                ["uncritically nostalgic", "entirely opposed to workplace learning", "certain that unpaid labor is always necessary"],
                "Se reconocen ventajas pedagógicas y, al mismo tiempo, se advierte contra idealizar arreglos injustos.",
                4,
                "Apprenticeship should not be romanticized.",
                ["La crítica explícita impide una visión nostálgica sin reservas.", "El texto propone mejorar, no abandonar, el aprendizaje situado.", "La compensación se presenta como protección moderna."],
                3,
            ),
        ],
    },
    {
        id: "60000000-0000-4000-8000-000000000014",

        slug: "bilingual-signs",
        title: "Reading a Bilingual Street",
        topicEs: "Señalización y lenguas en espacio público",
        genre: "social_science",
        cefr: "B2",
        difficulty: 2,
        length: "standard",
        estimatedMinutes: 7,
        paragraphs: [
            "Bilingual signs do more than repeat the same message in two languages. They help people find essential public services, understand safety information, and participate fully in public life. At the same time, choices about which language appears first, which receives larger letters, and where each language is used communicate something about status and belonging.",
            "The two versions are not always direct translations. A transit agency may use a short standardized term in one language and a fuller explanation in another because readers have different familiarity with the system. A place name may retain an older Indigenous form while practical directions appear in a national language. Designers must consider clarity, available space, reading direction, and the expectations attached to each language.",
            "Researchers sometimes study a city’s “linguistic landscape” by photographing and classifying signs. A count can show where languages are visible, but numbers alone may mislead. Ten small temporary notices do not necessarily carry the same authority as one permanent sign above a government office. Interpretation therefore requires attention to location, material, size, authorship, and audience.",
            "Signage policies can increase access, yet they cannot by themselves guarantee equal treatment. A hospital may display multilingual directions while lacking trained staff who can discuss complex care with patients. Conversely, an unofficial handwritten sign may provide highly useful and timely information within a neighborhood. Public language is best understood not as decoration but as one layer of a larger system of communication and power.",
        ],
        questions: [
            q("70000000-0000-4000-8000-000000000076", 
                "READ_PRIMARY_PURPOSE",
                "What is the author’s main purpose?",
                "To show that bilingual signage conveys practical information as well as social relationships",
                ["To argue that every sign should use identical wording", "To teach readers how to count letters on a sign", "To prove that permanent signs are always accurate"],
                "El pasaje combina acceso, diseño, análisis de autoridad y límites institucionales para mostrar una función doble.",
                4,
                "one layer of a larger system of communication and power",
                ["Las traducciones pueden variar según lectores y contexto.", "El conteo de señales es un método parcial, no un objetivo en sí.", "La permanencia indica autoridad posible, no exactitud garantizada."],
            ),
            q("70000000-0000-4000-8000-000000000077", 
                "READ_DETAIL",
                "Why might a transit message be longer in one language?",
                "Readers of that language may be less familiar with the transit system.",
                ["The language cannot be written in small letters.", "Transit agencies are forbidden to translate directly.", "The shorter language always has higher social status."],
                "El segundo párrafo da como razón una familiaridad distinta con el sistema, lo que puede exigir más explicación.",
                2,
                "readers have different familiarity with the system",
                ["El tamaño de letras es una decisión separada.", "No se establece una prohibición general.", "La longitud no se equipara automáticamente con jerarquía."],
            ),
            q("70000000-0000-4000-8000-000000000078", 
                "READ_INFERENCE",
                "Why can a simple count of signs be misleading?",
                "Signs differ in visibility, permanence, authority, and intended audience.",
                ["Photographs cannot record written language.", "Cities contain only temporary signs.", "Every government sign uses two languages."],
                "El autor contrasta diez avisos pequeños con una señal oficial permanente y pide atender a cualidades además de cantidad.",
                3,
                "numbers alone may mislead",
                ["Las fotografías son precisamente una herramienta de estudio.", "Se distinguen señales temporales y permanentes.", "No se afirma bilingüismo universal en señales gubernamentales."],
                2,
            ),
            q("70000000-0000-4000-8000-000000000079", 
                "READ_REFERENCE",
                "The word “they” in paragraph 4 refers to",
                "signage policies",
                ["hospital patients", "multilingual directions", "neighborhoods"],
                "El pronombre retoma el sujeto de la oración anterior: las políticas pueden ampliar acceso pero no garantizar trato igual.",
                4,
                "Signage policies can increase access, yet they",
                ["Los pacientes aparecen después como usuarios de atención.", "Las direcciones son un ejemplo de señalización, no el antecedente gramatical.", "Los barrios se mencionan en relación con letreros informales."],
            ),
            q("70000000-0000-4000-8000-000000000080", 
                "READ_PARAPHRASE",
                "Which statement best expresses the final paragraph?",
                "Multilingual information helps, but equal communication also requires capable institutions and local practice.",
                ["Once official signs are translated, no further language support is needed.", "Unofficial neighborhood signs have little practical value for residents.", "Hospitals should replace trained multilingual staff members with larger signs."],
                "Los ejemplos del hospital y el barrio muestran que las señales son solo una capa de un sistema más amplio.",
                4,
                "they cannot by themselves guarantee equal treatment",
                ["La falta de personal competente demuestra que la traducción visual no basta.", "El aviso manuscrito puede ser muy útil.", "El texto reclama comunicación humana además de señalización."],
                3,
            ),
        ],
    },
    {
        id: "60000000-0000-4000-8000-000000000015",

        slug: "counting-a-population",
        title: "Counting a Moving Population",
        topicEs: "Métodos y efectos de los censos",
        genre: "social_science",
        cefr: "B2",
        difficulty: 3,
        length: "long",
        estimatedMinutes: 13,
        paragraphs: [
            "A census aims to describe an entire population at a particular moment. Governments use the results to distribute legislative seats, plan schools and transportation, and compare changes across regions. The apparent simplicity of counting everyone hides a basic difficulty: a population is constantly moving. People are born, die, travel, share homes temporarily, or live in places that official records do not recognize.",
            "To make the task possible, census agencies establish rules about where each person should be counted. A student living away from home, a seasonal worker, or a person staying with relatives could plausibly be associated with more than one address. Most systems choose a concept such as usual residence and specify a reference date. These conventions do not eliminate ambiguity, but they make separate responses more comparable.",
            "Methods of collecting information have changed. Enumerators once visited nearly every household with paper forms. Many agencies now invite online responses first, then send reminders or workers to addresses that have not replied. Administrative records may help identify occupied buildings or check basic details. Using several sources can reduce cost, but it also requires careful procedures to prevent the same person from being counted twice.",
            "Undercounting is not evenly distributed. People in remote areas may be difficult to reach, while those who move frequently may miss forms and follow-up visits. Language barriers, distrust of government, or fear that information will be shared with other agencies can also reduce participation. A high national response rate may therefore coexist with serious gaps in particular communities.",
            "Agencies attempt to measure these gaps after the main count. One method surveys a smaller sample independently and compares its records with census responses. Statistical models can then estimate how many people were probably missed or duplicated. Adjustment is controversial because it replaces some direct counts with estimates, yet leaving known patterns of omission untouched also affects representation and funding.",
            "Question wording creates another source of change. Categories used to describe occupation, household relationships, disability, or identity evolve as societies and policy needs change. A new category may make previously invisible experiences measurable, but it can complicate comparison with earlier censuses. Researchers must decide whether an apparent increase reflects social change, a new definition, or greater willingness to answer.",
            "The census is therefore both a measurement and an institution. Its numbers influence important public decisions, and those decisions can affect whether communities trust the next national count. Public discussion before forms are finalized can expose unclear wording and practical barriers for local residents. Transparency about definitions, privacy protections, uncertainty, and correction methods is essential. No census produces a perfectly still portrait of society, but a carefully designed one can provide a shared reference while making its limitations visible.",
        ],
        questions: [
            q("70000000-0000-4000-8000-000000000081", 
                "READ_MAIN_IDEA",
                "Which statement best captures the central argument of the passage?",
                "A census requires conventions, multiple methods, and transparent corrections to represent a changing population.",
                ["A census is a simple total that requires no definitions.", "Online forms have eliminated all population undercounts.", "Census categories should never change over time."],
                "El texto desarrolla dificultades de residencia, recolección, omisión, estimación y categorías antes de defender transparencia.",
                7,
                "a carefully designed one can provide a shared reference while making its limitations visible",
                ["Las reglas de residencia muestran que contar exige definiciones.", "Persisten brechas incluso con métodos digitales.", "Las categorías cambian con la sociedad y las necesidades."],
                3,
            ),
            q("70000000-0000-4000-8000-000000000082", 
                "READ_DETAIL",
                "Why do census systems establish a reference date?",
                "To apply residence rules consistently to a population that is always changing",
                ["To guarantee that nobody travels that day", "To prevent students from having an address", "To replace all household responses with estimates"],
                "La fecha y el concepto de residencia crean una convención común para casos que podrían asociarse con varios lugares.",
                2,
                "make separate responses more comparable",
                ["Una fecha de referencia no detiene los desplazamientos.", "Los estudiantes ilustran ambigüedad, no ausencia de domicilio.", "Las estimaciones se usan para evaluar omisiones después."],
            ),
            q("70000000-0000-4000-8000-000000000083", 
                "READ_VOCAB_CONTEXT",
                "The word “plausibly” in paragraph 2 is closest in meaning to",
                "reasonably",
                ["permanently", "secretly", "incorrectly"],
                "Los ejemplos pueden vincularse con más de una dirección de manera razonable, por eso se necesitan reglas convencionales.",
                2,
                "could plausibly be associated with more than one address",
                ["La asociación puede ser temporal.", "El problema no depende de ocultar información.", "Más de una dirección puede ser válida según el criterio usado."],
            ),
            q("70000000-0000-4000-8000-000000000084", 
                "READ_RHETORICAL_PURPOSE",
                "Why does the author describe online responses followed by visits?",
                "To illustrate how agencies combine collection methods",
                ["To show that enumerators no longer perform any work", "To argue that paper forms count people twice by design", "To identify the only method used in remote areas"],
                "La secuencia ejemplifica un enfoque escalonado que combina canales y concentra seguimiento donde falta respuesta.",
                3,
                "Using several sources can reduce cost",
                ["Los trabajadores siguen visitando direcciones sin respuesta.", "La duplicación es un riesgo que se intenta prevenir, no un objetivo.", "No se limita el ejemplo a regiones remotas."],
                2,
            ),
            q("70000000-0000-4000-8000-000000000085", 
                "READ_INFERENCE",
                "Why can a high national response rate give a misleading impression?",
                "It can conceal severe undercounting concentrated in particular groups or places.",
                ["It proves that every community has the same participation.", "It means that no statistical models are needed.", "It counts every mobile person more than once."],
                "El promedio nacional puede ser alto aunque comunidades específicas tengan barreras y ausencias sistemáticas.",
                4,
                "coexist with serious gaps in particular communities",
                ["El párrafo afirma una distribución desigual.", "Los modelos pueden seguir siendo necesarios para medir brechas.", "La movilidad puede producir omisión o duplicación, pero no necesariamente en todos los casos."],
                3,
            ),
            q("70000000-0000-4000-8000-000000000086", 
                "READ_NEGATIVE_DETAIL",
                "All of the following are mentioned as possible barriers to census participation EXCEPT",
                "having a permanent government office nearby",
                ["frequent movement", "language differences", "distrust about data sharing"],
                "Una oficina cercana no aparece entre las barreras; sí se mencionan movilidad, idioma, desconfianza y distancia.",
                4,
                "Language barriers, distrust of government, or fear that information will be shared",
                ["Mudarse con frecuencia puede hacer perder formularios y visitas.", "Las barreras lingüísticas reducen participación.", "El temor al intercambio de datos se identifica directamente."],
            ),
            q("70000000-0000-4000-8000-000000000087", 
                "READ_TONE",
                "How does the author present statistical adjustment?",
                "As contested but potentially necessary when direct counts have known biases",
                ["As unquestionably perfect", "As a deliberate attempt to hide all direct responses", "As irrelevant to representation and funding"],
                "El pasaje reconoce la controversia y también el costo de dejar omisiones sistemáticas sin corregir.",
                5,
                "Adjustment is controversial",
                ["Los modelos estiman y conservan incertidumbre.", "La comparación parte de respuestas directas y una encuesta independiente.", "El texto vincula expresamente omisión con representación y recursos."],
                3,
            ),
            q("70000000-0000-4000-8000-000000000088", 
                "READ_REFERENCE",
                "The phrase “these gaps” in paragraph 5 refers to",
                "patterns of people being missed or unevenly represented",
                ["differences between paper colors", "distances between legislative seats", "changes in school schedules"],
                "La expresión retoma la subrepresentación desigual descrita en el párrafo anterior.",
                5,
                "Agencies attempt to measure these gaps",
                ["No se analizan colores de formularios.", "Los escaños usan resultados, pero la distancia entre ellos no es una brecha de conteo.", "Los horarios escolares no se discuten."],
            ),
            q("70000000-0000-4000-8000-000000000089", 
                "READ_PARAPHRASE",
                "Which statement best expresses the problem discussed in paragraph 6?",
                "Changes in census categories can improve visibility while making historical comparison harder.",
                ["New categories always prove that a population suddenly appeared.", "Earlier census data become completely useless after wording changes.", "Respondents never change how willing they are to answer."],
                "El párrafo plantea una ganancia de medición y una dificultad interpretativa entre cambio social, definición y respuesta.",
                6,
                "make previously invisible experiences measurable, but it can complicate comparison",
                ["Una nueva medición no demuestra por sí sola aparición repentina.", "La comparación se complica, pero no se vuelve imposible.", "La voluntad de responder es una explicación considerada."],
                3,
            ),
            q("70000000-0000-4000-8000-000000000090", 
                "READ_ORGANIZATION",
                "Which description best matches the structure of the passage?",
                "It moves from counting problems through methods and biases to the consequences of census design.",
                ["It lists major census years and their results in chronological order.", "It compares two private survey companies and their online methods.", "It begins with a conclusion and then rejects every use of census data."],
                "La progresión va de definición y residencia a recolección, omisión, categorías y confianza pública.",
                7,
                "The census is therefore both a measurement and an institution.",
                ["No se ofrece una cronología de años censales.", "Las agencias y métodos son generales, no empresas específicas.", "La conclusión conserva el valor del censo como referencia compartida."],
                3,
            ),
        ],
    },
    {
        id: "60000000-0000-4000-8000-000000000016",

        slug: "water-by-agreement",
        title: "Water by Agreement",
        topicEs: "Gobernanza comunitaria del riego",
        genre: "social_science",
        cefr: "C1",
        difficulty: 3,
        length: "long",
        estimatedMinutes: 14,
        paragraphs: [
            "In dry farming regions, an irrigation canal is both a physical structure and a schedule of obligations. Water must be diverted from a river, carried across uneven ground, and delivered to fields in an order that users recognize as legitimate. A technically efficient canal can still fail if farmers do not maintain it or believe that distribution is unfair.",
            "Many long-lived systems assign water in turns. A household may receive a flow for a fixed number of hours, or its turn may last until a field reaches a specified point of saturation. The rule chosen reflects local conditions. Time is easier to measure, but equal hours do not deliver equal volumes when flow changes. A field-based rule adapts to need but may be harder for others to verify.",
            "Maintenance is commonly organized as collective labor. Before the growing season, users remove sediment, repair walls, and clear plants from the channel. Participation may be proportional to land area, water rights, or household status. Someone unable to work might contribute money or provide food. These arrangements convert an individual need for water into repeated cooperation.",
            "Monitoring matters because upstream users can take water before it reaches downstream fields. Communities respond with canal guards, rotating inspectors, visible gates, or public records of turns. Effective monitoring does not require constant punishment. When rules and actions are observable, most users can anticipate how violations will be detected, and disputes can be addressed before distrust spreads.",
            "Not all traditions are equitable. Rules inherited from earlier periods may favor large landowners, exclude tenants, or assign obligations differently by gender. Calling a system communal does not guarantee that every affected person has a voice. Reforms sometimes create elected committees or written appeals, but formal procedures can also be captured by people with more time, literacy, or political influence.",
            "External projects can unintentionally weaken local coordination. An agency may line a canal with concrete to reduce leakage but ignore the fact that seepage replenished wells or supported plants used by households. It may install gates that are efficient yet too expensive for local repair. Conversely, romanticizing traditional practice can preserve avoidable losses and unequal rules. Useful intervention begins by understanding both hydraulic flows and social relationships.",
            "Climate variability adds pressure to these institutions. A schedule designed around a reliable snowmelt may become difficult to follow when water arrives earlier or in shorter bursts. Communities may need to revise the length of turns, prioritize crops differently, or reserve water for domestic use. Such changes can impose unequal local costs, so temporary experiments and public review may be especially useful. Whether local adaptation succeeds depends not only on available engineering but on whether users consider the process for changing rules legitimate.",
        ],
        questions: [
            q("70000000-0000-4000-8000-000000000091", 
                "READ_MAIN_IDEA",
                "What central claim does the passage make about irrigation systems?",
                "Their success depends on legitimate social rules as well as physical engineering.",
                ["Concrete canals automatically produce equal water access.", "Traditional rules are always fairer than written procedures.", "Water schedules matter only when rainfall is abundant."],
                "Cada sección relaciona infraestructura con turnos, trabajo, monitoreo, desigualdad, intervención y adaptación legítima.",
                1,
                "both a physical structure and a schedule of obligations",
                ["El concreto puede causar efectos ignorados y no resuelve legitimidad.", "Las tradiciones pueden reproducir desigualdad.", "Los horarios son especialmente críticos en regiones secas."],
                3,
            ),
            q("70000000-0000-4000-8000-000000000092", 
                "READ_DETAIL",
                "What disadvantage of allocating water by fixed hours is mentioned?",
                "Changing flow can cause equal periods to deliver unequal amounts.",
                ["Hours cannot be measured.", "Every field receives too much water.", "The rule prevents any public schedule."],
                "El segundo párrafo contrasta facilidad de medir tiempo con variación del volumen cuando cambia el caudal.",
                2,
                "equal hours do not deliver equal volumes when flow changes",
                ["El tiempo se describe como más fácil de medir.", "El resultado depende del flujo y no siempre es exceso.", "Los turnos pueden registrarse públicamente."],
            ),
            q("70000000-0000-4000-8000-000000000093", 
                "READ_VOCAB_CONTEXT",
                "The word “proportional” in paragraph 3 is closest in meaning to",
                "determined in relation to an amount or share",
                ["secretly assigned", "identical for every person", "unrelated to land or rights"],
                "La contribución puede variar según superficie, derechos o posición, es decir, guardar relación con una medida.",
                3,
                "proportional to land area, water rights, or household status",
                ["La organización es comunitaria y observable.", "La proporcionalidad permite cargas diferentes.", "La frase enumera precisamente los factores relacionados."],
            ),
            q("70000000-0000-4000-8000-000000000094", 
                "READ_INFERENCE",
                "Why can visible gates and public records reduce the need for frequent punishment?",
                "They make behavior observable and violations easier to anticipate or resolve.",
                ["They prevent upstream farms from using any water.", "They eliminate every disagreement about rules.", "They allow inspectors to remain permanently absent."],
                "La observabilidad favorece cumplimiento y tratamiento temprano de disputas sin depender solo de sanciones constantes.",
                4,
                "When rules and actions are observable",
                ["Los usuarios río arriba conservan turnos legítimos.", "El texto habla de abordar disputas, no de eliminarlas.", "Existen guardias o inspectores aunque su rotación varíe."],
                3,
            ),
            q("70000000-0000-4000-8000-000000000095", 
                "READ_TONE",
                "How does the author treat community traditions?",
                "As valuable sources of coordination that still require critical examination",
                ["As perfect systems that outsiders should never question", "As obstacles that must always be replaced by technology", "As practices unrelated to power"],
                "Se reconocen cooperación y duración, pero también exclusiones y la posibilidad de reformas.",
                5,
                "Not all traditions are equitable.",
                ["La desigualdad heredada exige revisión.", "La intervención útil comprende el sistema en vez de sustituirlo automáticamente.", "El texto analiza explícitamente voz e influencia."],
                3,
            ),
            q("70000000-0000-4000-8000-000000000096", 
                "READ_NEGATIVE_DETAIL",
                "All of the following are described as forms of canal maintenance contribution EXCEPT",
                "writing national weather forecasts",
                ["removing sediment", "repairing canal walls", "providing food when unable to work"],
                "El pronóstico nacional no aparece como contribución al mantenimiento; las otras acciones sí.",
                3,
                "remove sediment, repair walls, and clear plants",
                ["Retirar sedimento es una tarea colectiva.", "Reparar paredes ocurre antes de la temporada.", "Alguien puede aportar comida o dinero en lugar de trabajo físico."],
            ),
            q("70000000-0000-4000-8000-000000000097", 
                "READ_RHETORICAL_PURPOSE",
                "Why does the author mention seepage replenishing wells?",
                "To show that an apparently inefficient feature can provide benefits outside the canal.",
                ["To prove that all canal leakage should increase", "To explain why concrete is impossible to manufacture", "To show that wells cause every irrigation dispute"],
                "El ejemplo advierte que una mejora técnica aislada puede eliminar servicios hídricos o ecológicos no considerados.",
                6,
                "seepage replenished wells or supported plants",
                ["El texto pide evaluar efectos, no maximizar pérdidas.", "El problema es adecuación social y ecológica, no fabricación.", "Los conflictos tienen múltiples causas y no se atribuyen a pozos."],
                3,
            ),
            q("70000000-0000-4000-8000-000000000098", 
                "READ_REFERENCE",
                "The phrase “These arrangements” in paragraph 3 refers to",
                "the different ways users contribute labor, money, or food",
                ["the timing of snowmelt", "the installation of concrete gates", "the exclusion of tenants"],
                "El demostrativo resume las formas de participación y sustitución de trabajo descritas inmediatamente antes.",
                3,
                "These arrangements convert an individual need for water into repeated cooperation.",
                ["El deshielo se discute al final.", "Las compuertas externas aparecen varios párrafos después.", "La exclusión se presenta como problema distinto."],
            ),
            q("70000000-0000-4000-8000-000000000099", 
                "READ_PARAPHRASE",
                "Which statement best expresses the final sentence?",
                "Adaptation needs both technical options and user trust in how rules change.",
                ["Engineering becomes unnecessary whenever a community changes its water rules.", "Legitimate decision processes guarantee that additional water will become available.", "Users should preserve every traditional schedule without discussion or revision."],
                "La conclusión distingue disponibilidad técnica de legitimidad del proceso institucional de cambio.",
                7,
                "depends not only on available engineering but on whether users consider the process for changing rules legitimate",
                ["La ingeniería sigue siendo relevante, pero no suficiente.", "La legitimidad facilita adaptación sin crear agua adicional.", "El clima cambiante puede exigir revisar horarios anteriores."],
                3,
            ),
            q("70000000-0000-4000-8000-000000000100", 
                "READ_ORGANIZATION",
                "How does paragraph 6 function in the passage?",
                "It warns against both purely technical intervention and uncritical preservation of tradition.",
                ["It introduces a single solution that works in every region.", "It changes the topic from water to urban libraries.", "It argues that leakage has no consequences."],
                "El párrafo critica tanto proyectos que ignoran relaciones locales como la idealización de prácticas ineficientes o injustas.",
                6,
                "Conversely, romanticizing traditional practice can preserve avoidable losses and unequal rules.",
                ["La conclusión pide comprender cada contexto.", "El tema sigue siendo coordinación del riego.", "La filtración puede alimentar pozos y plantas."],
                3,
            ),
        ],
    },
];
