import { q, type ReadingPassageSeed } from "../readingBankTypes";

export const TECHNOLOGY_PASSAGES: readonly ReadingPassageSeed[] = [
    {
        slug: "clocks-and-escapements",
        title: "Releasing Time One Step at a Time",
        topicEs: "Mecanismos de relojería",
        genre: "technology",
        cefr: "B1",
        difficulty: 1,
        length: "short",
        estimatedMinutes: 5,
        paragraphs: [
            "A mechanical clock needs stored energy, often supplied by a falling weight or wound spring. If that energy were released freely, the gears would spin quickly and stop. The escapement solves this problem by alternately locking and releasing a gear in small, regular steps.",
            "Each release gives a pendulum or balance wheel a slight push. The oscillator then controls when the next tooth can pass. The familiar ticking sound comes from these repeated contacts. Accuracy depends on the steadiness of the oscillator as well as the shape, friction, and alignment of the parts.",
            "No escapement is perfectly isolated from its environment. Temperature can change the dimensions of components, oil can thicken, and motion can disturb a portable watch. Later designs and materials reduced these effects. Their goal was not to create energy but to divide its release into intervals that remained as uniform as possible.",
        ],
        questions: [
            q(
                "READ_MAIN_IDEA",
                "What function of a clock escapement does the passage explain?",
                "It controls stored energy by releasing the gear in regular steps.",
                ["It generates unlimited energy inside the clock.", "It prevents every part from moving.", "It measures temperature without using gears."],
                "El texto explica bloqueo, liberación, oscilador y factores que afectan regularidad.",
                1,
                "alternately locking and releasing a gear in small, regular steps",
                ["La energía procede de peso o resorte.", "El mecanismo permite movimiento controlado.", "La temperatura es una perturbación, no la variable medida."],
            ),
            q(
                "READ_DETAIL",
                "What produces the familiar ticking sound?",
                "Repeated contacts as the escapement locks and releases",
                ["A spring becoming completely unwound at once", "Oil flowing through the clock face", "The clock measuring outdoor light"],
                "El segundo párrafo vincula directamente los contactos repetidos con el sonido.",
                2,
                "ticking sound comes from these repeated contacts",
                ["La liberación libre haría girar y detener rápidamente.", "El aceite afecta fricción pero no se describe como origen del tic.", "La luz no forma parte del mecanismo."],
            ),
            q(
                "READ_VOCAB_CONTEXT",
                "The word “steadiness” in paragraph 2 is closest in meaning to",
                "regularity",
                ["size", "brightness", "cost"],
                "La precisión depende de que el oscilador mantenga un período constante.",
                2,
                "Accuracy depends on the steadiness of the oscillator",
                ["Las dimensiones influyen, pero no definen la palabra.", "El reloj no produce luz en este contexto.", "No se discute precio."],
            ),
            q(
                "READ_INFERENCE",
                "Why would a clock run poorly if its gears were released without an escapement?",
                "Its stored energy would be spent too rapidly to mark equal intervals.",
                ["The pendulum would create additional energy.", "Temperature would stop affecting metal.", "Every tooth would become larger."],
                "El contraste inicial explica que la liberación libre hace girar los engranes rápido y agota el sistema.",
                1,
                "gears would spin quickly and stop",
                ["El oscilador regula, no crea energía neta.", "La temperatura seguiría afectando componentes.", "No se describe crecimiento de dientes."],
                2,
            ),
            q(
                "READ_PARAPHRASE",
                "Which statement best expresses the passage’s final point?",
                "Improved clock designs make energy release more uniform rather than producing the energy themselves.",
                ["Modern escapements no longer need moving parts.", "Portable watches are unaffected by motion.", "The main purpose of an escapement is to warm the oil."],
                "El cierre distingue la fuente energética de la función reguladora y reconoce perturbaciones reducidas, no eliminadas.",
                3,
                "not to create energy but to divide its release into intervals",
                ["El mecanismo sigue basado en contactos y oscilación.", "El movimiento puede perturbar relojes portátiles.", "La viscosidad del aceite es un problema, no un objetivo."],
                2,
            ),
        ],
    },
    {
        slug: "open-source-repair",
        title: "Instructions That Remain Open",
        topicEs: "Diseño abierto y reparabilidad",
        genre: "technology",
        cefr: "B1",
        difficulty: 2,
        length: "short",
        estimatedMinutes: 5,
        paragraphs: [
            "An open hardware project publishes enough design information for others to study, modify, and build the device. Files may include diagrams, circuit layouts, software, parts lists, and assembly instructions. Access to a drawing alone is not always sufficient; a useful project also states versions, tolerances, and testing procedures.",
            "Openness can support repair. When a component fails, a technician can identify it and understand how it interacts with the rest of the system. Communities may propose replacement parts after the original component is no longer sold. Shared documentation also lets users discover recurring failures and improve later versions.",
            "Open design does not guarantee that repair will be easy or safe. Specialized tools, high voltage, sealed materials, or unavailable components can still create barriers. Licenses explain what others may legally do with the files, while practical documentation explains what they can realistically accomplish. Both are important, but they solve different problems.",
        ],
        questions: [
            q(
                "READ_PRIMARY_PURPOSE",
                "What distinction does the passage make about open hardware?",
                "Publishing designs enables study and repair, but practical barriers can remain.",
                ["Open files guarantee that every device is safe to repair.", "A parts list is legally identical to a license.", "Open projects never change versions."],
                "El texto presenta beneficios informativos y límites físicos, técnicos y legales.",
                3,
                "does not guarantee that repair will be easy or safe",
                ["Se mencionan alta tensión y herramientas especializadas.", "Licencias y documentación resuelven problemas distintos.", "Declarar versiones es parte de una buena publicación."],
            ),
            q(
                "READ_DETAIL",
                "Which item may be included in an open hardware project?",
                "A circuit layout",
                ["A promise that no component will fail", "A ban on all modifications", "An unpublished manufacturing secret"],
                "El primer párrafo enumera diagramas, circuitos, software, piezas e instrucciones.",
                1,
                "circuit layouts",
                ["La apertura ayuda a detectar fallas, no promete ausencia.", "Modificar es uno de los usos permitidos según licencia.", "La información esencial se publica."],
            ),
            q(
                "READ_INFERENCE",
                "Why is version information important?",
                "Instructions or replacement parts may apply only to particular revisions.",
                ["Every version uses exactly the same components.", "Versions replace the need for testing.", "A version number removes high voltage."],
                "Si diseños evolucionan, identificar la revisión evita aplicar especificaciones incompatibles.",
                1,
                "states versions, tolerances, and testing procedures",
                ["Los cambios entre versiones justifican declararlas.", "Las pruebas siguen siendo necesarias.", "Los riesgos físicos no desaparecen con metadatos."],
                2,
            ),
            q(
                "READ_REFERENCE",
                "The word “they” in the final sentence refers to",
                "licenses and practical documentation",
                ["sealed materials", "recurring failures", "replacement components"],
                "El pronombre retoma los dos elementos comparados inmediatamente antes.",
                3,
                "Both are important, but they solve different problems.",
                ["Los materiales son una barrera física.", "Las fallas son información que la comunidad descubre.", "Las piezas pueden proponerse a partir de documentación."],
            ),
            q(
                "READ_NEGATIVE_DETAIL",
                "Which factor is NOT presented as a barrier to practical repair?",
                "Users being allowed to read a parts list",
                ["specialized tools", "high voltage", "components that are no longer available"],
                "El acceso a la lista favorece identificación; las otras tres condiciones dificultan reparación.",
                3,
                "Specialized tools, high voltage, sealed materials, or unavailable components",
                ["Herramientas especiales limitan quién puede intervenir.", "La alta tensión añade riesgo.", "La falta de componentes impide sustitución directa."],
            ),
        ],
    },
    {
        slug: "keeping-food-cold",
        title: "A Chain That Must Stay Cold",
        topicEs: "Logística de refrigeración",
        genre: "technology",
        cefr: "B2",
        difficulty: 2,
        length: "standard",
        estimatedMinutes: 7,
        paragraphs: [
            "A cold chain keeps temperature-sensitive products within a specified range from production to use. It may include precooling at a farm, refrigerated storage, insulated vehicles, transfer centers, retail cabinets, and household refrigerators. The chain is only as reliable as its weakest transfer, because a product can warm rapidly while waiting on an uncovered loading platform.",
            "Temperature history matters more than a reading taken at the destination. Some damage accumulates gradually, while crossing a critical threshold can allow rapid microbial growth or alter a medicine. Small data loggers travel with shipments and record conditions over time. Their position inside a box should reflect the product rather than the coldest nearby surface. Fixed sensors monitor warehouses and vehicles, but they may not represent the temperature inside every package.",
            "Packaging can slow heat transfer but cannot provide unlimited cooling. Ice packs, phase-change materials, insulation, and airflow must be selected for the route and product. Packing boxes too tightly can block cold air in a refrigerated truck; leaving excessive empty space can permit shifting and damage.",
            "Operators prepare for failures such as delayed flights, power cuts, and broken doors. A response plan identifies alternative storage, safe time limits, and who can decide whether goods remain usable. Staff rehearse transfers, so emergency equipment can be found and activated quickly. Discarding everything after a minor deviation creates waste, but accepting products without evidence can create health risks. Good cold-chain management combines prevention with documented decisions after an interruption.",
        ],
        questions: [
            q(
                "READ_MAIN_IDEA",
                "Which idea about cold-chain management is central to the passage?",
                "Safe delivery depends on continuous monitoring, suitable packaging, and planned responses to interruptions.",
                ["A final temperature reading reveals every earlier problem.", "Insulation keeps products cold forever without energy.", "All deviations require automatic disposal."],
                "Los párrafos recorren puntos débiles, historial, empaque y decisiones documentadas ante fallas.",
                4,
                "combines prevention with documented decisions after an interruption",
                ["La historia de temperatura es más informativa.", "El aislamiento solo ralentiza transferencia.", "La decisión depende de magnitud, tiempo y evidencia."],
            ),
            q(
                "READ_DETAIL",
                "Why can a loading platform be a weak point?",
                "Products may warm while waiting outside controlled storage.",
                ["It records temperature too frequently.", "It always contains excessive insulation.", "It prevents vehicles from arriving."],
                "El primer párrafo usa la espera descubierta como ejemplo de ruptura entre etapas refrigeradas.",
                1,
                "warm rapidly while waiting on an uncovered loading platform",
                ["El problema es falta de control, no exceso de datos.", "No se describe aislamiento en la plataforma.", "Puede haber espera aunque el vehículo llegue."],
            ),
            q(
                "READ_RHETORICAL_PURPOSE",
                "Why does the author contrast fixed sensors with package loggers?",
                "To show that measurements at different locations may describe different conditions",
                ["To argue that warehouses should never be monitored", "To prove that every package has the same temperature", "To show that loggers actively cool products"],
                "Un sensor ambiental no siempre representa el interior de cada caja; el registrador viajero conserva otra escala de evidencia.",
                2,
                "may not represent the temperature inside every package",
                ["Los sensores fijos siguen siendo útiles.", "La variación entre paquetes es precisamente la limitación.", "Los registradores miden, no refrigeran."],
                2,
            ),
            q(
                "READ_INFERENCE",
                "Why might tightly packed boxes be a problem inside a refrigerated truck?",
                "They can prevent cooled air from circulating around the load.",
                ["They make every product freeze instantly.", "They increase the accuracy of household refrigerators.", "They eliminate all movement damage outside the truck."],
                "El tercer párrafo indica que un empaque compacto puede bloquear el flujo necesario para repartir frío.",
                3,
                "Packing boxes too tightly can block cold air",
                ["El bloqueo puede generar zonas cálidas, no congelación universal.", "El contexto es transporte, no refrigeración doméstica.", "Otros riesgos pueden persistir."],
                2,
            ),
            q(
                "READ_PARAPHRASE",
                "What does the final paragraph say about decisions after a temperature deviation?",
                "They should use recorded evidence to balance waste against safety.",
                ["Every affected shipment should be accepted.", "Minor changes always make products dangerous.", "Only the driver may decide without records."],
                "El cierre evita tanto descarte automático como aceptación sin pruebas.",
                4,
                "Discarding everything after a minor deviation creates waste, but accepting products without evidence can create health risks.",
                ["La aceptación universal ignora riesgo.", "Una desviación menor no implica daño seguro.", "El plan define autoridad y usa documentación."],
                3,
            ),
        ],
    },
    {
        slug: "why-keyboards-keep-their-shape",
        title: "Why Keyboards Keep Their Shape",
        topicEs: "Persistencia de diseños tecnológicos",
        genre: "technology",
        cefr: "B1",
        difficulty: 2,
        length: "short",
        estimatedMinutes: 5,
        paragraphs: [
            "Early typewriters used mechanical arms that struck an inked ribbon. If nearby arms were activated in rapid succession, they could collide or jam. Keyboard layouts distributed commonly paired letters across the mechanism, though the history of any particular arrangement involved several design revisions and commercial choices.",
            "Once typists learned a layout, changing it imposed a cost. Schools taught it, manufacturers produced compatible machines, and workplaces evaluated speed using familiar patterns. Later technologies no longer had the same mechanical constraints, but the network of trained users and established equipment remained.",
            "Alternative layouts may offer advantages for particular languages, tasks, or accessibility needs. Their existence does not automatically cause a universal switch. A technology can persist because coordination is valuable: an imperfect shared standard may be more useful than several incompatible improvements.",
        ],
        questions: [
            q(
                "READ_MAIN_IDEA",
                "Why do established keyboard layouts persist according to the passage?",
                "Mechanical history and the benefits of a shared learned standard reinforce them.",
                ["Modern keyboards still use colliding typewriter arms.", "No alternative layout has ever been designed.", "Changing a layout has no training cost."],
                "El texto une origen mecánico con dependencia de aprendizaje, fabricación y coordinación.",
                3,
                "coordination is valuable",
                ["Las tecnologías posteriores perdieron esa restricción.", "Se mencionan alternativas.", "Usuarios y escuelas ya invirtieron en el patrón."],
            ),
            q(
                "READ_DETAIL",
                "What problem could occur when nearby typewriter arms moved quickly?",
                "They could collide or jam.",
                ["They changed the language being typed.", "They erased the inked ribbon.", "They made schools stop teaching."],
                "El primer párrafo identifica interferencia física entre brazos como restricción de diseño.",
                1,
                "they could collide or jam",
                ["El mecanismo no modifica el idioma.", "La cinta recibe golpes para imprimir.", "Las escuelas aparecen en la adopción posterior."],
            ),
            q(
                "READ_VOCAB_CONTEXT",
                "The word “imposed” in paragraph 2 is closest in meaning to",
                "created",
                ["measured", "removed", "photographed"],
                "Cambiar el estándar generaba un costo de reaprendizaje y compatibilidad.",
                2,
                "changing it imposed a cost",
                ["La evaluación de velocidad es un uso separado.", "El costo no desaparecía.", "No se trata de imágenes."],
            ),
            q(
                "READ_INFERENCE",
                "Why did electronic keyboards retain older layouts after mechanical jams disappeared?",
                "Users and institutions had already coordinated around familiar arrangements.",
                ["Electronic devices required inked ribbons.", "Every old design was technically perfect.", "Manufacturers could not move printed letters."],
                "La inversión colectiva en enseñanza, habilidad y equipo creó costo de transición.",
                2,
                "network of trained users and established equipment remained",
                ["La electrónica no depende de cinta mecánica.", "El cierre admite estándares imperfectos.", "Las teclas pueden reorganizarse técnicamente."],
                2,
            ),
            q(
                "READ_TONE",
                "How does the author view alternative layouts?",
                "They may be useful, but adoption depends on more than technical advantage.",
                ["They are impossible to learn.", "They should be legally prohibited.", "They guarantee an immediate universal transition."],
                "El texto reconoce ventajas específicas y explica por qué la coordinación puede frenar un cambio general.",
                3,
                "Their existence does not automatically cause a universal switch.",
                ["Pueden aprenderse y servir a necesidades.", "No se propone prohibición.", "La transición automática se niega."],
                2,
            ),
        ],
    },
    {
        slug: "seeing-storms-from-orbit",
        title: "Seeing Storms from Orbit",
        topicEs: "Observación meteorológica satelital",
        genre: "technology",
        cefr: "B2",
        difficulty: 2,
        length: "standard",
        estimatedMinutes: 7,
        paragraphs: [
            "Weather satellites observe large areas repeatedly, including oceans and remote regions with few ground stations. Some remain above nearly the same longitude, providing frequent images of one broad region. Their rapid updates are useful for following the development of storms. Others orbit closer to Earth and pass over different locations, producing more detailed observations but revisiting a given place less continuously.",
            "Satellite instruments measure radiation in visible, infrared, and microwave bands. Visible images show reflected sunlight and therefore depend on daylight. Infrared measurements estimate temperatures of cloud tops or surfaces and work at night. Certain microwave signals can pass through clouds and provide information about rain, moisture, sea ice, or ocean winds. Each band responds to a different combination of atmospheric and surface properties.",
            "An image is not a direct photograph in every band. Computers convert measured radiation into colors, and the chosen color scale emphasizes particular features. The same measurement can be displayed with several palettes for different tasks. Forecasters compare several channels and ground observations rather than interpreting one bright area in isolation. Models also use satellite data to estimate the current atmospheric state before calculating a forecast.",
            "Satellites have limitations. They infer many quantities indirectly, instruments age, and clouds or surface properties can complicate retrieval. Calibration against trusted surface measurements remains necessary throughout the mission. Instrument teams compare overlapping observations as satellites cross. The value of satellite observation comes from broad, repeated coverage combined with—not substituted for—other independent scientific evidence.",
        ],
        questions: [
            q(
                "READ_PRIMARY_PURPOSE",
                "What does the passage explain about weather satellites?",
                "They provide broad, varied observations that require interpretation and calibration with other evidence.",
                ["They directly measure every important weather quantity without using models.", "Visible satellite images work equally well during day and night.", "A single satellite orbit supplies continuous high-resolution detail everywhere on Earth."],
                "El texto cubre órbitas, bandas, procesamiento, modelos y límites para construir una visión integrada.",
                4,
                "combined with—not substituted for—other independent scientific evidence",
                ["Muchas cantidades se infieren.", "La banda visible depende de luz diurna.", "Las órbitas ofrecen compromisos entre frecuencia y detalle."],
            ),
            q(
                "READ_DETAIL",
                "Which type of measurement can be used at night to estimate cloud-top temperature?",
                "Infrared radiation",
                ["Visible reflected light", "A printed color scale alone", "Mechanical typewriter motion"],
                "El segundo párrafo distingue visible diurno de infrarrojo térmico disponible de noche.",
                2,
                "Infrared measurements estimate temperatures of cloud tops or surfaces and work at night.",
                ["La imagen visible necesita luz solar.", "La escala representa datos, no es sensor.", "El teclado no participa en meteorología."],
            ),
            q(
                "READ_REFERENCE",
                "The word “Others” in paragraph 1 refers to",
                "satellites in lower orbits that pass over different places",
                ["remote ground stations", "broad ocean regions", "infrared color scales"],
                "El término contrasta dos grupos de satélites: los casi estacionarios y los de órbita más baja.",
                1,
                "Others orbit closer to Earth",
                ["Las estaciones son otra fuente de medición.", "Las regiones son observadas, no orbitan.", "Las escalas aparecen después."],
            ),
            q(
                "READ_INFERENCE",
                "Why do forecasters examine several channels?",
                "Different wavelengths reveal different properties and reduce ambiguity.",
                ["Every channel contains exactly the same information.", "Combining channels stops instruments from aging.", "A visible image already measures ocean wind directly at night."],
                "La variedad de bandas y la conversión de color exige contrastar señales antes de atribuir significado.",
                3,
                "compare several channels and ground observations",
                ["Cada banda responde a propiedades distintas.", "El envejecimiento requiere calibración.", "La banda visible depende del sol y otras bandas infieren viento."],
                2,
            ),
            q(
                "READ_PARAPHRASE",
                "How does the conclusion evaluate satellite evidence?",
                "Satellite coverage is powerful when it complements models and measurements from other sources.",
                ["Satellites make ground observations obsolete.", "Calibration is needed only before launch.", "Indirect measurements have no scientific value."],
                "El cierre valora alcance y repetición, condicionados por calibración e integración.",
                4,
                "combined with—not substituted for—other independent scientific evidence",
                ["La evidencia terrestre se compara continuamente.", "Los instrumentos envejecen y se recalibran.", "La inferencia es útil cuando se valida."],
                3,
            ),
        ],
    },
    {
        slug: "sensors-in-a-river",
        title: "Sensors in a River",
        topicEs: "Monitoreo ambiental con sensores",
        genre: "technology",
        cefr: "B2",
        difficulty: 2,
        length: "standard",
        estimatedMinutes: 7,
        paragraphs: [
            "A water-quality sensor can record temperature, conductivity, oxygen, or turbidity at intervals much shorter than occasional manual sampling. Frequent records reveal daily cycles and brief events, such as a muddy pulse after rain, that a monthly visit could miss. A sequence can also show whether conditions recover after the event. Sensors are especially useful where change happens quickly.",
            "Continuous data are not automatically reliable. Algae and sediment grow or settle on sensor surfaces, gradually shifting readings. Electronic components drift, batteries weaken, and communication can fail. Technicians clean instruments, compare them with reference standards, and inspect patterns for sudden jumps or implausibly constant values. Field notes help separate maintenance effects from real environmental change.",
            "Placement matters. A sensor near a pipe may detect a discharge but not represent the full river. One near the bank may experience different flow from the center. Seasonal changes in water level can also leave an instrument in an unsuitable position. Networks use several locations and combine fixed instruments with laboratory samples. Metadata record depth, calibration, maintenance, and periods when a reading should be treated cautiously.",
            "Public dashboards can make river conditions visible in near real time, but a number without context may cause confusion. A temporary rise in turbidity after a storm is not equivalent to a toxic spill. Historical ranges help users judge whether a value is unusual for that season. Effective systems pair measurements with thresholds, explanations, uncertainty, and contact information for unusual events.",
        ],
        questions: [
            q(
                "READ_MAIN_IDEA",
                "What does the passage emphasize about river sensors?",
                "Their frequent data are useful only with maintenance, representative placement, and context.",
                ["They make laboratory samples unnecessary.", "Every unusual value indicates a toxic spill.", "A single bank sensor represents an entire river."],
                "El texto combina ventaja temporal con ensuciamiento, calibración, ubicación y comunicación.",
                4,
                "pair measurements with thresholds, explanations, uncertainty",
                ["Las muestras de laboratorio complementan.", "La turbidez por tormenta tiene otra interpretación.", "La posición puede sesgar representatividad."],
            ),
            q(
                "READ_DETAIL",
                "What can frequent sensor records reveal that monthly sampling may miss?",
                "A short muddy pulse following rainfall",
                ["The legal ownership of every riverbank", "The manufacturing history of the sensor", "A permanent absence of daily cycles"],
                "El primer párrafo da el evento breve posterior a lluvia como ejemplo directo.",
                1,
                "a muddy pulse after rain",
                ["La propiedad no es una variable de calidad medida.", "La fabricación no se infiere del agua.", "Los registros revelan, no eliminan, ciclos diarios."],
            ),
            q(
                "READ_VOCAB_CONTEXT",
                "The word “drift” in paragraph 2 is closest in meaning to",
                "change gradually away from accurate values",
                ["move downstream as a boat", "become perfectly calibrated", "display a storm explanation"],
                "La deriva electrónica aparece junto con suciedad y envejecimiento como fuente progresiva de error.",
                2,
                "Electronic components drift",
                ["El sujeto son componentes, no una embarcación.", "La calibración corrige la deriva.", "Las explicaciones pertenecen al tablero público."],
            ),
            q(
                "READ_INFERENCE",
                "Why are implausibly constant values suspicious?",
                "A failed or fouled sensor may stop responding to real environmental variation.",
                ["Rivers naturally have no variation.", "Reference standards always produce random numbers.", "Constant readings prove the battery is fully charged."],
                "Como el río muestra ciclos y eventos, una línea artificialmente plana puede revelar bloqueo o falla.",
                2,
                "inspect patterns for sudden jumps or implausibly constant values",
                ["El primer párrafo destaca cambios diarios.", "Los estándares sirven para comparar precisión.", "La batería débil es una causa posible de falla, no se descarta por constancia."],
                2,
            ),
            q(
                "READ_RHETORICAL_PURPOSE",
                "Why does the author contrast storm turbidity with a toxic spill?",
                "To illustrate why public measurements need interpretation and context",
                ["To claim that storms never affect rivers", "To show that turbidity sensors measure no real property", "To prove that every dashboard should hide unusual events"],
                "Valores superficiales parecidos pueden tener causas y riesgos diferentes, por lo que se necesitan explicaciones.",
                4,
                "a number without context may cause confusion",
                ["La lluvia puede elevar turbidez.", "La turbidez es una variable válida.", "Se propone explicar y ofrecer contacto, no ocultar."],
                3,
            ),
        ],
    },
    {
        slug: "printing-as-a-system",
        title: "Printing as a System",
        topicEs: "Producción técnica de libros impresos",
        genre: "technology",
        cefr: "B2",
        difficulty: 3,
        length: "long",
        estimatedMinutes: 13,
        paragraphs: [
            "Movable-type printing is often represented by the press itself, but repeatable book production depended on a larger technical system. Printers needed durable type, consistent ink, suitable paper, skilled compositors, reliable presses, and markets large enough to recover the cost of preparing a text. A shortage in any one element could delay the entire production plan.",
            "Type had to combine uniformity with flexibility. Individual letters were cast so they could be arranged into lines, locked into a frame, inked, printed, cleaned, and reused. If pieces differed too much in height, some letters printed darkly while others barely touched the paper. Foundries organized thousands of pieces by character and size. Metal alloys balanced hardness, casting detail, and the need to remelt worn type.",
            "Compositors assembled text by hand, selecting letters from divided cases. They had to read while working backward relative to the printed impression and manage spacing, so lines fit a chosen width. Decisions about abbreviation and line breaks affected both labor and appearance. A completed page form contained not only letters but blank pieces that created spaces and held the structure tightly together.",
            "Ink developed for writing did not automatically work on metal type. Thin ink could run off the raised surfaces or spread into paper; printing ink needed enough body to transfer a clear image. Paper also varied in thickness, moisture, and strength. Dampening could improve printing but had to be controlled sheet by sheet. Printers adjusted pressure and packing rather than assuming every sheet would behave identically.",
            "Errors could enter at many stages. A compositor might select the wrong letter, type could shift, a page could be imposed in the wrong position, or sheets could be folded incorrectly. Proofreading corrected some mistakes before a full run, but stopping production and resetting type cost time. Lists of corrections could be added when resetting was impractical. Surviving copies of the same edition sometimes contain different corrections made during printing.",
            "The economics shaped design. Large initial labor made longer print runs cheaper per copy, but unsold books tied up capital. Size, paper quality, illustrations, and the number of copies all changed financial risk. Printers cooperated with publishers, booksellers, authors, institutions, and sometimes governments that granted privileges or imposed censorship. Technical capacity did not by itself determine what reached readers.",
            "Printing increased the number of comparatively consistent copies, yet it did not produce perfect uniformity. Hand work, material variation, correction, binding, and later use gave copies individual histories. Libraries sometimes combined sheets from different states when repairing volumes. Owners also annotated, trimmed, rebound, or rearranged their surviving personal copies after purchase. Understanding printing as a system explains both its power to reproduce text and the differences that remain within apparently identical books.",
        ],
        questions: [
            q(
                "READ_MAIN_IDEA",
                "What is the central argument of the passage?",
                "Repeatable printing resulted from coordinated materials, labor, machinery, and markets rather than the press alone.",
                ["A printing press produced books without human labor.", "Every copy from one edition was perfectly identical.", "Writing ink always worked well on metal type."],
                "Cada párrafo añade una parte del sistema y el cierre explica reproducción junto con variación.",
                1,
                "depended on a larger technical system",
                ["Compositores, correctores y otros trabajadores eran esenciales.", "Se conservan correcciones y diferencias entre copias.", "La tinta de escritura podía ser demasiado fluida."],
                3,
            ),
            q(
                "READ_DETAIL",
                "Why was consistent type height important?",
                "Uneven pieces would produce letters with different darkness or no clear impression.",
                ["It determined which books governments censored.", "It made every sheet equally moist.", "It eliminated the need for spacing."],
                "El segundo párrafo relaciona altura física con contacto uniforme sobre papel.",
                2,
                "some letters printed darkly while others barely touched the paper",
                ["La censura pertenece a economía y política.", "La humedad era propiedad del papel.", "Los espacios requerían piezas en la forma."],
            ),
            q(
                "READ_VOCAB_CONTEXT",
                "The word “body” in paragraph 4 is closest in meaning to",
                "thickness or consistency",
                ["human figure", "main text of a law", "group of readers"],
                "La tinta debía permanecer sobre el relieve y transferirse sin escurrir ni extenderse demasiado.",
                4,
                "needed enough body to transfer a clear image",
                ["El contexto es material, no anatomía.", "No se habla de contenido jurídico.", "Los lectores aparecen en distribución, no en la tinta."],
            ),
            q(
                "READ_RHETORICAL_PURPOSE",
                "Why does the author mention blank pieces inside a page form?",
                "To show that nonprinting components were necessary to organize and secure printable type",
                ["To prove that blank pages were more valuable than printed ones", "To explain why compositors did not read", "To show that letters were carved directly into paper"],
                "Los blancos crean espacios y mantienen la forma aunque no dejan tinta.",
                3,
                "blank pieces that created spaces and held the structure tightly together",
                ["Su función era estructural, no aumentar valor de páginas vacías.", "Los compositores leían mientras armaban.", "Las letras metálicas se colocaban antes de imprimir."],
                2,
            ),
            q(
                "READ_INFERENCE",
                "Why might two copies from the same edition contain different errors?",
                "Corrections could be made while the print run was already in progress.",
                ["Every copy used a different alphabet.", "Paper automatically rewrote the text after binding.", "Printers never examined proofs."],
                "Si se detuvo y corrigió la forma tras imprimir algunas hojas, los ejemplares anteriores conservan otro estado.",
                5,
                "different corrections made during printing",
                ["El mismo conjunto de caracteres servía al tiraje.", "El papel no altera palabras por sí solo.", "La corrección de pruebas se menciona expresamente."],
                3,
            ),
            q(
                "READ_NEGATIVE_DETAIL",
                "All of the following could introduce variation into printed books EXCEPT",
                "a guarantee that materials never changed",
                ["differences in paper moisture", "type shifting during production", "corrections made during the run"],
                "La invariabilidad garantizada no se describe; las otras fuentes de variación aparecen explícitamente.",
                7,
                "material variation, correction, binding, and later use",
                ["El papel variaba en humedad.", "El tipo podía desplazarse.", "Las correcciones creaban estados distintos."],
            ),
            q(
                "READ_REFERENCE",
                "The phrase “the structure” in paragraph 3 refers to",
                "the locked arrangement of type and spacing pieces",
                ["the market for unsold books", "a government censorship office", "the metal alloy before casting"],
                "Las piezas en blanco sostienen físicamente la forma de página ya compuesta.",
                3,
                "held the structure tightly together",
                ["El mercado se discute más tarde.", "La censura no forma parte de la página.", "La aleación produce tipos individuales antes de su montaje."],
            ),
            q(
                "READ_PARAPHRASE",
                "Which statement best expresses paragraph 6?",
                "Production costs and institutional relationships influenced which texts were printed and sold.",
                ["Technical ability guaranteed that every manuscript found readers.", "Long print runs always sold out.", "Booksellers had no role in publication."],
                "El párrafo une costo inicial, riesgo de inventario, colaboración, privilegios y censura.",
                6,
                "Technical capacity did not by itself determine what reached readers.",
                ["El acceso al equipo no asegura publicación o demanda.", "Los libros no vendidos inmovilizaban capital.", "Los libreros son uno de los actores enumerados."],
                3,
            ),
            q(
                "READ_TONE",
                "How does the author treat the idea of identical printed copies?",
                "As broadly useful but too simple to describe material variation between copies",
                ["As completely accurate in every detail", "As impossible because no text was repeated", "As irrelevant to printing history"],
                "El cierre reconoce consistencia comparativa y luego enumera fuentes de individualidad.",
                7,
                "comparatively consistent copies, yet it did not produce perfect uniformity",
                ["La uniformidad perfecta se niega.", "La reproducción de texto sí fue poderosa.", "Las diferencias son parte de la explicación histórica."],
                3,
            ),
            q(
                "READ_ORGANIZATION",
                "How is the printing passage organized?",
                "It moves through components and stages of production before considering economics and overall consequences.",
                ["It presents a biography of one author.", "It compares only two kinds of paper.", "It begins with censorship and never discusses machinery."],
                "La secuencia recorre tipo, composición, tinta, errores, mercado y síntesis.",
                7,
                "Understanding printing as a system",
                ["No hay personaje biográfico central.", "El papel es una variable entre muchas.", "La maquinaria y los materiales ocupan la mayor parte."],
                3,
            ),
        ],
    },
    {
        slug: "microgrids-that-can-island",
        title: "A Grid That Can Become an Island",
        topicEs: "Microredes eléctricas resilientes",
        genre: "technology",
        cefr: "C1",
        difficulty: 3,
        length: "long",
        estimatedMinutes: 14,
        paragraphs: [
            "A microgrid is a local electrical network containing loads and one or more energy resources. Under normal conditions it may exchange electricity with the larger utility grid, buying power or exporting a surplus. If the external network fails, some microgrids can disconnect at a controlled point and continue operating independently, a mode known as islanding. Others are designed only for connected operation.",
            "Islanding requires more than adding solar panels. A grid-connected system usually relies on the wider network to stabilize voltage and frequency. Once separated, local controls must perform that task. At least one resource must respond quickly when demand or generation changes, and protective devices must distinguish faults inside the microgrid from problems beyond it. These controls need testing under realistic transitions.",
            "Energy storage is useful because it can absorb or deliver power rapidly. A battery may smooth short fluctuations and support the transition into island mode. Its energy capacity is limited, however. Usable capacity also declines with age and extreme temperature. Several hours of cloudy weather or high demand can exhaust it unless other generators operate or some loads are reduced. Operators track both power and remaining energy.",
            "Microgrids therefore classify loads by priority. A hospital might maintain emergency rooms, refrigeration, and communications while temporarily disconnecting offices or nonessential equipment. Automated controls can shed loads quickly, but priorities require human decisions made before an emergency. Different users may disagree about what is essential, especially when an outage lasts for days. Published plans can make those choices more accountable.",
            "Renewable generation introduces forecasts as well as uncertainty. Solar and wind reduce fuel use, but their output varies. Controllers combine weather predictions, current battery charge, expected demand, and fuel availability to decide whether to store energy or use it. They may preserve extra charge before a predicted storm. A forecast error does not necessarily cause failure if the system retains adequate reserve.",
            "Connection and reconnection must be managed carefully. An islanded microgrid cannot simply close a switch if its voltage phase and frequency differ from the utility network. Controls synchronize the two systems first. Utility workers also need clear indication that local wires may remain energized during a wider outage. Protection settings must coordinate, so a local fault is isolated without unnecessarily shutting down every critical load.",
            "The value of a microgrid depends on more than whether it survives one demonstration. Equipment needs maintenance, software must be secured, fuel contracts may be needed, and operators require training. Replacement parts and technical support must remain reliably available years after installation. Financing must cover operation as well as construction. A technically advanced system that a community cannot afford to maintain may provide less resilience than a simpler design supported by durable local institutions.",
        ],
        questions: [
            q(
                "READ_MAIN_IDEA",
                "What main idea does the passage develop about microgrids?",
                "Independent operation requires coordinated controls, resources, priorities, safety, and long-term support.",
                ["Solar panels alone guarantee unlimited island operation.", "A microgrid must remain permanently disconnected.", "Maintenance becomes unnecessary after one successful test."],
                "El pasaje expande islanding desde hardware hacia control, energía, decisiones, seguridad y sostenibilidad institucional.",
                7,
                "depends on more than whether it survives one demonstration",
                ["La separación exige más que paneles.", "Normalmente puede intercambiar con la red.", "El cierre exige mantenimiento y capacitación."],
                3,
            ),
            q(
                "READ_DETAIL",
                "What function must local controls assume after islanding?",
                "Stabilizing voltage and frequency",
                ["Creating unlimited battery capacity", "Writing fuel contracts automatically", "Turning every load into a generator"],
                "El segundo párrafo explica que esa referencia deja de venir de la red grande.",
                2,
                "local controls must perform that task",
                ["La capacidad energética sigue limitada.", "Los contratos son una necesidad institucional.", "Las cargas consumen energía aunque algunas se desconecten."],
            ),
            q(
                "READ_VOCAB_CONTEXT",
                "The word “shed” in paragraph 4 is closest in meaning to",
                "disconnect",
                ["predict", "repair", "synchronize"],
                "Para conservar cargas prioritarias, el control corta temporalmente otras.",
                4,
                "Automated controls can shed loads quickly",
                ["Los pronósticos se usan para renovables.", "Reparar no reduce demanda inmediata.", "Sincronizar se aplica al reconectar redes."],
            ),
            q(
                "READ_RHETORICAL_PURPOSE",
                "Why does the author give the example of a hospital?",
                "To illustrate how limited power requires ranking loads by importance",
                ["To prove that offices never use electricity", "To show that batteries work only in hospitals", "To identify a load that must always be disconnected"],
                "La selección entre urgencias y oficinas concreta decisiones de prioridad durante operación limitada.",
                4,
                "classify loads by priority",
                ["Las oficinas consumen pero pueden ser menos prioritarias.", "El almacenamiento sirve en múltiples microredes.", "Las áreas clínicas se mantienen, no se desconectan siempre."],
                2,
            ),
            q(
                "READ_INFERENCE",
                "Why is battery power alone not always sufficient during a long outage?",
                "Its stored energy may be depleted before generation or demand recovers.",
                ["A battery cannot change output rapidly.", "Clouds immediately damage every battery.", "Storage increases every load automatically."],
                "El texto distingue respuesta rápida de duración limitada y plantea generadores o reducción de carga.",
                3,
                "Several hours of cloudy weather or high demand can exhaust it",
                ["La rapidez es precisamente una ventaja.", "Las nubes reducen solar, no destruyen batería.", "El almacenamiento no crea demanda por sí mismo."],
                3,
            ),
            q(
                "READ_NEGATIVE_DETAIL",
                "All of the following are mentioned as inputs to microgrid control decisions EXCEPT",
                "the color of the control-room walls",
                ["weather forecasts", "battery charge", "expected demand"],
                "El color del edificio no se usa; las otras variables aparecen en el quinto párrafo.",
                5,
                "weather predictions, current battery charge, expected demand, and fuel availability",
                ["El clima ayuda a anticipar renovables.", "La carga disponible condiciona reserva.", "La demanda prevista guía almacenamiento y uso."],
            ),
            q(
                "READ_REFERENCE",
                "The phrase “the two systems” in paragraph 6 refers to",
                "the islanded microgrid and the utility network",
                ["solar and wind forecasts", "emergency rooms and offices", "fuel contracts and training"],
                "Antes de cerrar el interruptor se alinean fase y frecuencia de la red local y externa.",
                6,
                "Controls synchronize the two systems first.",
                ["Los pronósticos son entradas del controlador.", "Las áreas son cargas dentro del hospital.", "Los contratos y formación apoyan operación."],
            ),
            q(
                "READ_PARAPHRASE",
                "Which statement best expresses the reserve point in paragraph 5?",
                "Uncertain forecasts are manageable when the system keeps enough flexible capacity.",
                ["Forecasts must be perfectly accurate for any microgrid to work.", "Renewable output never changes.", "Reserve means disconnecting every critical load."],
                "El pasaje no exige predicción perfecta; exige margen para absorber error.",
                5,
                "A forecast error does not necessarily cause failure if the system retains adequate reserve.",
                ["La reserva reduce dependencia de exactitud total.", "Solar y viento varían.", "Las cargas críticas se priorizan."],
                3,
            ),
            q(
                "READ_TONE",
                "How does the author evaluate technologically advanced microgrids?",
                "Their value is conditional on maintainability, security, affordability, and trained operation.",
                ["The most complex design is always the most resilient.", "Institutional support has no technical relevance.", "One demonstration proves permanent reliability."],
                "El cierre cuestiona evaluar solo desempeño inicial o sofisticación.",
                7,
                "may provide less resilience than a simpler design supported by durable local institutions",
                ["La complejidad puede exceder capacidad local.", "Las instituciones determinan mantenimiento y operación.", "Se exige desempeño sostenido."],
                3,
            ),
            q(
                "READ_ORGANIZATION",
                "How does the passage progress?",
                "It defines islanding, explains operational requirements, and ends with conditions for durable resilience.",
                ["It lists electrical prices in several countries.", "It describes only solar-panel manufacturing.", "It argues that reconnection needs no safety procedure."],
                "La estructura va de concepto y control a almacenamiento, prioridades, pronóstico, reconexión y sostenibilidad.",
                7,
                "The value of a microgrid depends on more",
                ["No hay comparación de tarifas nacionales.", "La generación solar es una parte del sistema.", "El sexto párrafo exige sincronización y advertencias."],
                3,
            ),
        ],
    },
];
